/* ============================================================
   관리자 기능(개인·교육용 클라이언트 구현)
   상업/공개 운영에서는 관리자 권한 및 명령 검증을 서버로 이전해야 합니다.
   화면 효과는 미니톡 창 내부에만 표시됩니다.
   ============================================================ */
MiniTalk.Features.Admin=(()=>{MiniTalk.Events.on("rt:command",handleCommand);function visible(){return MiniTalk.Store.get("admin")===true}function render(host){MiniTalk.UI.Shell.setHeader("관리자",[],{back:()=>MiniTalk.Router.go("chats")});const D=MiniTalk.UI.Dom,view=D.el("section",{class:"view"}),list=D.el("div",{class:"card-list"});if(!visible()){list.append(D.el("p",{class:"muted",text:"채팅 입력창에 관리자 명령어를 입력해야 합니다."}));view.append(list);host.replaceChildren(view);return}const card=D.el("section",{class:"tool-card"});card.innerHTML='<label class="field">대상 사용자 ID<input id="adminTarget"></label><label class="field">명령<select id="adminType"><option value="NOTICE">안내문</option><option value="STAMP">도장</option><option value="IMAGE">이미지</option><option value="ALARM">알람</option><option value="TASK">과제</option><option value="LOCK">프로그램 잠금</option><option value="UNLOCK">잠금 해제</option></select></label><label class="field">제목<input id="adminTitle"></label><label class="field">내용/이미지 URL<textarea id="adminBody"></textarea></label><button id="adminSend" class="button primary">전송</button><p class="warning">화면 중앙 효과는 대상 미니톡 창 내부에서만 표시됩니다.</p>';card.querySelector("#adminSend").onclick=async event=>{const button=event.currentTarget,target=card.querySelector("#adminTarget").value.trim(),type=card.querySelector("#adminType").value,title=card.querySelector("#adminTitle").value,body=card.querySelector("#adminBody").value;if(!target)return MiniTalk.UI.Shell.toast("대상 ID를 입력하세요.");button.disabled=true;try{if(type==="TASK")await MiniTalk.Realtime.assignTask(target,{title:title||"과제",description:body});else await MiniTalk.Realtime.sendCommand(target,type,{title,body});MiniTalk.UI.Shell.toast("전송했습니다.")}catch(error){MiniTalk.UI.Shell.toast(error.message||"관리자 명령 전송에 실패했습니다.")}finally{button.disabled=false}};list.append(card,MiniTalk.Features.Shopping.adminPanel(()=>render(host)));view.append(list);host.replaceChildren(view)}
 function handleCommand(cmd){const p=cmd.payload||{};if(cmd.type==="NOTICE")MiniTalk.UI.Shell.toast(`${p.title||"안내"}: ${p.body||""}`);if(cmd.type==="STAMP")effect(p.title||"참 잘했어요");if(cmd.type==="IMAGE")effectImage(p.body);if(cmd.type==="ALARM"){new Audio("assets/sounds/notify.mp3").play().catch(()=>{});effect(p.title||"알람")};if(cmd.type==="LOCK")lock(p.body||"관리자가 사용을 잠갔습니다.");if(cmd.type==="UNLOCK")unlock()}
 function effect(text){const D=MiniTalk.UI.Dom,host=D.byId("overlayHost"),node=D.el("div",{class:"screen-effect",text});host.append(node);new Audio("assets/sounds/stamp.mp3").play().catch(()=>{});setTimeout(()=>node.remove(),2100)}function effectImage(url){if(!url)return;const D=MiniTalk.UI.Dom,host=D.byId("overlayHost"),img=D.el("img",{class:"screen-effect",src:url,alt:"관리자 이미지"});img.style.maxWidth="65vw";img.style.maxHeight="65vh";host.append(img);setTimeout(()=>img.remove(),2100)}function lock(message){MiniTalk.Persistence.set("runtime.lock",{message:String(message||"관리자가 사용을 잠갔습니다."),at:Date.now()});renderLock()}
 function unlock(){MiniTalk.Persistence.remove("runtime.lock");MiniTalk.UI.Dom.byId("hardLock")?.remove();MiniTalk.UI.Shell.toast("관리자 잠금이 해제되었습니다.")}
 function renderLock(){const saved=MiniTalk.Persistence.get("runtime.lock");if(!saved)return false;const D=MiniTalk.UI.Dom,doc=D.doc();D.byId("hardLock")?.remove();const layer=D.el("section",{id:"hardLock",class:"hard-lock","aria-live":"assertive"},[D.el("div",{class:"hard-lock-card"},[D.el("div",{class:"app-mark",text:"M"}),D.el("h2",{text:"미니톡 사용이 잠겼습니다."}),D.el("p",{text:saved.message||"관리자가 사용을 잠갔습니다."}),D.el("small",{class:"muted",text:"관리자가 잠금을 해제하면 다시 사용할 수 있습니다."})])]);doc.body.append(layer);return true}
 function applyStoredLock(){return renderLock()}
 return{id:"admin",title:"관리자",icon:"⚙",nav:false,isVisible:visible,render,applyStoredLock}})();
/* 관리자 메뉴는 항상 등록하되 비활성 상태에서는 안내만 표시합니다. */MiniTalk.Registry.register(MiniTalk.Features.Admin);
