/* ============================================================
   관리자 기능
   - 서버 인증을 통과한 관리자만 화면과 일괄 전송을 사용할 수 있습니다.
   - 대상은 프로필/접속자 명단에서 체크박스로 선택합니다.
   - NOTICE는 사용자가 닫을 수 있는 상단 공지로 표시됩니다.
   ============================================================ */
MiniTalk.Features.Admin=(()=>{
  function adminPopupBounds(){const sourceView=MiniTalk.UI.Dom.doc()?.defaultView||window,scr=sourceView.screen||{},availLeft=Number(scr.availLeft)||0,availTop=Number(scr.availTop)||0,availW=Math.max(640,Number(scr.availWidth)||1280),availH=Math.max(520,Number(scr.availHeight)||800),gap=42,left0=Number(sourceView.screenX??sourceView.screenLeft)||availLeft,top0=Number(sourceView.screenY??sourceView.screenTop)||availTop,w0=Math.max(320,Number(sourceView.outerWidth)||Math.min(520,availW*.42)),rightStart=Math.min(availLeft+availW,left0+w0+gap),rightSpace=Math.max(0,availLeft+availW-rightStart),leftSpace=Math.max(0,left0-gap-availLeft);let width=Math.min(1100,Math.max(rightSpace,leftSpace)),left=rightSpace>=leftSpace?rightStart:left0-gap-width;if(Math.max(rightSpace,leftSpace)<600){width=Math.min(Math.max(650,Math.round(availW*.62)),availW-24);left=(left0+w0/2)<=availLeft+availW/2?availLeft+availW-width-8:availLeft+8}const height=Math.min(820,availH-24),top=Math.max(availTop+8,Math.min(top0,availTop+availH-height-8));return{width:Math.round(Math.max(560,width)),height:Math.round(Math.max(560,height)),left:Math.round(left),top:Math.round(top)}}
  function enforceAdminPopupBounds(win,b){const apply=()=>{try{win.resizeTo(b.width,b.height);win.moveTo(b.left,b.top)}catch{}};apply();setTimeout(apply,80);setTimeout(apply,260)}
  MiniTalk.Events.on("rt:command",handleCommand);
  const visible=()=>MiniTalk.AdminSession?.authorized?.()===true;
  let noticeTimer=0,balanceOwner="",balanceLoaded=false,balanceLoadedAt=0,balanceInFlight=null,balanceMap={},adminPopup=null,adminPopupRoot=null,closingAdminPopup=false,refreshTaskReview=()=>{};
  const pendingCoinRequests=new Map();
  MiniTalk.Events.on("tasks:admin-refresh",()=>refreshTaskReview());

  const desktopAdmin=host=>{const view=host?.ownerDocument?.defaultView||MiniTalk.UI.Dom.doc()?.defaultView||window,screenInfo=view?.screen||screen;return !MiniTalk.MobileImmersive?.isMobile?.()&&Number(screenInfo?.availWidth||view?.innerWidth||0)>=720};
  function closeAdminPopup(){if(closingAdminPopup)return;closingAdminPopup=true;const popup=adminPopup;adminPopup=null;adminPopupRoot=null;try{if(popup&&!popup.closed)popup.close()}catch{}closingAdminPopup=false}
  function returnMessengerToChats(){if(MiniTalk.Store.get("route")==="admin")Promise.resolve(MiniTalk.Router.go("chats")).catch(error=>console.warn("관리자 창 분리 후 대화 화면 복귀 실패",error))}
  function adminPopupStyles(sourceDoc){
    return [...sourceDoc.querySelectorAll('link[rel~="stylesheet"][href]')].map(node=>{
      const href=new URL(node.getAttribute("href"),sourceDoc.baseURI).href.replace(/&/g,"&amp;").replace(/"/g,"&quot;");
      const media=node.getAttribute("media"),mediaAttr=media?` media="${String(media).replace(/&/g,"&amp;").replace(/"/g,"&quot;")}"`:"";
      return `<link rel="stylesheet" href="${href}"${mediaAttr}>`;
    }).join("")
  }
  function waitForAdminPopupStyles(doc){
    const links=[...doc.querySelectorAll('link[rel~="stylesheet"]')];
    if(!links.length)return Promise.resolve();
    return Promise.allSettled(links.map(link=>new Promise(resolve=>{
      if(link.sheet)return resolve();
      const done=()=>resolve();
      link.addEventListener("load",done,{once:true});link.addEventListener("error",done,{once:true});
      setTimeout(done,1800)
    }))).then(()=>undefined)
  }
  function buildAdminPopup(host,popup,bounds,{loading=false}={}){
    const sourceDoc=host?.ownerDocument||MiniTalk.UI.Dom.doc(),doc=popup.document,theme=sourceDoc.documentElement?.dataset?.theme||"light",styles=adminPopupStyles(document),baseHref=String(document.baseURI||sourceDoc.baseURI).replace(/&/g,"&amp;").replace(/'/g,"%27"),critical="html,body{width:100%;min-height:100%;margin:0}body.admin-window-body{min-height:100vh;overflow:hidden;background:#edf1f7;font-family:system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif}.admin-window-shell{width:100%;height:100vh;display:grid;grid-template-rows:auto minmax(0,1fr);overflow:hidden}.admin-window-shell .app-header{min-height:52px;display:flex;align-items:center;gap:10px;padding:0 12px;background:#fff;border-bottom:1px solid #e3e7ee}.admin-window-shell .header-title{display:flex;align-items:center;gap:7px;min-width:0}.admin-window-shell .view-host{min-width:0;min-height:0;overflow:auto}.admin-window-shell #adminWindowView:empty::before{content:\"관리자 화면 불러오는 중…\";display:block;margin:18px;padding:16px;border-radius:14px;background:#fff;color:#667085;font-size:13px}";
    doc.open();doc.write(`<!doctype html><html lang="ko" data-theme="${theme}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><base href="${baseHref}"><style>${critical}</style>${styles}</head><body class="admin-window-body"><section class="app-shell admin-window-shell"><header class="app-header"><button id="backBtn" class="icon-button" aria-label="관리자 창 닫기">‹</button><div class="header-title"><strong id="headerTitle">관리자</strong><span id="connectionBadge" class="connection-badge">온라인</span></div><div id="headerActions" class="header-actions"></div></header><main id="adminWindowView" class="view-host"></main></section><div id="toastHost" class="toast-host" aria-live="polite"></div><div id="notificationHost" class="notification-host" aria-live="assertive"></div><div id="overlayHost" class="overlay-host" aria-live="assertive"></div><div id="modalHost" class="modal-host hidden"></div></body></html>`);doc.close();
    adminPopup=popup;adminPopupRoot=doc.getElementById("adminWindowView");
    if(loading)adminPopupRoot.replaceChildren(MiniTalk.UI.Dom.forDocument(doc).el("section",{class:"view"},[MiniTalk.UI.Dom.forDocument(doc).el("div",{class:"card-list"},[MiniTalk.UI.Dom.forDocument(doc).el("section",{class:"tool-card"},[MiniTalk.UI.Dom.forDocument(doc).el("strong",{text:"관리자 인증 중…"}),MiniTalk.UI.Dom.forDocument(doc).el("small",{class:"muted",text:"인증이 끝나면 이 창에서 관리자 화면을 엽니다."})])])]))
    popup.addEventListener("pagehide",()=>{if(!closingAdminPopup&&adminPopup===popup){adminPopup=null;adminPopupRoot=null}},{once:true});enforceAdminPopupBounds(popup,bounds);return adminPopupRoot
  }
  function reserveDesktopAdminPopup(host){if(!desktopAdmin(host)||host?.ownerDocument?.body?.classList?.contains("admin-window-body"))return false;if(adminPopup&&!adminPopup.closed)return true;const bounds=adminPopupBounds(),sourceView=host?.ownerDocument?.defaultView||window,popup=sourceView.open("","MoaruAdmin",`popup=yes,toolbar=no,location=no,menubar=no,status=no,scrollbars=yes,resizable=yes,width=${bounds.width},height=${bounds.height},left=${bounds.left},top=${bounds.top}`);if(!popup)return false;buildAdminPopup(host,popup,bounds,{loading:true});popup.focus();return true}
  function openDesktopAdmin(host){if(!desktopAdmin(host)||host?.ownerDocument?.body?.classList?.contains("admin-window-body"))return false;if(adminPopup&&!adminPopup.closed){if(adminPopupRoot)waitForAdminPopupStyles(adminPopup.document).then(()=>{if(adminPopupRoot&&adminPopup&&!adminPopup.closed)render(adminPopupRoot)});adminPopup.focus();queueMicrotask(returnMessengerToChats);return true}const bounds=adminPopupBounds(),sourceView=host?.ownerDocument?.defaultView||window,popup=sourceView.open("","MoaruAdmin",`popup=yes,toolbar=no,location=no,menubar=no,status=no,scrollbars=yes,resizable=yes,width=${bounds.width},height=${bounds.height},left=${bounds.left},top=${bounds.top}`);if(!popup)return false;buildAdminPopup(host,popup,bounds);waitForAdminPopupStyles(popup.document).then(()=>{if(adminPopup===popup&&!popup.closed&&adminPopupRoot)render(adminPopupRoot)});popup.focus();queueMicrotask(returnMessengerToChats);return true}

  function isActiveAdminHost(host){return Boolean(host?.isConnected&&(host===adminPopupRoot||MiniTalk.Store.get("route")==="admin"))}

  async function loadBalances(force=false){
    const current=MiniTalk.Store.get("user")||{},owner=String(current.user_id||"");
    if(owner!==balanceOwner){balanceOwner=owner;balanceLoaded=false;balanceLoadedAt=0;balanceMap={}}
    if(!force&&balanceLoaded)return balanceMap;if(balanceInFlight)return balanceInFlight;
    balanceInFlight=MiniTalk.AuthApi.adminUserBalances(owner,MiniTalk.AdminSession.requireToken("ADMIN")).then(rows=>{balanceMap={};rows.forEach(row=>balanceMap[row.user_id]=Math.floor(Number(row.coin)||0));balanceLoaded=true;balanceLoadedAt=Date.now();return balanceMap}).finally(()=>balanceInFlight=null);return balanceInFlight
  }

  function users(){
    return MiniTalk.UserDirectory?.all?.()||[]
  }

  function render(host){
    if(openDesktopAdmin(host)){try{if(adminPopup&&!adminPopup.closed)adminPopup.document.title="관리자"}catch{}return}
    const hostDoc=host?.ownerDocument||MiniTalk.UI.Dom.doc(),D=MiniTalk.UI.Dom.forDocument(hostDoc),Shell=MiniTalk.UI.Shell.forDocument(hostDoc);Shell.setHeader("관리자",[],{back:()=>adminPopup?closeAdminPopup():MiniTalk.Router.go("chats")});const view=D.el("section",{class:"view"}),list=D.el("div",{class:"card-list"});
    if(!visible()){list.append(D.el("p",{class:"muted",text:"설정에서 관리자 인증을 완료해야 합니다."}));view.append(list);host.replaceChildren(view);return}
    const role=MiniTalk.AdminSession.role?.()||"";
    if(role==="SHOP_MANAGER"){
      Shell.setHeader("쇼핑몰 관리자",[],{back:()=>adminPopup?closeAdminPopup():MiniTalk.Router.go("chats")});
      list.append(MiniTalk.Features.Shopping.adminPanel(()=>render(host),{Dom:D,Shell}),MiniTalk.Features.Shopping.deliveryAdminPanel({Dom:D,Shell}));
      view.append(list);host.replaceChildren(view);return
    }
    if(!MiniTalk.UserDirectory?.loaded?.()){const loading=D.el("section",{class:"tool-card"},[D.el("strong",{text:"권한 갱신 중…"})]);list.append(loading);view.append(list);host.replaceChildren(view);MiniTalk.UserDirectory.refresh().then(()=>{if(isActiveAdminHost(host))render(host)}).catch(error=>{loading.replaceChildren(D.el("strong",{text:"권한을 갱신하지 못했습니다."}),D.el("small",{class:"muted",text:error.message||"Apps Script 배포 상태를 확인하세요."}))});return}
    // v104: 코인 잔액 조회가 느려도 잠금/공지/알람/과제 등 전체 관리자 화면을 막지 않습니다.
    // 잔액은 COIN_REWARD를 선택했을 때만 비동기로 가져오며, 관리자 명령 자체는 즉시 사용할 수 있습니다.
    const card=D.el("section",{class:"tool-card admin-command-card"}),selected=new Set(),people=users().map(person=>({...person,coin:balanceLoaded?(balanceMap[person.user_id]??0):null}));
    card.append(D.el("h3",{text:"대상 사용자"}));
    const controls=D.el("div",{class:"admin-target-controls"}),selectAll=D.el("button",{class:"mini-action",type:"button",text:"전체 선택"}),clearAll=D.el("button",{class:"mini-action",type:"button",text:"선택 해제"}),count=D.el("span",{class:"muted admin-selected-count",text:"0명 선택"});controls.append(selectAll,clearAll,count);
    const search=D.el("input",{class:"search",placeholder:"닉네임 검색","aria-label":"대상 사용자 검색"}),targetList=D.el("div",{class:"admin-target-list"});
    const updateCount=()=>{count.textContent=`${selected.size}명 선택`};
    const drawTargets=()=>{const q=String(search.value||"").trim().toLowerCase(),shown=people.filter(person=>person.nickname.toLowerCase().includes(q)),showCoin=type?.value==="COIN_REWARD";targetList.replaceChildren(...shown.map(person=>{const check=D.el("input",{type:"checkbox","data-admin-user":person.user_id,"aria-label":`${person.nickname} 선택`});check.checked=selected.has(person.user_id);check.onchange=()=>{check.checked?selected.add(person.user_id):selected.delete(person.user_id);updateCount()};const avatar=person.avatar?D.el("img",{class:"room-member-avatar profile-image",src:person.avatar,alt:""}):D.el("span",{class:"room-member-avatar",text:(person.nickname||"?").slice(0,1)}),coinText=person.coin==null?"…":String(person.coin),coinLabel=person.coin==null?"현재 코인 확인 중":`현재 보유 ${person.coin}코인`,nameRow=D.el("span",{class:"admin-target-name-row"},[D.el("strong",{text:person.nickname}),showCoin?D.el("span",{class:"admin-target-coin","aria-label":coinLabel},[D.el("img",{src:"assets/ui/notebook-coin.svg",alt:""}),D.el("b",{text:coinText})]):null]);return D.el("label",{class:"room-member admin-target-option"},[avatar,D.el("span",{class:"room-member-copy"},[nameRow,D.el("small",{class:"muted",text:person.user_id})]),check])}));if(!shown.length)targetList.append(D.el("p",{class:"muted modal-note",text:"표시할 사용자가 없습니다."}))};
    selectAll.onclick=()=>{people.forEach(person=>selected.add(person.user_id));drawTargets();updateCount()};clearAll.onclick=()=>{selected.clear();drawTargets();updateCount()};search.oninput=drawTargets;card.append(controls,search,targetList);

    const typeField=D.el("label",{class:"field"},[D.el("span",{text:"명령"})]),type=D.el("select",{id:"adminType"});[["NOTICE","상단 공지"],["STAMP","도장 효과"],["IMAGE","이미지 효과"],["ALARM","알람"],["TASK","과제"],["COIN_REWARD","코인 증감 (+/−)"],["LOCK","프로그램 잠금"],["UNLOCK","잠금 해제"]].forEach(([value,label])=>type.append(D.el("option",{value,text:label})));typeField.append(type);
    const title=D.el("input",{id:"adminTitle",maxlength:"80"}),titleField=D.el("label",{class:"field"},[D.el("span",{text:"제목"}),title]),body=D.el("textarea",{id:"adminBody",maxlength:"1000",rows:"4"}),bodyField=D.el("label",{class:"field"},[D.el("span",{text:"내용"}),body]),coinAmount=D.el("input",{id:"adminCoinAmount",type:"number",min:"-100000",max:"100000",step:"1",inputmode:"numeric",value:"1"}),coinField=D.el("label",{class:"field hidden"},[D.el("span",{text:"1인당 코인 증감 (+/−)"}),coinAmount]),send=D.el("button",{id:"adminSend",class:"button primary",type:"button",text:"선택한 사용자에게 전송"});
    let selectedEffectImage="";const mediaPreview=D.el("img",{class:"admin-effect-preview",src:"assets/ui/quest-stamp.png",alt:"전송 효과 미리보기"}),gallery=D.el("button",{class:"button secondary compact-button",type:"button",text:"이미지 선택"}),camera=D.el("button",{class:"button secondary compact-button",type:"button",text:"카메라 촬영"}),mediaField=D.el("section",{class:"field admin-effect-field hidden"},[D.el("span",{text:"전송할 이미지"}),mediaPreview,D.el("div",{class:"button-row compact-row"},[gallery,camera]),D.el("small",{class:"muted",text:"이미지는 서버에 업로드한 뒤 선택한 사용자 화면 중앙에 표시됩니다."})]);
    const chooseEffectImage=async cameraMode=>{gallery.disabled=camera.disabled=true;try{const payload=await MiniTalk.Chat.Attachments.image({camera:cameraMode});if(!payload)return;if(!payload.imageUrl)throw new Error("이미지 업로드 서버가 URL을 반환하지 않았습니다.");selectedEffectImage=payload.imageUrl;mediaPreview.src=selectedEffectImage;mediaPreview.alt="선택한 이미지 미리보기"}catch(error){Shell.toast(error.message||"이미지를 선택하지 못했습니다.")}finally{gallery.disabled=camera.disabled=false}};gallery.onclick=()=>chooseEffectImage(false);camera.onclick=()=>chooseEffectImage(true);
    const syncFields=()=>{const coin=type.value==="COIN_REWARD",task=type.value==="TASK",lock=type.value==="LOCK",unlock=type.value==="UNLOCK",stamp=type.value==="STAMP",image=type.value==="IMAGE";coinField.classList.toggle("hidden",!coin&&!task);mediaField.classList.toggle("hidden",!stamp&&!image);titleField.classList.toggle("hidden",lock||unlock||stamp||image);bodyField.classList.toggle("hidden",coin||unlock||stamp||image);gallery.classList.toggle("hidden",stamp);camera.classList.toggle("hidden",stamp);if(stamp){mediaPreview.src="assets/ui/quest-stamp.png";mediaPreview.alt="도장 효과 미리보기"}else if(image){mediaPreview.src=selectedEffectImage||"assets/mascot-avatar.png";mediaPreview.alt=selectedEffectImage?"선택한 이미지 미리보기":"이미지를 선택하세요"}coinAmount.min=task?"1":"-100000";if(task&&Number(coinAmount.value)<1)coinAmount.value="1";coinField.querySelector("span").textContent=task?"과제 완료 보상":"1인당 코인 증감 (+/−)";titleField.querySelector("span").textContent=coin?"변경 사유":"제목";bodyField.querySelector("span").textContent=task?"과제 설명 (1,000자 이하)":lock?"잠금 화면에 표시할 내용":"내용";send.textContent=coin?"선택한 사용자 코인 변경":task?"선택한 사용자에게 과제 배정":stamp?"선택한 사용자에게 도장 보내기":image?"선택한 사용자에게 이미지 보내기":lock?"선택한 사용자 잠금":unlock?"선택한 사용자 잠금 해제":"선택한 사용자에게 전송";if(targetList.isConnected)drawTargets();if(coin&&!balanceLoaded&&!balanceInFlight){loadBalances(false).then(()=>{people.forEach(person=>person.coin=balanceMap[person.user_id]??0);if(type.value==="COIN_REWARD"&&targetList.isConnected)drawTargets()}).catch(error=>console.warn("관리자 코인 잔액 조회 실패",error))}};type.onchange=syncFields;
    send.onclick=async()=>{const targets=[...selected];if(!targets.length){Shell.toast("대상 사용자를 선택하세요.");return}if(type.value==="IMAGE"&&!selectedEffectImage){Shell.toast("전송할 이미지를 먼저 선택하세요.");return}send.disabled=true;try{let amount;if(type.value==="COIN_REWARD"||type.value==="TASK"){const coins=Number(coinAmount.value);if(type.value==="TASK"&&(!Number.isInteger(coins)||coins<1||coins>100000))throw new Error("과제 보상은 1~100,000 사이의 정수로 입력하세요.");if(type.value==="COIN_REWARD"&&(!Number.isInteger(coins)||coins===0||Math.abs(coins)>100000))throw new Error("코인 증감은 -100,000~100,000 사이에서 0을 제외한 정수로 입력하세요.");if(type.value==="COIN_REWARD"){const current=MiniTalk.Store.get("user")||{},reason=title.value.trim()||"관리자 코인 변경",signature=JSON.stringify([current.user_id,targets,coins,reason]),requestId=pendingCoinRequests.get(signature)||crypto.randomUUID();pendingCoinRequests.set(signature,requestId);const result=await MiniTalk.AuthApi.adminCoinReward({userId:current.user_id,adminToken:MiniTalk.AdminSession.requireToken("ADMIN"),targets,amount:coins,reason,requestId});pendingCoinRequests.delete(signature);amount=Number(result.count)||0;(result.rewarded||[]).forEach(row=>{balanceMap[row.user_id]=Math.floor(Number(row.newCoin)||0);const person=people.find(item=>item.user_id===row.user_id);if(person)person.coin=balanceMap[row.user_id]});MiniTalk.Realtime.notifyCommandTargets?.(targets);drawTargets()}else{const result=await MiniTalk.Tasks.TaskService.assign(targets,{title:title.value.trim()||"과제",description:body.value.trim(),rewardCoin:coins});amount=Number(result.count)||0}}else{const payload=type.value==="STAMP"?{imageUrl:"assets/ui/quest-stamp.png"}:type.value==="IMAGE"?{imageUrl:selectedEffectImage}:{title:title.value.trim(),body:body.value.trim()};amount=await MiniTalk.Realtime.sendCommands(targets,type.value,payload)}Shell.toast(type.value==="COIN_REWARD"?`${amount}명의 코인을 변경했습니다.`:type.value==="TASK"?`${amount}명에게 과제를 배정했습니다.`:`${amount}명에게 전송했습니다.`)}catch(error){Shell.toast(error.message||"관리자 요청 처리에 실패했습니다.")}finally{send.disabled=false}};
    card.append(typeField,titleField,bodyField,coinField,mediaField,send,D.el("p",{class:"muted modal-note",text:"관리자 명령은 서버에서 권한을 확인하고 Firebase 실시간 신호로 즉시 전달합니다. 코인·과제는 서버에서 중복 지급과 잔액을 다시 확인합니다."}));syncFields();drawTargets();list.append(card,moaLearningPanel(D,Shell),taskReviewPanel(()=>render(host),D,Shell),MiniTalk.Features.Shopping.adminPanel(()=>render(host),{Dom:D,Shell}),MiniTalk.Features.Shopping.deliveryAdminPanel({Dom:D,Shell}));view.append(list);host.replaceChildren(view)
  }

  function moaLearningPanel(D=MiniTalk.UI.Dom,Shell=MiniTalk.UI.Shell){
    const section=D.el("section",{class:"tool-card admin-moa-learning"}),title=D.el("h3",{text:"🧠 모아 대화 학습"}),status=D.el("p",{class:"muted",text:"필요할 때만 학습 버튼을 눌러 상태 확인과 학습을 실행합니다."}),progress=D.el("p",{class:"muted modal-note",text:"관리자 창을 열 때는 모아 학습 서버를 자동 조회하지 않습니다. 기존 과제·상품·배송 관리 요청을 우선하고, 이 버튼을 누를 때만 소통/대화방 시트를 읽습니다."}),learn=D.el("button",{class:"button primary",type:"button",text:"새 대화 학습"}),relearn=D.el("button",{class:"button secondary",type:"button",text:"전체 재학습"}),buttons=D.el("div",{class:"button-row"},[learn,relearn]);
    section.append(title,status,progress,buttons);
    const credentials=()=>{const current=MiniTalk.Store.get("user")||{};return{userId:current.user_id,adminToken:MiniTalk.AdminSession.requireToken("ADMIN")}};
    const refresh=async()=>{try{const c=credentials(),r=await MiniTalk.AuthApi.adminMoaLearningStatus(c.userId,c.adminToken),pending=r.status_bounded?`학습원 ${Number(r.sources)||0}곳 · 새 내용은 학습 실행 때 확인`:`미학습 약 ${Number(r.pending)||0}건 · 학습원 ${Number(r.sources)||0}곳`;status.textContent=`${r.rebuilding?"전체 재학습 진행 중 · ":""}${pending} · 학습 패턴 ${Number(r.learned_patterns)||0}개`;return r}catch(error){status.textContent=error.message||"학습 상태를 확인하지 못했습니다.";return null}};
    const run=async reset=>{learn.disabled=relearn.disabled=true;let totalProcessed=0,totalPairs=0,totalNew=0,totalPrivate=0,totalDeduped=0,totalUrlRemoved=0,round=0,committed=false;try{let more=true,first=true;while(more&&round<120){round++;const c=credentials(),r=await MiniTalk.AuthApi.adminMoaLearnChats({...c,reset:reset&&first,cleanup:first,batchLimit:260});first=false;totalProcessed+=Number(r.processed)||0;totalPairs+=Number(r.pairs)||0;totalNew+=Number(r.new_patterns)||0;totalPrivate+=Number(r.private_skipped)||0;totalDeduped+=Number(r.deduped_patterns)||0;totalUrlRemoved+=Number(r.url_patterns_removed)||0;committed=committed||r.rebuild_committed===true;more=r.has_more===true;progress.textContent=`${r.rebuilding?"재학습 임시본 작성 중":"학습 중"}… ${totalProcessed}건 확인 · 반응쌍 ${totalPairs} · 새 패턴 ${totalNew} · 중복 정리 ${totalDeduped} · 링크 학습 삭제 ${totalUrlRemoved} · 개인정보 제외 ${totalPrivate}`;await new Promise(resolve=>setTimeout(resolve,0));}progress.textContent=`${committed?"전체 재학습 교체 완료":"학습 완료"} · ${totalProcessed}건 확인 · 반응쌍 ${totalPairs} · 새 패턴 ${totalNew} · 중복 정리 ${totalDeduped} · 링크 학습 삭제 ${totalUrlRemoved} · 개인정보 제외 ${totalPrivate}${round>=120?" · 남은 내용은 버튼을 한 번 더 눌러 이어서 학습":""}`;Shell.toast(committed?"모아 전체 재학습을 안전하게 교체했습니다.":"모아 공통 대화 학습을 완료했습니다.");MiniTalk.AI?.MoaCommunicationEngine?.sync?.(true).catch?.(()=>{});await refresh()}catch(error){progress.textContent=error.message||"대화 학습 중 오류가 발생했습니다.";Shell.toast(error.message||"모아 대화 학습에 실패했습니다.")}finally{learn.disabled=relearn.disabled=false}};
    learn.onclick=()=>run(false);relearn.onclick=()=>run(true);return section
  }

  function taskReviewPanel(onChanged,D=MiniTalk.UI.Dom,Shell=MiniTalk.UI.Shell){
    const section=D.el("section",{class:"tool-card admin-task-review"}),head=D.el("div",{class:"admin-review-head"},[D.el("div",{},[D.el("h3",{text:"과제 확인"}),D.el("small",{class:"muted",text:"여러 과제를 선택해 같은 전달내용으로 일괄 확인하거나, 보상 없이 삭제할 수 있습니다."})])]),refresh=D.el("button",{class:"mini-action",type:"button",text:"새로고침"}),body=D.el("div",{class:"admin-review-body"},[D.el("p",{class:"muted",text:"과제 제출 목록을 불러오는 중입니다."})]);head.append(refresh);section.append(head,body);
    let loading=false,reloadQueued=false,mode="submitted",rows=[];const selected=new Set();
    const load=async(manual=true)=>{if(loading){reloadQueued=true;return}loading=true;if(manual)refresh.disabled=true;try{draw(await MiniTalk.Tasks.TaskService.adminList(true))}catch(error){if(manual)body.replaceChildren(D.el("p",{class:"muted",text:error.message||"과제 제출 목록을 불러오지 못했습니다."}))}finally{loading=false;if(manual)refresh.disabled=false;if(reloadQueued){reloadQueued=false;queueMicrotask(()=>load(false))}}};
    const confirmDelete=count=>new Promise(resolve=>{const copy=D.el("div",{class:"modal-copy"},[D.el("p",{text:`선택한 과제 ${count}개를 삭제할까요?`}),D.el("p",{class:"muted",text:"삭제는 코인 보상을 지급하지 않으며 되돌릴 수 없습니다."})]),cancel=D.el("button",{class:"button secondary",type:"button",text:"취소"}),remove=D.el("button",{class:"button danger",type:"button",text:"선택 삭제"}),buttons=D.el("div",{class:"button-row"},[cancel,remove]);copy.append(buttons);let done=false;const finish=value=>{if(done)return;done=true;Shell.closeModal();resolve(value)};cancel.onclick=()=>finish(false);remove.onclick=()=>finish(true);Shell.modal("과제 일괄 삭제",copy)});
    const draw=nextRows=>{rows=nextRows;const validIds=new Set(rows.map(task=>task.id));[...selected].forEach(id=>{if(!validIds.has(id))selected.delete(id)});const counts={submitted:0,retry:0,completed:0};rows.forEach(task=>{if(counts[task.status]!=null)counts[task.status]++});const tabs=D.el("div",{class:"admin-review-tabs"}),bulk=D.el("section",{class:"admin-review-bulk"}),list=D.el("div",{class:"admin-review-list"}),selectedCount=D.el("span",{class:"muted admin-review-selected",text:"0개 선택"}),selectVisible=D.el("button",{class:"mini-action",type:"button",text:"현재 목록 전체 선택"}),clearSelected=D.el("button",{class:"mini-action",type:"button",text:"선택 해제"}),feedback=D.el("textarea",{class:"admin-bulk-feedback",maxlength:"100",rows:"2",placeholder:"일괄 확인 시 함께 전달할 내용 (선택)"}),complete=D.el("button",{class:"button primary compact-button",type:"button",text:"선택 일괄 확인"}),remove=D.el("button",{class:"button secondary compact-button admin-bulk-delete",type:"button",text:"선택 일괄 삭제"});
      const visibleRows=()=>rows.filter(task=>task.status===mode),syncBulk=()=>{selectedCount.textContent=`${selected.size}개 선택`;complete.disabled=!selected.size||mode!=="submitted";remove.disabled=!selected.size;feedback.disabled=mode!=="submitted";feedback.placeholder=mode==="submitted"?"일괄 확인 시 함께 전달할 내용 (선택)":"완료 전달내용은 제출 대기 탭에서 입력할 수 있습니다."};
      const setSelected=(id,checked)=>{checked?selected.add(id):selected.delete(id);syncBulk()};
      const renderRows=()=>{const visible=visibleRows();list.replaceChildren(...visible.map(task=>reviewTaskCard(task,load,D,Shell,{checked:selected.has(task.id),onSelect:checked=>setSelected(task.id,checked)})));if(!visible.length)list.append(D.el("div",{class:"empty-state compact-empty"},[D.el("span",{text:"✓"}),D.el("strong",{text:"표시할 과제가 없습니다."})]));syncBulk()};
      [["submitted","제출 대기"],["retry","다시 요청"],["completed","완료"]].forEach(([value,label])=>{const button=D.el("button",{class:`admin-review-tab ${value===mode?"active":""}`,type:"button",text:`${label} ${counts[value]}`});button.onclick=()=>{mode=value;selected.clear();D.all(".admin-review-tab",tabs).forEach(item=>item.classList.toggle("active",item===button));renderRows()};tabs.append(button)});
      selectVisible.onclick=()=>{visibleRows().forEach(task=>selected.add(task.id));renderRows()};clearSelected.onclick=()=>{selected.clear();renderRows()};
      complete.onclick=async()=>{const ids=[...selected];if(!ids.length||mode!=="submitted")return;complete.disabled=remove.disabled=true;try{const result=await MiniTalk.Tasks.TaskService.bulkReview(ids,"complete",feedback.value.trim());Shell.toast(`${Number(result.count)||0}개 과제를 일괄 확인했습니다.${Number(result.failed)?` · ${Number(result.failed)}개 제외`:""}`);selected.clear();feedback.value="";await load(true)}catch(error){Shell.toast(error.message||"과제 일괄 확인에 실패했습니다.")}finally{syncBulk()}};
      remove.onclick=async()=>{const ids=[...selected];if(!ids.length||!await confirmDelete(ids.length))return;complete.disabled=remove.disabled=true;try{const result=await MiniTalk.Tasks.TaskService.bulkDelete(ids);Shell.toast(`${Number(result.count)||0}개 과제를 보상 없이 삭제했습니다.${Number(result.failed)?` · ${Number(result.failed)}개 제외`:""}`);selected.clear();await load(true)}catch(error){Shell.toast(error.message||"과제 일괄 삭제에 실패했습니다.")}finally{syncBulk()}};
      bulk.append(D.el("div",{class:"admin-review-bulk-select"},[selectVisible,clearSelected,selectedCount]),feedback,D.el("div",{class:"button-row admin-review-bulk-actions"},[complete,remove]));body.replaceChildren(tabs,bulk,list);renderRows()};
    refresh.onclick=()=>load(true);refreshTaskReview=()=>{if(section.isConnected)load(false)};const fallback=setInterval(()=>{if(!section.isConnected){clearInterval(fallback);return}load(false)},30000);load();return section
  }

  function reviewTaskCard(task,reload,D=MiniTalk.UI.Dom,Shell=MiniTalk.UI.Shell,selection={}){const statusLabel={submitted:"제출됨",retry:"다시 요청",completed:"완료"}[task.status]||task.status,check=D.el("input",{class:"admin-task-check",type:"checkbox","aria-label":`${task.nickname||task.userId||"학생"} 과제 선택`});check.checked=selection.checked===true;check.onchange=()=>selection.onSelect?.(check.checked);const who=D.el("label",{class:"admin-review-person"},[check,D.el("strong",{text:task.nickname||task.userId||"학생"})]),card=D.el("article",{class:`admin-review-card status-${task.status}`},[D.el("div",{class:"admin-review-card-top"},[who,D.el("span",{class:`task-status-badge ${task.status}`,text:statusLabel})]),D.el("b",{class:"admin-review-title",text:task.title||"과제"}),D.el("p",{class:"admin-review-preview",text:task.answer||task.description||"아직 제출하지 않았습니다."}),D.el("div",{class:"admin-review-meta"},[D.el("span",{class:"task-reward-pill","aria-label":`완료 보상 ${Number(task.rewardCoin)||0}코인`},[D.el("img",{src:"assets/ui/notebook-coin.svg",alt:""}),D.el("b",{text:`+${Number(task.rewardCoin)||0}`})]),task.imageData?D.el("span",{text:"이미지 1개"}):null])]);if(task.status==="submitted"){const open=D.el("button",{class:"button primary compact-button",type:"button",text:"제출 확인"});open.onclick=()=>MiniTalk.Tasks.TaskWindow.openReview(task,async(action,feedback)=>{await MiniTalk.Tasks.TaskService.review(task.id,action,feedback);Shell.toast(action==="complete"?"과제를 완료 처리하고 보상을 지급했습니다.":"피드백과 함께 다시 보냈습니다.");await reload()},D.doc());card.append(open)}return card}

  function handleCommand(cmd){const p=cmd.payload||{};if(cmd.type==="NOTICE")showNotice(p.title||"안내",p.body||"");if(cmd.type==="STAMP")effectImage(p.imageUrl||"assets/ui/quest-stamp.png",true);if(cmd.type==="IMAGE")effectImage(p.imageUrl||p.body);if(cmd.type==="ALARM"){new Audio("assets/sounds/notify.mp3").play().catch(()=>{});effect(p.title||"알람")};if(cmd.type==="LOCK")lock(p.body||"관리자가 사용을 잠갔습니다.");if(cmd.type==="UNLOCK")unlock()}
  function ensureOverlayHost(){const D=MiniTalk.UI.Dom,doc=D.doc();let host=D.byId("overlayHost");if(host)return host;host=D.el("div",{id:"overlayHost",class:"overlay-host","aria-live":"assertive"});doc.body.append(host);return host}
  function showNotice(title,body){const D=MiniTalk.UI.Dom,doc=D.doc();clearTimeout(noticeTimer);D.byId("adminNoticeLayer")?.remove();const close=D.el("button",{class:"admin-notice-close",type:"button",text:"×","aria-label":"공지 닫기"}),notice=D.el("aside",{id:"adminNotice",class:"admin-notice",role:"status"},[D.el("span",{class:"admin-notice-icon",text:"!"}),D.el("div",{},[D.el("strong",{text:title}),D.el("p",{text:body})]),close]),layer=D.el("div",{id:"adminNoticeLayer",class:"admin-notice-layer"},[notice]),dismiss=()=>{clearTimeout(noticeTimer);noticeTimer=0;layer.classList.add("leaving");setTimeout(()=>layer.remove(),220)};close.onclick=dismiss;doc.body.append(layer);noticeTimer=setTimeout(dismiss,10000)}
  function effect(text){const D=MiniTalk.UI.Dom,host=ensureOverlayHost(),node=D.el("div",{class:"screen-effect",text});host.append(node);new Audio("assets/sounds/stamp.mp3").play().catch(()=>{});setTimeout(()=>node.remove(),2100)}
  function effectImage(url,stamp=false){if(!url)return;const D=MiniTalk.UI.Dom,host=ensureOverlayHost(),img=D.el("img",{class:`screen-effect admin-image-effect${stamp?" stamp-effect":""}`,src:url,alt:stamp?"관리자 도장":"관리자 이미지"});host.append(img);if(stamp)new Audio("assets/sounds/stamp.mp3").play().catch(()=>{});setTimeout(()=>img.remove(),2100)}
  function lock(message){MiniTalk.Persistence.set("runtime.lock",{message:String(message||"관리자가 사용을 잠갔습니다."),at:Date.now()});renderLock()}
  function unlock(){MiniTalk.Persistence.remove("runtime.lock");MiniTalk.UI.Dom.byId("hardLock")?.remove();MiniTalk.UI.Shell.toast("관리자 잠금이 해제되었습니다.")}
  function renderLock(){const saved=MiniTalk.Persistence.get("runtime.lock");if(!saved)return false;const D=MiniTalk.UI.Dom,doc=D.doc();D.byId("hardLock")?.remove();const layer=D.el("section",{id:"hardLock",class:"hard-lock","aria-live":"assertive"},[D.el("div",{class:"hard-lock-card"},[D.el("div",{class:"app-mark",text:"M"}),D.el("h2",{text:"모아루 사용이 잠겼습니다."}),D.el("p",{text:saved.message||"관리자가 사용을 잠갔습니다."}),D.el("small",{class:"muted",text:"관리자가 잠금을 해제하면 다시 사용할 수 있습니다."})])]);doc.body.append(layer);return true}
  return{id:"admin",title:"관리자",icon:"⚙",nav:false,isVisible:visible,render,applyStoredLock:renderLock,reservePopup:reserveDesktopAdminPopup,closePopup:closeAdminPopup}
})();
MiniTalk.Registry.register(MiniTalk.Features.Admin);
