/* ============================================================
   CHAT FEATURE / ORCHESTRATOR
   ------------------------------------------------------------
   이 파일은 채팅 화면의 조립만 담당합니다.
   세부 기능은 js/chat/* 로 분리:
   - emoji.js       토리 이모티콘 12종
   - attachments.js 사진/카메라/파일
   - qr.js          QR 링크 스캔
   - linkify.js     URL/YouTube 미리보기
   - voice.js       보내기 길게 눌러 음성 입력
   - unread.js      방별 미확인 수
   ============================================================ */
MiniTalk.Features.Chats=(()=>{
  const messagesByRoom={},renderedMessageIds={};let roomAlertTimes={};let renderFrame=0;let eventsBound=false;
  function bindEvents(){if(eventsBound)return;eventsBound=true;
    MiniTalk.Events.on("rt:rooms",rooms=>{const active=MiniTalk.Store.get("activeRoom"),memberRooms=Object.fromEntries(Object.entries(rooms||{}).filter(([,room])=>MiniTalk.Realtime.isRoomMember(room)));MiniTalk.Store.set("rooms",rooms);notifyMemberRoomUpdates(memberRooms,active);MiniTalk.Chat.Unread.syncRooms(memberRooms,active);if(MiniTalk.Store.get("route")!=="chats")return;if(active&&(!rooms?.[active]||!canViewRoom(rooms[active]))){MiniTalk.UI.Shell.closeModal();backToList();MiniTalk.UI.Shell.toast(rooms?.[active]?"대화방에서 나왔습니다.":"대화방이 삭제되었습니다.");return}if(!active)renderList()});
    MiniTalk.Events.on("rt:profiles",profiles=>{MiniTalk.Store.set("profiles",profiles||{});if(MiniTalk.Store.get("route")!=="chats")return;const active=MiniTalk.Store.get("activeRoom");if(active){applyChatHeader(MiniTalk.Store.get("rooms")?.[active]?.title||"대화",[MiniTalk.UI.Dom.el("button",{class:"icon-button subtle",type:"button",text:"⋯","aria-label":"대화방 메뉴",onclick:()=>openRoomMenu(active)})],{back:()=>backToList()});scheduleMessageRender(active)}else{applyChatHeader("모아루",headerListActions());renderList()}});
    MiniTalk.Events.on("rt:presence",presence=>MiniTalk.Store.set("presence",presence||{}));
    MiniTalk.Events.on("rt:message-reset",roomId=>{messagesByRoom[roomId]=[];renderedMessageIds[roomId]=new Set()});
    MiniTalk.Events.on("rt:message",message=>{const roomId=message.roomId;if(!roomId)return;const list=messagesByRoom[roomId]||(messagesByRoom[roomId]=[]),isNew=!list.some(item=>item.id===message.id);if(isNew)list.push(message);const active=MiniTalk.Store.get("route")==="chats"&&MiniTalk.Store.get("activeRoom")===roomId,room=MiniTalk.Store.get("rooms")?.[roomId],stillMember=Boolean(room&&MiniTalk.Realtime.isRoomMember(room));if(active)scheduleMessageRender(roomId);if(isNew&&!active&&stillMember&&(message.ts||0)>Date.now()-7000)MiniTalk.Features.Tools?.notifyIncoming?.(message)});
    MiniTalk.Events.on("chat:unread",()=>{if(MiniTalk.Store.get("route")==="chats"&&!MiniTalk.Store.get("activeRoom"))renderList()});
  }
  function scheduleMessageRender(roomId){if(renderFrame)cancelAnimationFrame(renderFrame);renderFrame=requestAnimationFrame(()=>{renderFrame=0;if(MiniTalk.Store.get("activeRoom")===roomId)renderMessages(roomId)})}
  function render(host){MiniTalk.Store.set("activeRoom",null);MiniTalk.Realtime.unsubscribeMessages?.();applyChatHeader("모아루",headerListActions());renderList(host)}
  function headerListActions(){return[
    MiniTalk.UI.Dom.el("button",{class:"icon-button subtle",type:"button",text:"＋","aria-label":"대화방 만들기",onclick:createRoomDialog}),
    MiniTalk.UI.Dom.el("button",{class:"icon-button subtle",type:"button",text:"⌕","aria-label":"검색",onclick:()=>MiniTalk.UI.Dom.one(".search")?.focus()})
  ]}
  function profileHeaderOptions(){const D=MiniTalk.UI.Dom,user=MiniTalk.Store.get("user")||{},profile=MiniTalk.Store.get("profiles")?.[user.user_id]||{},node=D.el("img",{class:"header-profile-avatar",src:profile.avatar||"assets/mascot-avatar.png",alt:user.isGuest?"기본 프로필":"내 프로필",onerror:event=>{event.currentTarget.onerror=null;event.currentTarget.src="assets/mascot-avatar.png"}});return{profile:true,profileEditable:!user.isGuest,profileNode:node,onProfile:user.isGuest?null:()=>MiniTalk.Tools.ProfileEditor.open(()=>{const active=MiniTalk.Store.get("activeRoom");if(active){const room=MiniTalk.Store.get("rooms")?.[active];applyChatHeader(room?.title||"대화",[D.el("button",{class:"icon-button subtle",type:"button",text:"⋯","aria-label":"대화방 메뉴",onclick:()=>openRoomMenu(active)})],{back:()=>backToList()})}else{applyChatHeader("모아루",headerListActions());renderList()}})}}
  function applyChatHeader(title,actions=[],options={}){MiniTalk.UI.Shell.setHeader(title,actions,{...options,...profileHeaderOptions()})}
  function isAdmin(){return MiniTalk.AdminSession?.authorized?.()===true}
  function canViewRoom(room){return isAdmin()||MiniTalk.Realtime.isRoomMember(room)}
  function roomMessageTime(room){return Number(room?.lastMessageAt||room?.last_message_at||(room?.lastMessage?room?.updatedAt:0)||0)}
  /* 방 목록의 최신 메시지 시각을 비교해, 현재 소속된 방의 새 글만 알립니다. 최초 로드와 탈퇴한 방은 제외됩니다. */
  function notifyMemberRoomUpdates(rooms,activeRoom){const now=Date.now(),next={};Object.values(rooms||{}).forEach(room=>{if(!room?.id)return;const ts=roomMessageTime(room),previous=Number(roomAlertTimes[room.id]||0);next[room.id]=ts;if(previous>0&&ts>previous&&room.id!==activeRoom&&ts>now-7000)MiniTalk.Features.Tools?.notifyIncoming?.({roomId:room.id,user_id:room.lastMessageUserId||"",nickname:room.lastMessageNickname||room.title||"모아루",text:room.lastMessage||"새 메시지",ts})});roomAlertTimes=next}
  function profileForMessage(message){const profiles=MiniTalk.Store.get("profiles")||{},stored=profiles[message.user_id]||profiles[message.nickname]||{},avatar=stored.avatar||message.avatar||message.profileImage||message.profile_image||message.profileImageUrl||message.avatarUrl||message.photoURL||message.photoUrl||"";return{...stored,avatar}}
  /* 방 이미지가 없으면 1:1 상대, 방 제목과 같은 사용자, 마지막 발신자 순으로 프로필을 찾습니다. */
  function roomAvatar(room){
    const direct=room?.avatar||room?.profileImage||room?.profile_image||room?.imageUrl||room?.image_url||room?.icon||"";
    if(direct)return direct;
    const profiles=MiniTalk.Store.get("profiles")||{},userId=MiniTalk.Store.get("user")?.user_id||"";
    const memberEntries=Object.entries(room?.members||{}).filter(([id])=>id!==userId);
    const memberIds=memberEntries.map(([id])=>id),memberNames=memberEntries.map(([,member])=>member?.nickname).filter(Boolean);
    const candidates=[room?.otherUserId,room?.target_user_id,room?.lastMessageUserId,room?.lastMessageNickname,...memberIds,...memberNames].filter(Boolean);
    for(const id of candidates){if(profiles[id]?.avatar)return profiles[id].avatar}
    const title=String(room?.title||room?.name||"").trim();
    const matched=Object.values(profiles).find(profile=>String(profile?.nickname||"").trim()===title&&profile?.avatar);
    return matched?.avatar||"assets/mascot-avatar.png";
  }
  function favoriteKey(){return`chat.favorites.${MiniTalk.Store.get("user")?.user_id||"guest"}`}
  function favoriteMap(){return MiniTalk.Persistence.get(favoriteKey(),{})||{}}
  function isFavorite(roomId){return favoriteMap()[roomId]===true}
  function toggleFavorite(roomId){const map=favoriteMap();map[roomId]=!map[roomId];MiniTalk.Persistence.set(favoriteKey(),map);return map[roomId]}
  function createRoomDialog(){const D=MiniTalk.UI.Dom,body=D.el("div",{class:"modal-stack"});body.innerHTML='<label class="field">대화방 이름<input id="newRoomName" maxlength="40" placeholder="예: 우리 반 수다방"></label><label class="field">비밀번호 (선택)<input id="newRoomPassword" type="password" minlength="4" maxlength="32" autocomplete="new-password" placeholder="비워두면 공개방"></label><p class="muted modal-note">비밀번호를 설정하면 처음 입장하는 사람에게만 입력을 요청합니다.</p><button id="newRoomCreate" type="button" class="button primary">만들기</button>';body.querySelector("#newRoomCreate").onclick=async()=>{const b=body.querySelector("#newRoomCreate");b.disabled=true;try{const room=await MiniTalk.Realtime.createRoom(body.querySelector("#newRoomName").value,body.querySelector("#newRoomPassword").value);MiniTalk.UI.Shell.closeModal();MiniTalk.UI.Shell.toast("대화방을 만들었습니다.");setTimeout(()=>openRoom(room.id),30)}catch(e){MiniTalk.UI.Shell.toast(e.message)}finally{b.disabled=false}};MiniTalk.UI.Shell.modal("새 대화방",body);setTimeout(()=>body.querySelector("#newRoomName")?.focus(),30)}
  function renderList(host=MiniTalk.UI.Dom.byId("viewHost")){
    if(!host)return;const D=MiniTalk.UI.Dom,allRooms=Object.values(MiniTalk.Store.get("rooms")||{}).sort((a,b)=>roomMessageTime(b)-roomMessageTime(a)),rooms=allRooms.filter(canViewRoom);
    const view=D.el("section",{class:"view chat-home view-enter","data-filter":"all"});
    const top=D.el("div",{class:"chat-home-top"}),searchWrap=D.el("div",{class:"chat-search-wrap"}),search=D.el("input",{class:"search chat-search",placeholder:"대화방이나 메시지 검색","aria-label":"대화방 검색"});searchWrap.append(D.el("span",{class:"search-glyph",text:"⌕"}),search,D.el("span",{class:"search-hint",text:"검색"}));
    const filters=D.el("div",{class:"chat-filter-tabs","aria-label":"대화 필터"});[["all","전체"],["unread","안읽음"],["favorite","즐겨찾기"],["group","그룹"]].forEach(([mode,label])=>{const button=D.el("button",{class:`chat-filter ${mode==="all"?"active":""}`,type:"button",text:label});button.onclick=()=>{view.dataset.filter=mode;D.all(".chat-filter",filters).forEach(item=>item.classList.toggle("active",item===button));filter(search.value,list,mode,view)};filters.append(button)});
    const sectionHead=D.el("div",{class:"conversation-section-head"},[D.el("strong",{text:"최근 대화"}),D.el("span",{class:"conversation-count",text:`${rooms.length}`})]);top.append(searchWrap,filters,sectionHead);
    const list=D.el("div",{class:"conversation-list",id:"conversationList"});search.oninput=e=>filter(e.target.value,list,view.dataset.filter,view);
    allRooms.forEach((room,i)=>{const node=roomItem(room);node.style.setProperty("--stagger",`${Math.min(i,8)*22}ms`);list.append(node)});
    list.append(D.el("div",{class:"empty-state filter-empty hidden","data-filter-empty":"1"},[D.el("span",{text:"●"}),D.el("strong",{text:allRooms.length?"표시할 대화방이 없습니다":"대화방이 없습니다"}),D.el("small",{class:"muted",text:allRooms.length?"그룹 탭에서 참여할 대화방을 찾아보세요.":"오른쪽 위 ＋ 버튼으로 새 대화를 만들 수 있어요."})]));
    view.append(top,list);host.replaceChildren(view);filter("",list,"all",view)
  }
  function roomItem(room){const D=MiniTalk.UI.Dom,unread=MiniTalk.Chat.Unread.count(room.id),messageAt=roomMessageTime(room),time=messageAt?new Date(messageAt).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}):"",tone=[...(room.id||"")].reduce((sum,char)=>sum+char.charCodeAt(0),0)%4,node=D.el("button",{class:"conversation-item conversation-enter",type:"button","data-room-id":room.id,"data-tone":String(tone),"data-unread":unread?"1":"0","data-favorite":isFavorite(room.id)?"1":"0","data-member":canViewRoom(room)?"1":"0","data-room-type":room.type||"group"},[
    D.el("div",{class:"avatar-wrap"},[D.el("img",{class:"avatar profile-image",src:roomAvatar(room),alt:`${room.title||"대화방"} 이미지`,onerror:event=>{event.currentTarget.onerror=null;event.currentTarget.src="assets/mascot-avatar.png"}}),room.hasPassword?D.el("span",{class:"room-lock-badge",text:"🔒","aria-label":"비밀번호방"}):null]),
    D.el("div",{class:"conversation-main"},[D.el("strong",{class:"conversation-title"},[D.el("span",{text:`${isFavorite(room.id)?"★ ":""}${room.title||room.id}`})]),D.el("p",{text:room.lastMessage||"대화를 시작하세요"})]),
    D.el("div",{class:"conversation-meta"},[D.el("time",{text:time}),unread?D.el("b",{class:"unread",text:String(Math.min(99,unread))}):null])
  ]);let holdTimer=0,holdTriggered=false,startX=0,startY=0;const cancelHold=()=>{clearTimeout(holdTimer);holdTimer=0};node.onpointerdown=event=>{if(event.button!==0)return;holdTriggered=false;startX=event.clientX;startY=event.clientY;holdTimer=setTimeout(()=>{holdTriggered=true;quickRoomActions(room)},620)};node.onpointermove=event=>{if(Math.abs(event.clientX-startX)>10||Math.abs(event.clientY-startY)>10)cancelHold()};node.onpointerup=cancelHold;node.onpointercancel=cancelHold;node.onpointerleave=cancelHold;node.oncontextmenu=event=>{event.preventDefault();cancelHold();quickRoomActions(room)};node.onclick=event=>{if(holdTriggered){event.preventDefault();holdTriggered=false;return}openRoom(room.id)};return node}
  function filter(query,root,mode="all",view=null){const q=query.trim().toLowerCase();let visible=0;MiniTalk.UI.Dom.all(".conversation-item",root).forEach(item=>{const textMatch=item.textContent.toLowerCase().includes(q),member=item.dataset.member==="1",modeMatch=(mode==="all"&&member)||(mode==="unread"&&member&&item.dataset.unread==="1")||(mode==="favorite"&&member&&item.dataset.favorite==="1")||(mode==="group"&&item.dataset.roomType==="group");const show=textMatch&&modeMatch;item.classList.toggle("hidden",!show);if(show)visible++});MiniTalk.UI.Dom.one("[data-filter-empty]",root)?.classList.toggle("hidden",visible>0);const count=MiniTalk.UI.Dom.one(".conversation-count",view||root?.parentElement);if(count)count.textContent=String(visible)}
  async function openRoom(roomId,verifiedRoom=null){let room=verifiedRoom||MiniTalk.Store.get("rooms")?.[roomId]||await MiniTalk.Realtime.getRoom(roomId);if(!room){MiniTalk.UI.Shell.toast("대화방을 찾을 수 없습니다.");return}if(!MiniTalk.Realtime.isRoomMember(room)&&!isAdmin()){if(room.hasPassword){joinRoomDialog(room);return}try{room=await MiniTalk.Realtime.joinRoom(roomId)}catch(e){MiniTalk.UI.Shell.toast(e.message);return}}MiniTalk.Store.set("rooms",{...(MiniTalk.Store.get("rooms")||{}),[roomId]:room});MiniTalk.Store.set("activeRoom",roomId);MiniTalk.Store.set("lastRoom",roomId);MiniTalk.Chat.Unread.clear(roomId,roomMessageTime(room));applyChatHeader(room.title,[MiniTalk.UI.Dom.el("button",{class:"icon-button subtle",type:"button",text:"⋯","aria-label":"대화방 메뉴",onclick:()=>openRoomMenu(roomId)})],{back:()=>backToList()});await MiniTalk.Realtime.subscribeMessages(roomId);if(MiniTalk.Store.get("route")==="chats"&&MiniTalk.Store.get("activeRoom")===roomId)renderMessages(roomId)}
  function quickRoomActions(room){const D=MiniTalk.UI.Dom,body=D.el("div",{class:"modal-stack"}),favorite=D.el("button",{class:"button secondary",type:"button",text:isFavorite(room.id)?"즐겨찾기 해제":"즐겨찾기"});favorite.onclick=()=>{const active=toggleFavorite(room.id);MiniTalk.UI.Shell.closeModal();renderList();MiniTalk.UI.Shell.toast(active?"즐겨찾기에 추가했습니다.":"즐겨찾기에서 해제했습니다.")};body.append(favorite);if(room.id!=="global"&&MiniTalk.Realtime.isRoomMember(room)){const leave=D.el("button",{class:"button room-leave-button",type:"button",text:"대화방 나가기"});leave.onclick=()=>confirmLeaveRoom(room);body.append(leave)}else if(!MiniTalk.Realtime.isRoomMember(room)){const enter=D.el("button",{class:"button primary",type:"button",text:room.hasPassword?"비밀번호 입력 후 참여":"대화방 참여"});enter.onclick=()=>{MiniTalk.UI.Shell.closeModal();openRoom(room.id)};body.append(enter)}MiniTalk.UI.Shell.modal(room.title||"대화방",body)}
  function joinRoomDialog(room){const D=MiniTalk.UI.Dom,body=D.el("div",{class:"modal-stack"});body.innerHTML='<p class="modal-note">이 대화방은 비밀번호로 보호되어 있습니다.</p><label class="field">대화방 비밀번호<input id="roomJoinPassword" type="password" maxlength="32" autocomplete="current-password"></label><button id="roomJoinAction" type="button" class="button primary">입장하기</button>';const action=body.querySelector("#roomJoinAction"),input=body.querySelector("#roomJoinPassword");action.onclick=async()=>{action.disabled=true;try{const joined=await MiniTalk.Realtime.joinRoom(room.id,input.value);MiniTalk.Store.set("rooms",{...(MiniTalk.Store.get("rooms")||{}),[room.id]:joined});MiniTalk.UI.Shell.closeModal();setTimeout(()=>openRoom(room.id,joined),30)}catch(e){MiniTalk.UI.Shell.toast(e.message);input.select()}finally{action.disabled=false}};input.onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();action.click()}};MiniTalk.UI.Shell.modal(room.title,body);setTimeout(()=>input.focus(),30)}
  function roomMemberList(room){if(room.id==="global")return Object.values(MiniTalk.Store.get("presence")||{}).filter(Boolean);return Object.values(room.members||{}).filter(Boolean)}
  async function openRoomMenu(roomId){const room=await MiniTalk.Realtime.getRoom(roomId);if(!room){MiniTalk.UI.Shell.closeModal();backToList();return}const D=MiniTalk.UI.Dom,user=MiniTalk.Store.get("user"),owner=room.creator===user?.user_id,members=roomMemberList(room),body=D.el("div",{class:"room-menu modal-stack"});
    const summary=D.el("section",{class:"room-summary"},[D.el("div",{class:"room-summary-icon",text:room.hasPassword?"🔒":"●"}),D.el("div",{},[D.el("strong",{text:room.title||room.id}),D.el("small",{class:"muted",text:room.id==="global"?"모든 사용자가 참여하는 기본 대화방":`${members.length}명 · ${room.hasPassword?"비밀번호방":"공개방"}`})])]);body.append(summary);
    const memberBox=D.el("section",{class:"room-section"},[D.el("strong",{class:"room-section-title",text:room.id==="global"?"현재 접속자":"멤버"})]),list=D.el("div",{class:"room-member-list"});
    if(!members.length)list.append(D.el("p",{class:"muted modal-note",text:"표시할 멤버가 없습니다."}));
    members.sort((a,b)=>(a.joinedAt||0)-(b.joinedAt||0)).forEach(member=>{const id=member.user_id||"",isOwner=id===room.creator,row=D.el("div",{class:"room-member"},[D.el("span",{class:"room-member-avatar",text:(member.nickname||id||"?").slice(0,1)}),D.el("span",{class:"room-member-copy"},[D.el("strong",{text:member.nickname||id||"익명"}),D.el("small",{class:"muted",text:isOwner?"방장":member.online?"접속 중":"멤버"})])]);if(owner&&room.id!=="global"&&id&&id!==user.user_id){const kick=D.el("button",{class:"mini-action danger-lite",type:"button",text:"내보내기"});kick.onclick=()=>confirmRemoveMember(room,id,member.nickname||id);row.append(kick)}list.append(row)});memberBox.append(list);body.append(memberBox);
    if(room.id!=="global"&&(MiniTalk.Realtime.isRoomMember(room)||isAdmin())){const invite=D.el("button",{class:"button secondary compact-button",type:"button",text:"친구 초대"});invite.onclick=()=>inviteRoomDialog(room);body.append(invite)}
    if(owner&&room.id!=="global"){const security=D.el("section",{class:"room-section"});security.innerHTML=`<strong class="room-section-title">비밀번호</strong><label class="field"><input id="roomPasswordEdit" type="password" minlength="4" maxlength="32" autocomplete="new-password" placeholder="${room.hasPassword?"새 비밀번호 또는 빈칸":"4자 이상 입력"}"></label><p class="muted modal-note">${room.hasPassword?"빈칸으로 저장하면 비밀번호가 해제됩니다.":"설정하면 새 멤버가 입장할 때 입력해야 합니다."}</p>`;const save=D.el("button",{class:"button secondary compact-button",type:"button",text:room.hasPassword?"변경 또는 해제":"비밀번호 설정"});save.onclick=async()=>{save.disabled=true;try{await MiniTalk.Realtime.updateRoomPassword(roomId,security.querySelector("#roomPasswordEdit").value);MiniTalk.UI.Shell.toast("비밀번호 설정을 저장했습니다.");await openRoomMenu(roomId)}catch(e){MiniTalk.UI.Shell.toast(e.message)}finally{save.disabled=false}};security.append(save);body.append(security)}
    if(room.id!=="global"){const leaveButton=D.el("button",{class:"button room-leave-button",type:"button",text:"대화방 나가기"});leaveButton.onclick=()=>confirmLeaveRoom(room);body.append(leaveButton)}else body.append(D.el("p",{class:"muted modal-note",text:"전체 대화는 기본 대화방이므로 나가거나 비밀번호를 설정할 수 없습니다."}));
    MiniTalk.UI.Shell.modal("대화방 정보",body)
  }
  function inviteRoomDialog(room){
    const D=MiniTalk.UI.Dom,user=MiniTalk.Store.get("user")||{},members=room.members||{},people=new Map();
    const add=value=>{if(!value||typeof value!=="object")return;const id=String(value.user_id||value.userId||value.uid||"").trim(),nickname=String(value.nickname||value.name||value.username||id).trim();if(!id||id===user.user_id||members[id]||/^(guest-|게스트)/i.test(id))return;people.set(id,{user_id:id,nickname,avatar:value.avatar||""})};
    MiniTalk.UserDirectory?.all?.().forEach(add);Object.values(MiniTalk.Store.get("profiles")||{}).forEach(add);Object.values(MiniTalk.Store.get("presence")||{}).forEach(add);
    const body=D.el("div",{class:"modal-stack"}),search=D.el("input",{class:"search",placeholder:"이름 검색","aria-label":"초대할 사용자 검색"}),list=D.el("div",{class:"room-member-list invite-member-list"}),selected=new Set(),candidates=[...people.values()].sort((a,b)=>a.nickname.localeCompare(b.nickname,"ko"));
    const renderCandidates=query=>{const q=String(query||"").trim().toLowerCase(),visible=candidates.filter(person=>person.nickname.toLowerCase().includes(q));list.replaceChildren(...visible.map(person=>{const check=D.el("input",{type:"checkbox","aria-label":`${person.nickname} 선택`});check.checked=selected.has(person.user_id);check.onchange=()=>check.checked?selected.add(person.user_id):selected.delete(person.user_id);const avatar=person.avatar?D.el("img",{class:"room-member-avatar profile-image",src:person.avatar,alt:""}):D.el("span",{class:"room-member-avatar",text:(person.nickname||"?").slice(0,1)});return D.el("label",{class:"room-member invite-member-option"},[avatar,D.el("span",{class:"room-member-copy"},[D.el("strong",{text:person.nickname})]),check])}));if(!visible.length)list.append(D.el("p",{class:"muted modal-note",text:"초대할 수 있는 사용자가 없습니다."}))};
    search.oninput=()=>renderCandidates(search.value);const action=D.el("button",{class:"button primary",type:"button",text:"선택한 사용자 초대"});action.onclick=async()=>{const targets=candidates.filter(person=>selected.has(person.user_id));action.disabled=true;try{const count=await MiniTalk.Realtime.inviteRoomMembers(room.id,targets);MiniTalk.UI.Shell.toast(`${count}명을 초대했습니다.`);await openRoomMenu(room.id)}catch(error){MiniTalk.UI.Shell.toast(error.message);action.disabled=false}};body.append(search,list,action);renderCandidates("");MiniTalk.UI.Shell.modal("대화방 초대",body);setTimeout(()=>search.focus(),30)
  }
  function confirmRemoveMember(room,memberId,name){const D=MiniTalk.UI.Dom,body=D.el("div",{class:"modal-stack"},[D.el("p",{text:`${name}님을 대화방에서 내보낼까요?`}),D.el("p",{class:"muted modal-note",text:"비밀번호방이라면 다시 입장하려면 비밀번호가 필요합니다."})]),row=D.el("div",{class:"button-row"}),cancel=D.el("button",{class:"button secondary",type:"button",text:"취소"}),remove=D.el("button",{class:"button room-leave-button",type:"button",text:"내보내기"});cancel.onclick=()=>openRoomMenu(room.id);remove.onclick=async()=>{remove.disabled=true;try{await MiniTalk.Realtime.removeRoomMember(room.id,memberId);MiniTalk.UI.Shell.toast("멤버를 내보냈습니다.");await openRoomMenu(room.id)}catch(e){MiniTalk.UI.Shell.toast(e.message);remove.disabled=false}};row.append(cancel,remove);body.append(row);MiniTalk.UI.Shell.modal("멤버 내보내기",body)}
  function confirmLeaveRoom(room){const D=MiniTalk.UI.Dom,isOwner=room.creator===MiniTalk.Store.get("user")?.user_id,count=Object.keys(room.members||{}).length,body=D.el("div",{class:"modal-stack"},[D.el("p",{text:`${room.title}에서 나갈까요?`}),D.el("p",{class:"muted modal-note",text:isOwner?(count>1?"가장 먼저 참여한 멤버에게 방장이 자동으로 넘어갑니다.":"남은 멤버가 없어 대화방과 메시지가 삭제됩니다."):"다시 참여하려면 대화방에 재입장해야 합니다."})]),row=D.el("div",{class:"button-row"}),cancel=D.el("button",{class:"button secondary",type:"button",text:"취소"}),leaveButton=D.el("button",{class:"button room-leave-button",type:"button",text:"나가기"});cancel.onclick=()=>openRoomMenu(room.id);leaveButton.onclick=async()=>{leaveButton.disabled=true;MiniTalk.Store.set("activeRoom",null);try{const result=await MiniTalk.Realtime.leaveRoom(room.id);MiniTalk.UI.Shell.closeModal();MiniTalk.Realtime.unsubscribeMessages?.();backToList();MiniTalk.UI.Shell.toast(result.deleted?"대화방을 삭제했습니다.":"대화방에서 나왔습니다.")}catch(e){MiniTalk.Store.set("activeRoom",room.id);MiniTalk.UI.Shell.toast(e.message);leaveButton.disabled=false}};row.append(cancel,leaveButton);body.append(row);MiniTalk.UI.Shell.modal("대화방 나가기",body)}
  function backToList(){MiniTalk.Store.set("activeRoom",null);MiniTalk.Realtime.unsubscribeMessages?.();applyChatHeader("모아루",headerListActions(),{back:null});renderList()}
  function renderMessages(roomId){
    const D=MiniTalk.UI.Dom,host=D.byId("viewHost");if(!host)return;MiniTalk.Features.Settings?.applyChatBackground?.();
    const existing=D.one(".chat-room",host),sameRoom=existing?.getAttribute?.("data-room-id")===String(roomId),existingList=sameRoom?existing.querySelector?.("#messageList"):null;
    if(existingList){refreshMessageList(roomId,existingList);return}
    const view=D.el("section",{class:"view chat-room view-enter","data-room-id":roomId}),list=D.el("div",{class:"message-list",id:"messageList"});
    fillMessageList(roomId,list,true);
    const composer=buildComposer(roomId);view.append(list,composer.root);host.replaceChildren(view);requestAnimationFrame(()=>{list.scrollTop=list.scrollHeight})
  }
  function refreshMessageList(roomId,list){
    const distance=Math.max(0,list.scrollHeight-list.scrollTop-list.clientHeight),stickToBottom=distance<72,previousTop=list.scrollTop;
    fillMessageList(roomId,list,false);
    requestAnimationFrame(()=>{list.scrollTop=stickToBottom?list.scrollHeight:Math.min(previousTop,Math.max(0,list.scrollHeight-list.clientHeight))})
  }
  function fillMessageList(roomId,list,initial){
    const sorted=[...(messagesByRoom[roomId]||[])].sort((a,b)=>(a.ts||0)-(b.ts||0)),seen=renderedMessageIds[roomId]||(renderedMessageIds[roomId]=new Set());
    const nodes=sorted.map((message,i)=>{const n=messageNode(message),key=String(message.id||`${message.user_id||""}:${message.ts||0}:${i}`),fresh=!seen.has(key);if(fresh&&(initial?i>=Math.max(0,sorted.length-4):true))n.classList.add("message-enter");seen.add(key);return n});
    list.replaceChildren(...nodes)
  }
  function buildComposer(roomId){
    const D=MiniTalk.UI.Dom;let menuOpen=false,emojiOpen=false;
    const root=D.el("section",{class:"composer-zone"});
    const voiceStatus=D.el("div",{class:"voice-status","aria-live":"polite"});
    const tray=D.el("div",{class:"attach-tray hidden"});
    const emojiPanel=D.el("div",{class:"emoji-panel hidden"});
    MiniTalk.Chat.Emoji.list().forEach(info=>{const b=D.el("button",{type:"button",class:"emoji-item","aria-label":info.fallback||info.code});b.append(D.el("img",{src:info.src,alt:info.fallback||info.code,loading:"lazy"}));b.onclick=async()=>{await sendPayload(roomId,{text:info.fallback||info.token,type:"text",emoticon:info.fallback?info.code:null});emojiPanel.classList.add("hidden");emojiOpen=false};emojiPanel.append(b)});
    const form=D.el("form",{class:"composer"}),plus=D.el("button",{class:"composer-icon",type:"button",text:"＋","aria-label":"첨부 메뉴"}),input=D.el("input",{id:"msgInput",placeholder:"메시지 입력",maxlength:"500","aria-label":"메시지 입력",autocomplete:"off"}),emoji=D.el("button",{class:"composer-icon emoji-toggle",type:"button",text:"☺","aria-label":"이모티콘"}),send=D.el("button",{id:"msgSendBtn",class:"send",type:"submit",text:"➤","aria-label":"전송 - 길게 누르면 음성 입력"});
    const addAction=(icon,label,fn)=>{const b=D.el("button",{type:"button",class:"attach-action"},[D.el("span",{text:icon}),D.el("small",{text:label})]);b.onclick=async()=>{tray.classList.add("hidden");menuOpen=false;try{await fn()}catch(e){if(e?.message&&!/취소/.test(e.message))MiniTalk.UI.Shell.toast(e.message)}};tray.append(b)};
    addAction("▧","사진",async()=>{const payload=await MiniTalk.Chat.Attachments.image({camera:false});if(payload)await sendPayload(roomId,payload)});
    addAction("◉","카메라",async()=>{const payload=await MiniTalk.Chat.Attachments.image({camera:true});if(payload)await sendPayload(roomId,payload)});
    addAction("⌁","파일",async()=>{const payload=await MiniTalk.Chat.Attachments.file();if(payload)await sendPayload(roomId,payload)});
    addAction("▦","QR",async()=>{const text=await MiniTalk.Chat.QR.scan();if(text){input.value=text;input.focus()}});
    plus.onclick=()=>{menuOpen=!menuOpen;tray.classList.toggle("hidden",!menuOpen);emojiPanel.classList.add("hidden");emojiOpen=false;plus.classList.toggle("active",menuOpen)};
    emoji.onclick=()=>{emojiOpen=!emojiOpen;emojiPanel.classList.toggle("hidden",!emojiOpen);tray.classList.add("hidden");menuOpen=false;plus.classList.remove("active")};
    const submitText=async text=>{const clean=String(text||"").trim();if(!clean)return;await sendPayload(roomId,{text:clean,type:"text"})};
    form.onsubmit=async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;send.disabled=true;try{await submitText(text);input.value=""}catch(error){MiniTalk.UI.Shell.toast(error.message)}finally{send.disabled=false;input.focus()}};
    MiniTalk.Chat.Voice.bind(send,input,async text=>{try{await submitText(text)}catch(e){MiniTalk.UI.Shell.toast(e.message);throw e}},voiceStatus);
    form.append(plus,input,emoji,send);root.append(voiceStatus,tray,emojiPanel,form);return{root,input}
  }
  async function sendPayload(roomId,payload){await MiniTalk.Realtime.sendMessage(roomId,payload)}
  function messageNode(message){
    const D=MiniTalk.UI.Dom,mine=message.user_id===MiniTalk.Store.get("user")?.user_id,row=D.el("article",{class:`message-row ${mine?"mine":""}`}),profile=profileForMessage(message);
    if(!mine){const avatar=D.el("img",{class:"message-avatar profile-image",src:profile.avatar||"assets/mascot-avatar.png",alt:`${message.nickname||"사용자"} 프로필`});avatar.onerror=()=>{avatar.onerror=null;avatar.src="assets/mascot-avatar.png"};avatar.onclick=()=>openUserProfile(message,profile);row.append(avatar)}
    const content=D.el("div",{class:"message-content"});if(!mine)content.append(D.el("small",{class:"sender-name",text:message.nickname||"익명"}));
    const bubble=D.el("div",{class:"bubble"});const type=message.type||(message.fileUrl?"file":(message.image||message.imageUrl?"image":"text"));
    if(type==="image"){
      const src=message.imageUrl||message.image;if(src){bubble.classList.add("media-bubble");const img=D.el("img",{src,alt:"공유 이미지",loading:"lazy"});img.onclick=()=>openImage(src);bubble.append(img)}
    }else if(type==="file"){
      bubble.classList.add("file-bubble");const a=D.el("a",{href:message.fileUrl||"#",target:"_blank",rel:"noopener noreferrer",class:"file-card"},[D.el("span",{text:"⌁"}),D.el("span",{},[D.el("strong",{text:message.fileName||"첨부 파일"}),D.el("small",{text:"파일 열기"})])]);bubble.append(a)
    }else{
      if(MiniTalk.Chat.Emoji.isOnlyCustom(message.text,message.emoticon)||MiniTalk.Chat.Emoji.isOnlyUnicode(message.text))bubble.classList.add("emoji-only");MiniTalk.Chat.Emoji.appendText(message.text||"",bubble,message.emoticon);MiniTalk.Chat.Linkify.enhance(bubble);const preview=MiniTalk.Chat.Linkify.preview(message.text||"",D.doc());if(preview&&!message.emoticon)bubble.append(preview)
    }
    const meta=D.el("time",{class:"message-time",text:message.ts?new Date(message.ts).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}):""});content.append(D.el("div",{class:"bubble-line"},mine?[meta,bubble]:[bubble,meta]));row.append(content);return row
  }
  function openImage(src){const D=MiniTalk.UI.Dom,wrap=D.el("div",{class:"image-viewer"}),img=D.el("img",{src,alt:"이미지 크게 보기"});wrap.append(img);wrap.onclick=()=>wrap.remove();D.doc().body.append(wrap)}
  function openUserProfile(message,profile){const D=MiniTalk.UI.Dom,body=D.el("div",{class:"profile-viewer"}),avatar=D.el("img",{class:"profile-viewer-avatar",src:profile?.avatar||"assets/mascot-avatar.png",alt:"프로필"});avatar.onerror=()=>{avatar.onerror=null;avatar.src="assets/mascot-avatar.png"};body.append(avatar,D.el("strong",{class:"profile-viewer-name",text:message.nickname||"익명"}),D.el("p",{class:"muted profile-viewer-status",text:profile?.statusMsg||"상태메시지가 없습니다."}));MiniTalk.UI.Shell.modal("프로필",body)}
  function leave(){MiniTalk.Store.set("activeRoom",null);MiniTalk.Realtime.unsubscribeMessages?.();MiniTalk.Chat.QR.stop?.();if(renderFrame){cancelAnimationFrame(renderFrame);renderFrame=0}}
  bindEvents();return{id:"chats",title:"대화",icon:"◉",render,leave};
})();
MiniTalk.Registry.register(MiniTalk.Features.Chats);
