const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),server=fs.readFileSync(path.join(root,'docs/apps-script/coin-shopping-extension.gs'),'utf8'),code=fs.readFileSync(path.join(root,'docs/apps-script/Code.gs'),'utf8'),auth=fs.readFileSync(path.join(root,'js/adapters/auth-api.js'),'utf8'),service=fs.readFileSync(path.join(root,'js/tasks/task-service.js'),'utf8'),admin=fs.readFileSync(path.join(root,'js/features/admin.js'),'utf8');
class Range{constructor(sheet,row,col,rows,cols){Object.assign(this,{sheet,row,col,rows,cols})}getValues(){return Array.from({length:this.rows},(_,r)=>Array.from({length:this.cols},(_,c)=>this.sheet.rows[this.row-1+r]?.[this.col-1+c]??''))}setValues(values){values.forEach((line,r)=>line.forEach((value,c)=>{const rr=this.row-1+r;while(this.sheet.rows.length<=rr)this.sheet.rows.push([]);this.sheet.rows[rr][this.col-1+c]=value}));return this}}
class Sheet{constructor(name,rows=[]){this.name=name;this.rows=rows.map(row=>[...row])}getLastRow(){return this.rows.length}getRange(row,col,rows=1,cols=1){return new Range(this,row,col,rows,cols)}setFrozenRows(){}deleteRow(row){this.rows.splice(row-1,1)}appendRow(row){this.rows.push([...row]);return this}}
const login=new Sheet('로그인',[['user_id','username','password','nickname'],['admin-user','admin','','관리자'],['u1','one','','하나'],['u2','two','','둘']]),rewards=new Sheet('보상',[['user_id','username','coin','url'],['admin-user','admin',0,''],['u1','one',0,''],['u2','two',0,'']]),sheets=new Map([['로그인',login],['보상',rewards]]),workbook={getSheetByName:name=>sheets.get(name)||null,insertSheet:name=>{const sheet=new Sheet(name);sheets.set(name,sheet);return sheet}};
const propertyMap=new Map(),taskPropertyMap=new Map();
// restore methods explicitly to avoid accidental helper typo
function makeStore(map){return{getProperty:key=>map.get(key)||null,setProperty:(key,value)=>map.set(key,String(value)),setProperties:values=>Object.entries(values).forEach(([key,value])=>map.set(key,String(value))),deleteProperty:key=>map.delete(key),getProperties:()=>Object.fromEntries(map)}}
const rewardCalls=[];let uuid=0;
const ctx={console,SHEET_ID:'sheet',LOGIN_SHEET:'로그인',REWARD_SHEET:'보상',COL_REWARD_USER_ID:1,COL_REWARD_COIN:3,SpreadsheetApp:{openById:()=>workbook,getActive:()=>workbook},ContentService:{MimeType:{JSON:'json'},createTextOutput:value=>({value,setMimeType(){return this}})},CacheService:{getScriptCache:()=>({get:key=>key==='shop-admin:token'?'admin-user':null,put(){},remove(){}})},PropertiesService:{getScriptProperties:()=>makeStore(propertyMap),getDocumentProperties:()=>makeStore(taskPropertyMap)},Utilities:{getUuid:()=>`uuid-${++uuid}`},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},ScriptApp:{getProjectTriggers:()=>[],newTrigger:()=>({timeBased(){return this},everyDays(){return this},atHour(){return this},create(){}}),deleteTrigger(){}},getSheet_:name=>sheets.get(name),getRewardUserData_:id=>['admin-user','u1','u2'].includes(id)?{coin:0}:null,processCoinChangeUnlocked_:(id,action,amount)=>{rewardCalls.push({id,action,amount});return{success:true,newCoin:100+amount}}};
vm.createContext(ctx);vm.runInContext(server,ctx,{filename:'coin-shopping-extension.gs'});
const parse=result=>JSON.parse(result.value),call=(name,parameter)=>parse(ctx[name]({parameter}));
function assignAndSubmit(title){const assigned=call('handleAdminTaskAssign',{user_id:'admin-user',admin_token:'token',targets_json:'["u1","u2"]',title,description:'설명',reward_coin:'10',request_id:`req-${title}`});if(!assigned.ok||assigned.count!==2)throw new Error('bulk test assignment failed');assigned.task_ids.forEach((id,index)=>{const user=index===0?'u1':'u2';const submitted=call('handleUserTaskSubmit',{user_id:user,task_id:id,answer:`${title}-${user}`});if(!submitted.ok)throw new Error('bulk test submission failed')});return assigned.task_ids}
const reviewIds=assignAndSubmit('일괄확인');
const denied=call('handleAdminTaskBulkReview',{user_id:'admin-user',admin_token:'bad',task_ids_json:JSON.stringify(reviewIds),action:'complete',feedback:'같은 전달내용'});if(denied.error!=='ADMIN_SESSION_EXPIRED'||rewardCalls.length)throw new Error('bulk review skipped admin token validation');
const reviewed=call('handleAdminTaskBulkReview',{user_id:'admin-user',admin_token:'token',task_ids_json:JSON.stringify(reviewIds),action:'complete',feedback:'같은 전달내용'});if(!reviewed.ok||reviewed.count!==2||reviewed.failed!==0||rewardCalls.length!==2)throw new Error('bulk review did not complete and reward both selected tasks');
if(reviewed.results.some(row=>!row.ok||row.task.status!=='completed'||row.task.feedback!=='같은 전달내용'))throw new Error('bulk review did not apply identical feedback');
const reviewedAgain=call('handleAdminTaskBulkReview',{user_id:'admin-user',admin_token:'token',task_ids_json:JSON.stringify(reviewIds),action:'complete',feedback:'같은 전달내용'});if(!reviewedAgain.ok||rewardCalls.length!==2)throw new Error('bulk review retried rewards twice');
const deleteAssigned=call('handleAdminTaskAssign',{user_id:'admin-user',admin_token:'token',targets_json:'["u1","u2"]',title:'삭제대상',description:'삭제',reward_coin:'50',request_id:'delete-req'});const beforeDeleteRewards=rewardCalls.length;
const deleted=call('handleAdminTaskBulkDelete',{user_id:'admin-user',admin_token:'token',task_ids_json:JSON.stringify(deleteAssigned.task_ids)});if(!deleted.ok||deleted.count!==2||deleted.failed!==0)throw new Error('bulk delete did not remove selected tasks');if(rewardCalls.length!==beforeDeleteRewards)throw new Error('bulk delete changed coin rewards');
const remaining=call('handleAdminTaskList',{user_id:'admin-user',admin_token:'token'}).tasks;if(remaining.some(task=>deleteAssigned.task_ids.includes(task.id)))throw new Error('bulk-deleted task remained in server list');
const commandsU1=parse(ctx.handleUserCommands({parameter:{user_id:'u1',ack_ids:''}})).commands,commandsU2=parse(ctx.handleUserCommands({parameter:{user_id:'u2',ack_ids:''}})).commands;if(!commandsU1.some(c=>c.type==='TASK_DELETED')||!commandsU2.some(c=>c.type==='TASK_DELETED'))throw new Error('bulk delete did not notify student task refresh');
const backup=sheets.get('모아루_과제백업');if(!backup||backup.rows.filter(row=>row[0]==='DELETED').length<2)throw new Error('bulk delete was not backed up');
for(const needle of ['mode: "admin_task_bulk_review"','mode: "admin_task_bulk_delete"'])if(!auth.includes(needle))throw new Error(`AuthApi missing ${needle}`);
for(const needle of ['bulkReview','bulkDelete','TASK_(?:ASSIGNED|SUBMITTED|RETRY|COMPLETED|DELETED)'])if(!service.includes(needle))throw new Error(`TaskService missing ${needle}`);
for(const needle of ['선택 일괄 확인','선택 일괄 삭제','일괄 확인 시 함께 전달할 내용','TaskService.bulkReview','TaskService.bulkDelete'])if(!admin.includes(needle))throw new Error(`admin UI missing ${needle}`);
for(const needle of ['case "admin_task_bulk_review"','case "admin_task_bulk_delete"'])if(!code.includes(needle))throw new Error(`Code.gs missing ${needle}`);
if(!server.includes('function reviewMoaruTaskUnlocked_')||!server.includes('function handleAdminTaskBulkReview')||!server.includes('function handleAdminTaskBulkDelete'))throw new Error('bulk server handlers are incomplete');
console.log('ADMIN_TASK_BULK_REVIEW_DELETE_OK');
