const fs=require('fs');
const admin=fs.readFileSync('js/features/admin.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('css/features/tasks-assignment.css','utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(admin.includes('text:"명령"') && admin.includes('openCommand(group.name,targets)'),'group command button/modal bridge missing');
ok(admin.includes('Shell.modal(`${groupName} 명령`,wrap,{modalClass:"admin-group-command-dialog"})'),'group-only command modal missing');
ok(admin.includes('이 명령은 이 그룹 구성원에게만 적용됩니다.'),'group scope explanation missing');
ok(admin.includes('executeAdminCommand({targets,type:gType.value'),'group command must execute against fixed group targets');
ok(!admin.includes('selected.clear();targets.forEach(id=>selected.add(String(id)))'),'legacy group-to-main-target bridge remains');
ok(!admin.includes('focusCommand:focusGroupCommand'),'legacy group focus bridge remains');
ok(admin.includes('text:"선택"') && admin.includes('choose.onclick=()=>chooseMembers(group)'),'group member select flow missing');
ok(css.includes('.admin-group-command-modal') && css.includes('.admin-group-command:disabled'),'group command modal/layout missing');
ok(/css\/features\/tasks-assignment\.css\?v=[^"']+/.test(html),'tasks css cache ref missing');
ok(/js\/features\/admin\.js\?v=[^"']+/.test(html),'admin js cache ref missing');
console.log('ADMIN_GROUP_COMMAND_INTEGRATION_OK');
