const fs=require('fs');
const source=fs.readFileSync('js/features/auth.js','utf8');
const css=fs.readFileSync('css/app.css','utf8');
const html=fs.readFileSync('index.html','utf8');
function ok(value,message){if(!value)throw new Error(message)}
ok(source.includes('id===String(rememberedUser.username||"")&&!password'),'saved session reuse is missing');
ok(source.includes('placeholder="${hasSession?"••••••••":"비밀번호"}"'),'remembered password mask is missing');
ok(source.includes('MiniTalk.Persistence.set(LAST_ID_KEY,user.username)'),'last username is not remembered');
ok(!/Persistence\.set\([^\n]*(?:password|authPw)/.test(source),'plaintext password must not be persisted');
ok(source.includes('MiniTalk.WindowMode.openForLogin()'),'login click must request always-on-top mode');
ok(source.includes('id="authInstallAction"'),'login screen install button is missing');
ok(source.includes('MiniTalk.WindowMode.canInstall?.()'),'native PWA install path is missing');
ok(source.includes('showInstallGuide()'),'manual install guide fallback is missing');
ok(css.includes('.auth-host{min-height:0;overflow:auto;display:grid;align-content:center'),'login screen must be centered in the available window');
ok(css.includes('body{min-height:100dvh}'),'desktop app shell must fill the viewport for vertical centering');
ok(css.includes('.auth-host{align-content:safe center}'),'login card safe vertical centering is missing');
ok(css.includes('.auth-brand .app-mark{width:42px;height:42px;margin:0'),'login brand icon alignment is missing');
ok(html.includes('rel="icon" type="image/png" href="assets/mascot-avatar.png?v=64.5.1"'),'browser tab must keep the Moaru mascot favicon');
ok(source.includes('app-mark app-mark-mascot')&&source.includes('assets/mascot-avatar.png?v=64.5.1'),'login brand must use the Moaru mascot');
console.log('AUTH_SESSION_UI_OK');
