const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const rt=read('js/adapters/realtime.js'),rules=JSON.parse(read('database.rules.json')),config=read('js/config.js'),shell=read('js/ui/shell.js'),css=read('css/features/feed-classinfo-weekly.css'),index=read('index.html'),sw=read('sw.js'),app=read('js/app.js');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(rt.includes('CAPACITY_SOFT_LIMIT=92'),'soft capacity limit missing');
ok(rt.includes('CAPACITY_RETRY_MS=25000'),'waiting retry interval missing');
ok(rt.includes('await waitForCapacity();await loadFirebase()'),'capacity check must run before Firebase SDK connection');
ok(rt.includes('shallow:true'),'capacity check must use shallow REST for session keys');
ok(rt.includes('capacityRef.onDisconnect().remove()'),'capacity session must be removed on disconnect');
ok(rt.includes('기능 보존을 위해 입장을 계속합니다'),'capacity preflight must fail open');
ok(config.includes('capacitySessions:"moaru/v3/capacitySessions"'),'capacity path missing');
ok(rules.rules.moaru.v3.capacitySessions?.['.read']===true&&rules.rules.moaru.v3.capacitySessions?.['.write']===true,'capacity rules missing');
ok(shell.includes('현재 접속 인원이 많아 대기 중입니다.'),'capacity waiting UI missing');
ok(css.includes('.capacity-wait-host'),'capacity waiting styles missing');
ok(index.includes('realtime.js?v=64.5.15')&&index.includes('shell.js?v=64.5.7')&&index.includes('feed-classinfo-weekly.css?v=65.0.5')&&index.includes('js/config.js?v=64.5.1')&&index.includes('app.js?v=64.5.15'),'capacity cache versions stale');
ok(sw.includes('moaru-v64.5.15-capacity-gate-20260819')&&app.includes('sw.js?v=64.5.15'),'capacity service worker cache bump missing');
console.log('CAPACITY_GATE_OK');
