const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const js=read('js/tasks/quest-accordion.js'),css=read('css/features/quest-accordion.css'),html=read('index.html');
ok(js.includes('const subjectDone = total > 0 && completed >= total'),'outer subject completion state missing');
ok(js.includes('quest-subject-stamp')&&js.includes('과목 완료 도장'),'outer subject completion stamp missing');
ok(js.includes('text: subjectDone ? "완료" : `${completed}/${total}`'),'outer subject completion label missing');
ok(css.includes('.quest-subject-stamp')&&css.includes('.quest-accordion.completed'),'outer completion styling missing');
ok(html.includes('js/tasks/quest-accordion.js?v=26')&&html.includes('css/features/quest-accordion.css?v=29'),'outer completion cache version missing');
console.log('DAILY_SUBJECT_OUTER_COMPLETION_OK');
