const fs=require('fs');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const shop=fs.readFileSync('js/features/shopping.js','utf8');
const store=fs.readFileSync('js/shopping/store-service.js','utf8');
const server=fs.readFileSync('docs/apps-script/coin-shopping-extension.gs','utf8');
ok(shop.includes('preloadDeliveryMedia()'),'delivery media preload hook missing');
ok(shop.includes("audio.play().catch(() => {})"),'delivery audio playback missing');
const requestBlock=store.slice(store.indexOf('async function requestDelivery'),store.indexOf('const DEFINITE_GIFT_FAILURES'));
const returnPos=requestBlock.indexOf('return result;');
const refreshPos=requestBlock.indexOf('refreshInventory(true).catch(()=>{});');
ok(refreshPos>=0 && returnPos>refreshPos,'background inventory refresh arrangement missing');
ok(!requestBlock.includes('await refreshInventory(true)'),'delivery success still waits for inventory refresh');
ok(server.includes('function readShopInventoryFresh_'),'fresh inventory reader missing');
const managerBlock=server.slice(server.indexOf('function updateShopDeliveryByManager_'),server.indexOf('function handleShopDeliveryShipping'));
ok(managerBlock.includes('findShopInventoryItemFresh_(ownerId, inventoryId)'),'manager delivery mutation should use direct fresh item lookup');
const requestServer=server.slice(server.indexOf('function handleShopRequestDelivery'),server.indexOf('function handleShopDeliveryList'));
ok(requestServer.includes('findShopInventoryItemFresh_(userId, inventoryId)'),'delivery request should use direct fresh item lookup');
console.log('DELIVERY_STATE_AUDIO_LATENCY_OK');
