const fs=require('fs');
const feed=fs.readFileSync('js/features/feed.js','utf8');
const css=fs.readFileSync('css/features/feed-classinfo-weekly.css','utf8');
const game=fs.readFileSync('js/game-bridge/game-host.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(feed.includes('const expectedOn=post.hearts?.[uid]!==true')&&feed.indexOf('playHeartFeedback(button,expectedOn,true)')<feed.indexOf('await MiniTalk.Realtime.cloudTransaction(postPath'),'heart feedback must start inside the click gesture before network await');
ok(feed.includes('spawnHeartBurst(button,6')&&feed.includes('target.ownerDocument||MiniTalk.UI.Dom.doc()'),'heart burst visual was not strengthened');
ok(game.includes('function mobileGameMode()')&&game.includes('/CrOS/i.test(ua)'),'desktop/WhaleBook device split missing');
ok(game.includes('window.open("","MoaruMiniGame",popupFeatures())'),'desktop game popup launch missing');
ok(game.includes('width=${b.width},height=${b.height}')&&game.includes('Math.round(availWidth*.90)')&&game.includes('Math.round(availHeight*.90)'),'large popup sizing missing');
ok(game.includes('attachMessageWindow(popup)')&&game.includes('event.source!==frame.contentWindow'),'popup iframe score/exit message bridge missing');
ok(game.includes('if(!mobileGameMode()&&openDesktop(game))return;')&&game.includes('openInline(game)'),'mobile fallback / popup blocked fallback missing');
ok(html.includes('feed-classinfo-weekly.css?v=65.0.20')&&html.includes('js/features/feed.js?v=65.0.18')&&html.includes('js/game-bridge/game-host.js?v=21'),'asset cache versions stale');
console.log('FEED_HEART_DESKTOP_GAMES_OK');
