const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const friday=read('js/tasks/friday-grade6-mission.js');
const classInfo=read('js/tools/class-info.js');
const coin=read('docs/apps-script/coin.gs');
const html=read('index.html');
const css=read('css/features/feed-classinfo-weekly.css');
ok(friday.includes('REWARD_TYPE="WEEKLY_CHECK_OVER80"')&&friday.includes('REWARD_COIN=5'),'Friday weekly +5 reward constants missing');
ok(friday.includes('return scorePercent(record)>=80')&&friday.includes('reward_key:String(record.week||weekKey()),score_percent:String(scorePercent(record))'),'Friday reward threshold/week idempotency key missing');
ok(friday.includes('if(saved?.completed){closeWorksheet();const checked=await ensureWeeklyReward(saved)'),'completed Friday result does not retry pending reward acknowledgement');
ok(friday.includes('금요일 학습점검은 80점 이상이면 주 1회 보상됩니다.')&&friday.includes('주간 보상 +${REWARD_COIN}'),'Friday reward result UI missing');
ok(coin.includes('WEEKLY_CHECK_OVER80')&&coin.includes('weeklyScore < 80')&&coin.includes('delta = 5'),'Apps Script weekly >=80 reward validation/+5 missing');
ok(classInfo.includes('MiniTalk.UI.Dom.doc?.()||document')&&classInfo.includes('(doc.body||doc.documentElement).appendChild(i)'),'class-info picker is not attached to active UI document');
ok(classInfo.includes('win.addEventListener("focus",onFocus,{once:true})')&&classInfo.includes('i.addEventListener("change"'),'class-info picker cancellation/change cleanup missing');
ok(html.includes('js/tools/class-info.js?v=65.0.3')&&html.includes('js/tasks/friday-grade6-mission.js?v=65.0.16')&&html.includes('css/features/feed-classinfo-weekly.css?v=65.0.26'),'new class-info/Friday cache versions missing');
ok(css.includes('.friday-reward-card'),'Friday reward result styling missing');
console.log('FRIDAY_REWARD_CLASSINFO_UPLOAD_OK');
