const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const code=read('docs/apps-script/Code.gs'),coin=read('docs/apps-script/coin.gs');
const explorer=read('games/math-explorer.html'),tama=read('games/tamagotchi.html');
const host=read('js/game-bridge/game-host.js');
ok(code.includes('"수학탐험대"')&&code.includes('"마이다마고치"'),'new ranking sheets are not allowed by Apps Script');
ok(!code.includes('maybeAwardWeeklyGameTop3_')&&!code.includes('weekly_reward: weeklyReward'),'ranking requests must not pay weekly rewards immediately');
ok(coin.includes('function awardGameWeeklyTop3_')&&coin.includes('GAME_RANK_TOP3')&&coin.includes('"add", 1'),'weekly top3 +1 reward missing');
ok(coin.includes('gameName + ":" + weekKey'),'weekly reward key must be per-game and per-week');
ok(coin.includes('function runGameWeeklyRankingRewards()')&&coin.includes('weekday !== 1 || hour !== 9'),'Monday 09 KST payout guard missing');
ok(coin.includes('GAME_SHEETS.forEach(function(gameName)')&&coin.includes('Math.min(3, lastRow - 1)'),'scheduled top3 snapshot missing');
ok(coin.includes('function installGameWeeklyRankingRewardTrigger()')&&coin.includes('.onWeekDay(ScriptApp.WeekDay.MONDAY)')&&coin.includes('.atHour(9)')&&coin.includes('.nearMinute(0)')&&coin.includes('.inTimezone("Asia/Seoul")'),'Monday 09 KST Apps Script trigger installer missing');
ok(explorer.includes('hardMode ? 1.2 : 1'),'explorer hard ranking multiplier missing');
ok(!explorer.includes("type: 'MATH_EXPLORER_RESULT'"),'explorer must not duplicate the bridge result postMessage');
ok(host.includes('data.rankingScore')&&host.includes('data.hardMode?1.2:1'),'host explorer score bridge missing');
ok(tama.includes('setTimeout(reportGrowthScore,700)'),'tamagotchi resume ranking sync missing');
ok(code.includes('function ensureGameSheetHeader_')&&code.includes('sheet.insertRowsBefore(1, 1)')&&code.includes('setValues([headers])'),'game ranking sheet header initialization/migration missing');
const scoreService=read('js/games/score-service.js');
ok(!scoreService.includes('json.weekly_reward')&&!scoreService.includes('주간 TOP3 보상 🪙 +1'),'client must not perform immediate weekly rank payout handling');
console.log('GAME_RANKING_MONDAY_REWARD_OK');
