const fs = require('fs');
const path = require('path');
const html = fs.readFileSync(path.join(__dirname,'..','games','gugudan.html'),'utf8');
const games = fs.readFileSync(path.join(__dirname,'..','js','features','games.js'),'utf8');
const index = fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
function ok(cond,msg){ if(!cond){ console.error('FAIL',msg); process.exit(1); } }
ok(html.includes('const isTallPortrait = containerHeight > containerWidth * 1.2;'), 'tall portrait detection missing');
ok(html.includes('const availableGap = answers.length > 1'), 'available gap calculation missing');
ok(html.includes('const minGap = answers.length > 1'), 'minimum non-overlap gap missing');
ok(html.includes('segmentCount = count + 1'), 'natural spacing segment layout missing');
ok(html.includes('붙어 보이는 쌍 허용'), 'tight natural cluster behavior missing');
ok(html.includes('rawBottomOffsets'), 'irregular vertical offsets missing');
ok(html.includes('buildNaturalPositions'), 'natural horizontal spacing generator missing');
ok(html.includes('phaseOffsets'), 'staggered phase missing');
ok(html.includes('speedOffsets'), 'organic speed variation missing');
ok(!html.includes('speedRanks[index] * 180'), 'mechanical fixed speed ladder still present');
ok(html.includes('bottomSpread'), 'anti-row spread safeguard missing');
ok(!html.includes('ball.style.bottom = `${BALL_START_BOTTOM}px`'), 'all balls still share one start line');
ok(html.includes('const startBottom = BALL_START_BOTTOM + rawBottomOffsets[index]'), 'per-ball start bottom missing');
ok(html.includes('const newBottom = startBottom + maxRiseHeight * progress'), 'animation ignores per-ball start bottom');
ok(games.includes('games/gugudan.html?v=26'), 'gugudan cache bust not bumped');
ok(index.includes('js/features/games.js?v=23'), 'games loader cache bust not bumped');
console.log('GUGUDAN_NATURAL_FLOW_OK');
