const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const rt=read('js/adapters/realtime.js'),index=read('index.html'),sw=read('sw.js'),app=read('js/app.js');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(rt.includes('async function loadInitialMemberRooms()'),'initial member room loader missing');
ok(rt.includes('if(isRoomMember(room))memberOnly[id]=room'),'initial room load must keep joined rooms');
ok(rt.includes('await ensureDefaultRoom();await loadInitialMemberRooms();'),'initial joined rooms must load before workspace routing completes');
ok(!rt.includes('waitForCapacity')&&!rt.includes('capacitySessions')&&!rt.includes('CAPACITY_SOFT_LIMIT'),'custom capacity preflight must stay removed');
ok(rt.includes('await loadFirebase();'),'Firebase SDK should load directly without a capacity REST preflight');
ok(rt.includes('database.ref(".info/connected")'),'native Firebase connection state wait is missing');
ok(rt.includes('if(JSON.stringify(presenceCache[s.key])===JSON.stringify(next))return'),'presence initial child replay should be deduped');
ok(rt.includes('if(JSON.stringify(currentProfiles[c.key])===JSON.stringify(next))return'),'profile initial child replay should be deduped');
ok(index.includes('realtime.js?v=64.5.17')&&index.includes('app.js?v=64.5.18'),'login-room cache version stale');
ok(sw.includes('moaru-v64.5.18-wait-ui-20260819')&&app.includes('sw.js?v=64.5.18'),'service worker cache version stale');
console.log('LOGIN_ROOM_INITIALIZATION_OK');
