const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const rt=read('js/adapters/realtime.js'),shell=read('js/ui/shell.js'),index=read('index.html'),sw=read('sw.js'),app=read('js/app.js');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(rt.includes('async function loadInitialRooms()'),'initial room loader missing');
ok(rt.includes('if(isRoomMember(room))memberOnly[id]=room'),'initial room load must keep joined rooms');
ok(rt.includes('loadInitialRooms();'),'initial joined room bootstrap missing');
ok(!rt.includes('waitForConnected('),'Firebase connection must not gate login/workspace entry');
ok(rt.includes('function watchConnection(database)'),'Firebase connection should be observed without gating login');
ok(rt.includes('db=firebase.database();nextMode="firebase";watchConnection(db);startFirebase();'),'Firebase bootstrap should attach without waiting for .info/connected');
ok(shell.includes('MiniTalk.Realtime.init(user).then('),'workspace entry must not await realtime initialization');
ok(!shell.includes('const transport=await MiniTalk.Realtime.init(user)'),'workspace is still blocked by realtime initialization');
ok(rt.includes('if(JSON.stringify(presenceCache[s.key])===JSON.stringify(next))return'),'presence initial child replay should be deduped');
ok(rt.includes('JSON.stringify((kind==="legacy"?legacyProfiles:currentProfiles)[key])===JSON.stringify(value)'), 'profile delta replay should be deduped');
ok(index.includes('realtime.js?v=64.5.26')&&index.includes('app.js?v=64.5.26'),'login-room cache version stale');
ok(sw.includes('moaru-v64.5.26-room-feed-ui-fix-20260819')&&app.includes('sw.js?v=64.5.26'),'service worker cache version stale');
console.log('LOGIN_ROOM_INITIALIZATION_OK');
