const fs=require('fs'),vm=require('vm');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const engine=fs.readFileSync('js/ai/moa-communication-engine.js','utf8');
const gs=fs.readFileSync('docs/apps-script/MOA_AI.gs','utf8');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
ok(engine.includes('const VERSION = 95'),'v91 engine version missing');
ok(engine.includes('feedbackEvidenceKey')&&engine.includes('evidenceKey'),'v91 evidence key missing');
ok(engine.includes('tier==="solo"')&&engine.includes('tier==="growing"'),'v91 client tier weighting missing');
ok(html.includes('moa-communication-engine.js?v='),'v91 engine cache bust missing');
ok(sw.includes('moaru-runtime-bundle-'),'v91 service worker cache missing');
for(const token of ['moaPolicyLearningTier_','positive_score','negative_score','evidence_hashes','learning_tier','moa-public-learning-'])ok(gs.includes(token),'public policy learning missing '+token);
ok(gs.includes('function moaCleanupLegacySheets()')&&!gs.includes('moaV91CleanupLegacySheets'),'stable cleanup function missing');
const sandbox={console,Utilities:{base64EncodeWebSafe:x=>'hash',computeDigest:()=>[1,2,3],DigestAlgorithm:{SHA_256:'SHA_256'}},PropertiesService:{},SpreadsheetApp:{},CacheService:{},UrlFetchApp:{},LockService:{},ScriptApp:{}};
vm.createContext(sandbox);vm.runInContext(gs,sandbox);
ok(sandbox.moaPolicyLearningTier_(1,0,2.5,0,5)==='solo','one-user policy learning should reach solo');
ok(sandbox.moaPolicyLearningTier_(1,0,2.5,1,5)==='observing','negative one-user policy should not promote');
console.log('MOA_V91_SOLO_PUBLIC_LEARNING_OK');
