const fs=require('fs'),vm=require('vm');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const core=fs.readFileSync('js/ai/moa-dialogue-core.js','utf8');
const engine=fs.readFileSync('js/ai/moa-chat-engine.js','utf8');
const feature=fs.readFileSync('js/features/moa-chat.js','utf8');
const css=fs.readFileSync('css/features/moa-chat.css','utf8');
const gs=fs.readFileSync('docs/apps-script/MOA_CHAT.gs','utf8');
const html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8');
ok(html.includes('moa-dialogue-core.js?v=2')&&html.includes('moa-chat-engine.js?v=12'),'v85 cache bust missing');
ok(sw.includes('moa-conversation-v85-20260820'),'v85 sw cache missing');
ok(core.includes('function choose(family, entries)'),'dialogue repetition selector missing');
ok(core.includes("choose('activity'")&&core.includes("choose('concept'"),'broad dialogue families missing');
ok(engine.includes('recentReplyPatterns')&&engine.includes('freshPick'),'engine repeat guard missing');
ok(gs.includes('function moaWikiSearch_')&&gs.includes('function moaDuckHtmlSearch_'),'search fallback chain missing');
ok(gs.includes('🔎 ‘')&&gs.includes('찾아봤어'),'search result summary formatting missing');
ok(gs.includes('📍 ')&&gs.includes('☔ 강수확률 최대')&&gs.includes('💨 바람'),'weather readable format missing');
ok(feature.includes('moa-weather-card')&&feature.includes('linkLabel'),'rich result rendering missing');
ok(css.includes('.moa-ai-bubble.moa-info-card'),'info card CSS missing');
let observations=[];
const ctx={console,Math,Date,setTimeout,clearTimeout,URL,MiniTalk:{AI:{},Store:{get:k=>k==='user'?{user_id:'u1',nickname:'테스트'}:{}},Persistence:{get:()=>[],set:()=>{},remove:()=>{}},Tools:{},AuthApi:{moaSearch:async()=>({}),moaChat:async()=>({topic_hints:[]}),moaFeedback:async()=>({}),moaTopicObserve:async a=>{observations.push(a);return{}},moaReactionObserve:async()=>({}),moaReactionLexicon:async()=>({entries:[]}),moaMemoryGet:async()=>({}),moaMemorySet:async()=>({})}}};
vm.createContext(ctx);vm.runInContext(core,ctx);vm.runInContext(engine,ctx);const E=ctx.MiniTalk.AI.MoaChatEngine;
(async()=>{
  const seq=['오늘 방과후에 보드게임 했어','규칙이 생각보다 어렵더라','그래도 마지막엔 이겼어','친구가 진짜 아쉬워했음','다음엔 다른 게임 하기로 했어'];
  const replies=[];for(const t of seq)replies.push((await E.reply(t)).reply);
  ok(new Set(replies).size>=4,'general conversation replies too repetitive: '+JSON.stringify(replies));
  ok(replies.filter(v=>/계속 말해봐|그다음은|어떻게 됐어/.test(v)).length<=2,'continuation fallback overused: '+JSON.stringify(replies));
  const more=[];for(const t of ['슬라임 만들었어','종이접기 했어','새 게임 깔았어','책 읽었어'])more.push((await E.reply(t)).reply);
  ok(new Set(more).size>=3,'activity patterns repeat too much: '+JSON.stringify(more));
  console.log('MOA_V85_CONVERSATION_SEARCH_WEATHER_OK');
})().catch(e=>{console.error(e);process.exit(1)});
