const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..'),src=fs.readFileSync(path.join(root,'docs/apps-script/MOA_AI.gs'),'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const sandbox={console,JSON,Math,Date,String,Number,RegExp,encodeURIComponent,decodeURIComponent};
vm.createContext(sandbox);vm.runInContext(src,sandbox,{filename:'MOA_AI.gs'});
const seoul=sandbox.moaGeoPlace_('서울');
ok(seoul&&Math.abs(seoul.latitude-37.5665)<0.001&&Math.abs(seoul.longitude-126.9780)<0.001,'Seoul Korean-name fallback missing');
let forecastCalls=0;
sandbox.moaFetchJson_=url=>{forecastCalls++;if(!url.includes('latitude=37.5665')||!url.includes('longitude=126.978'))throw new Error('weather did not use Seoul fallback coordinates');return {current:{temperature_2m:26,apparent_temperature:27,weather_code:1,wind_speed_10m:8},daily:{temperature_2m_max:[29,30],temperature_2m_min:[21,22],precipitation_probability_max:[20,30],time:['2026-08-21','2026-08-22']}}};
const result=sandbox.moaWeatherSearch_('서울 오늘 날씨 알려줘');
ok(result&&result.kind==='weather'&&/서울/.test(result.reply)&&/26°/.test(result.reply),'Seoul weather quick prompt still fails');
ok(forecastCalls===1,'known Seoul should not need a geocoding request before forecast');
console.log('MOA_WEATHER_KOREAN_LOCATION_OK');
