const fs=require("fs"),path=require("path");
const root=path.resolve(__dirname,"..");
const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const ok=(v,m)=>{if(!v)throw new Error(m)};
const html=read("index.html"), chats=read("js/features/chats.js"), feature=read("js/features/moa-chat.js"), engine=read("js/ai/moa-chat-engine.js"), api=read("js/adapters/auth-api.js"), code=read("docs/apps-script/Code.gs"), chatGs=read("docs/apps-script/MOA_CHAT.gs"), learnGs=read("docs/apps-script/MOA_LEARNING.gs"), sw=read("sw.js"), install=read("docs/apps-script/MOA_AI_INSTALL.md");
ok(html.includes('css/features/moa-chat.css?v=1')&&html.includes('js/ai/moa-chat-engine.js?v=2')&&html.includes('js/features/moa-chat.js?v=2'),"moa client assets missing/stale");
ok(chats.includes('MiniTalk.Features.MoaChat?.listItem?.()')&&chats.includes('MOA_CHAT_INTEGRATION_START'),"moa fixed chat room/integration marker missing");
ok(feature.includes('모아와 대화하기')&&feature.includes('MiniTalk.Router.go("chats")'),"moa chat screen/back route missing");
ok(feature.includes('MiniTalk.DataCache')&&feature.includes('moa-chat-history')&&feature.includes('IndexedDB'),"visible moa chat history must stay in device IndexedDB cache");
ok(engine.includes('calculate(raw)')&&engine.includes('wikiSearch')&&engine.includes('detectPersonalMemory')&&engine.includes('sendNaturalFeedback')&&engine.includes('builtinReply'),"minimum conversation/natural-learning pipeline missing");
ok(engine.includes('builtin:hello')===false || true,"noop");
ok(engine.includes('builtin:${id}')&&engine.includes('previousSource'),"builtin natural-learning metadata missing");
ok(!/MiniTalk\.Realtime|MiniTalk\.Firebase|firebase\./i.test(engine),"moa AI engine must not depend on Firebase");
ok(api.includes('mode: "moa_chat"')&&api.includes('mode: "moa_feedback"')&&api.includes('previous_source')&&api.includes('MOA_CHAT_INTEGRATION_START'),"moa Apps Script API adapter/removal marker missing");
for(const mode of ['moa_chat','moa_feedback','moa_memory_get','moa_memory_set'])ok(code.includes(`case "${mode}"`),`Code.gs route missing: ${mode}`);
ok(code.includes('MOA_CHAT_INTEGRATION_START')&&code.includes('MOA_CHAT_INTEGRATION_END'),"Code.gs removal markers missing");
ok(chatGs.includes('CacheService.getScriptCache()')&&chatGs.includes('MOA_PHRASE_SHEET')&&chatGs.includes('MOA_DIALOG_SHEET'),"server cache/moa-only learning missing");
ok(!chatGs.includes('DIALOG_SHEET') || chatGs.includes('MOA_DIALOG_SHEET'),"legacy dialogue sheet linkage remains");
ok(!chatGs.includes('getSheet_(DIALOG_SHEET)'),"legacy `대화` sheet must not seed moa");
ok(chatGs.includes('/^builtin:/')&&chatGs.includes('pos>=2'),"builtin positive expression learning missing");
ok(learnGs.includes('correction')&&learnGs.includes('moaUpdatePhraseSignal_')&&learnGs.includes('previous_source')&&learnGs.includes('MOA_MEMORY_SHEET'),"natural learning or personal memory server foundation missing");
ok(feature.includes('완전히 제거')&&engine.includes('완전 제거')&&chatGs.includes('완전히 제거')&&learnGs.includes('완전 제거'),"removal guide comments missing");
ok(install.includes('기존 미나용 `대화` 시트와 **연결하지 않습니다.**')&&install.includes('완전 제거 방법'),"install/removal documentation missing");
ok(sw.includes('./js/ai/moa-chat-engine.js')&&sw.includes('./js/features/moa-chat.js')&&sw.includes('./css/features/moa-chat.css')&&sw.includes('MOA_CHAT_INTEGRATION_START'),"moa offline assets/removal marker missing");
console.log('MOA_AI_FOUNDATION_OK');
