const fs=require('fs'),vm=require('vm');
const src=fs.readFileSync('js/features/moa-chat.js','utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function node(tag,attrs={},children=[]){const n={tag,attrs:{...attrs},className:attrs.class||'',dataset:{},children:[],isConnected:true,textContent:attrs.text||'',append(...xs){this.children.push(...xs.filter(Boolean))},prepend(...xs){this.children.unshift(...xs.filter(Boolean))},remove(){this.isConnected=false},querySelector(sel){const match=x=>sel[0]==='.'?String(x.className||'').split(/\s+/).includes(sel.slice(1)):false;const walk=x=>{for(const c of x.children||[]){if(match(c))return c;const f=walk(c);if(f)return f}return null};return walk(this)}};for(const[k,v]of Object.entries(attrs)){if(k.startsWith('data-'))n.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(v);if(k==='onclick')n.onclick=v}n.append(...children);return n}
function makeContext({failPuts=0,delay=45}={}){let stored=[],puts=0;const Dom={el:node,doc:()=>({}),one(){return null},byId(){return null}};const ctx={console,setTimeout,clearTimeout,setInterval:()=>1,clearInterval(){},requestAnimationFrame:fn=>setTimeout(fn,0),document:{visibilityState:'visible',querySelector(){return null},addEventListener(){}},MiniTalk:{Features:{},UI:{Dom,Shell:{setHeader(){},modal(){},closeModal(){}}},Store:{get(k){if(k==='user')return{user_id:'u1',isGuest:false};return null},set(){}},DataCache:{async get(){return stored.map(x=>({...x}))},async put(_b,_k,value){puts++;await sleep(delay);if(puts<=failPuts)throw new Error('simulated storage failure');stored=value.map(x=>({...x}));return true},async remove(){stored=[]}},Persistence:{get(){return null},remove(){}},Router:{go(){}},Realtime:{unsubscribeMessages(){}},AI:{MoaCommunicationEngine:{maybeConnectionGreeting(){return{reply:'먼저 인사할게',candidateId:'g1',topic:''}},maybeInitiate(){return null},warmup(){},initiativeSettings(){return{enabled:true,quietStart:22,quietEnd:7}},clearContext(){}}},Registry:{register(){}},Events:{emit(){}}}};vm.createContext(ctx);vm.runInContext(src,ctx);return{ctx,get stored(){return stored},get puts(){return puts}}}
(async()=>{
  // 느린 저장: UI는 저장을 기다리지 않고 즉시 새글을 보여야 한다.
  {const env=makeContext({delay:80}),chat=env.ctx.MiniTalk.Features.MoaChat,first=chat.listItem();await sleep(8);ok(first.dataset.unread==='1','slow storage must not delay proactive unread UI');ok(first.querySelector('.conversation-preview').textContent==='먼저 인사할게','slow storage must not delay proactive preview');const second=chat.listItem();await sleep(25);ok(second.dataset.unread==='1','second list render must merge in-memory proactive message');await sleep(100);ok(env.puts===1,'rapid list refresh duplicated proactive save');ok(env.stored.length===1,'proactive message did not persist after delayed save')}
  // 일시 실패: UI는 유지되고 자동 재시도로 영구 저장되어야 한다.
  {const env=makeContext({failPuts:2,delay:5}),chat=env.ctx.MiniTalk.Features.MoaChat,node1=chat.listItem();await sleep(20);ok(node1.dataset.unread==='1','temporary storage failure hid proactive UI');await sleep(1100);ok(env.puts>=3,'temporary storage failure was not retried');ok(env.stored.length===1&&env.stored[0].text==='먼저 인사할게','retry did not persist proactive message')}
  // 지속 실패: 현재 세션 UI는 살아 있어야 하고 새 list render에서도 메시지가 사라지면 안 된다.
  {const env=makeContext({failPuts:99,delay:2}),chat=env.ctx.MiniTalk.Features.MoaChat,node1=chat.listItem();await sleep(20);const node2=chat.listItem();await sleep(30);ok(node1.dataset.unread==='1'&&node2.dataset.unread==='1','persistent storage failure must not kill proactive feature in current session');ok(node2.querySelector('.conversation-preview').textContent==='먼저 인사할게','memory fallback lost proactive preview during storage outage');await sleep(2050);ok(env.puts===4,'persistent storage outage must stop automatic retries after the bounded retry budget')}
  console.log('MOA_PROACTIVE_PERSISTENCE_OK');
})().catch(e=>{console.error(e);process.exit(1)});
