const fs=require('fs'),vm=require('vm');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const engine=fs.readFileSync('js/ai/moa-communication-engine.js','utf8');
const gs=fs.readFileSync('docs/apps-script/MOA_AI.gs','utf8');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
ok(engine.includes('const VERSION = 91'),'v91 engine version missing');
ok(engine.includes('feedbackEvidenceKey')&&engine.includes('evidenceKey'),'v91 evidence key missing');
ok(engine.includes('tier==="solo"')&&engine.includes('tier==="growing"'),'v91 client tier weighting missing');
ok(html.includes('moa-communication-engine.js?v=6'),'v91 engine cache bust missing');
ok(sw.includes('moaru-v64.5.49-task-reward-shopping-audit-v91-20260821'),'v91 service worker cache missing');
for(const token of ['moaLearningTier_','moaPolicyLearningTier_','positive_score','negative_score','evidence_hashes','learning_tier','moa-public-v91-'])ok(gs.includes(token),'v91 GS solo learning missing '+token);
ok(gs.includes('function moaCleanupLegacySheets()')&&!gs.includes('moaV91CleanupLegacySheets'),'stable cleanup function missing');
const sandbox={console,Utilities:{base64EncodeWebSafe:x=>'hash',computeDigest:()=>[1,2,3],DigestAlgorithm:{SHA_256:'SHA_256'}},PropertiesService:{},SpreadsheetApp:{},CacheService:{},UrlFetchApp:{},LockService:{},ScriptApp:{}};
vm.createContext(sandbox);vm.runInContext(gs,sandbox);
ok(sandbox.moaLearningTier_(1,0,2.2,0,3)==='solo','one-user phrase learning should reach solo');
ok(sandbox.moaLearningTier_(1,0,1.2,0,2)==='observing','weak one-user phrase learning promoted too early');
ok(sandbox.moaLearningTier_(2,0,2.1,0,2)==='growing','two-user phrase tier missing');
ok(sandbox.moaLearningTier_(3,0,3.0,0,3)==='confirmed','three-user phrase confirmation missing');
ok(sandbox.moaPolicyLearningTier_(1,0,2.5,0,5)==='solo','one-user policy learning should reach solo');
ok(sandbox.moaPolicyLearningTier_(1,0,2.5,1,5)==='observing','negative one-user policy should not promote');
console.log('MOA_V91_SOLO_PUBLIC_LEARNING_OK');
