const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),ok=(v,m)=>{if(!v)throw new Error(m)};
const html=read('index.html'),engine=read('js/ai/moa-communication-engine.js'),chat=read('js/features/moa-chat.js'),css=read('css/features/moa-chat.css'),gs=read('docs/apps-script/MOA_AI.gs'),sw=read('sw.js');
ok(html.includes('moa-communication-engine.js?v=48')&&html.includes('moa-chat.js?v=14')&&html.includes('moa-chat.css?v=6'),'v93 cache bust missing');
ok(sw.includes('moaru-moa-dialogue-fusion-final'),'v93 service worker cache missing');
ok(gs.includes('function moaWikiSummary_')&&gs.includes('/api/rest_v1/page/summary/'),'wikipedia summary fallback missing');
ok(gs.includes('function moaImageKnowledge_')&&gs.includes('image_url')&&gs.includes('image_search_url'),'image answer metadata missing');
ok(gs.includes('moa.search.v4.'),'v93 search cache generation missing');
ok(engine.includes('COMMON_KNOWLEDGE')&&engine.includes('지구')&&engine.includes('localKnowledgeReply'),'local knowledge safety net missing');
ok(!/\"(?:피카츄|이순신|세종대왕)\"\s*:/.test(engine),'named-person client answer should use generic knowledge/search routing');
ok((engine.match(/greeting:\[/g)||[]).length===1&&engine.includes('오 왔네 ㅋㅋ 무슨 얘기부터 할까?'),'expanded base conversation pool missing');
ok(engine.includes('imageUrl=String(d.image_url||"")')&&engine.includes('imageSearchUrl=String(d.image_search_url||"")'),'engine image metadata propagation missing');
ok(chat.includes('moa-image-result')&&chat.includes('Google 이미지에서 더 보기 ↗'),'chat image result UI missing');
ok(css.includes('.moa-image-result-img')&&css.includes('cursor:zoom-in'),'image result style missing');
console.log('MOA_V93_KNOWLEDGE_IMAGE_CONVERSATION_OK');
