const fs=require("fs"),path=require("path");
const root=path.resolve(__dirname,"..");
const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const ok=(v,m)=>{if(!v)throw new Error(m)};
const html=read("index.html"), chats=read("js/features/chats.js"), feature=read("js/features/moa-chat.js"), core=read("js/ai/moa-dialogue-core.js"), engine=read("js/ai/moa-chat-engine.js"), api=read("js/adapters/auth-api.js"), code=read("docs/apps-script/Code.gs"), chatGs=read("docs/apps-script/MOA_CHAT.gs"), learnGs=read("docs/apps-script/MOA_LEARNING.gs"), sw=read("sw.js"), install=read("docs/apps-script/MOA_AI_INSTALL.md"), css=read("css/features/moa-chat.css");
ok(html.includes('css/features/moa-chat.css?v=4')&&html.includes('js/ai/moa-dialogue-core.js?v=2')&&html.includes('js/ai/moa-chat-engine.js?v=12')&&html.includes('js/features/moa-chat.js?v=6'),"moa client assets missing/stale");
ok(chats.includes('MiniTalk.Features.MoaChat?.listItem?.()')&&chats.includes('MOA_CHAT_INTEGRATION_START'),"moa fixed chat room/integration marker missing");
ok(feature.includes('모아와 대화하기')&&feature.includes('MiniTalk.Router.go("chats")'),"moa chat screen/back route missing");
ok(feature.includes('MiniTalk.DataCache')&&feature.includes('moa-chat-history')&&feature.includes('IndexedDB'),"visible moa chat history must stay in device IndexedDB cache");
ok(feature.includes('assets/mascot-avatar.png')&&!feature.includes('text:"모아","aria-hidden":"true"'),"moa must reuse the existing default mascot profile image");
ok(feature.includes('대화 반응이 모아 학습에 반영돼.')&&!feature.includes('그냥 평소처럼 얘기하면 돼. 맞다거나'),"moa learning hint must be short and direct");
ok(css.includes('.moa-answer-link')&&feature.includes('appendRichText'),"search answer links must render as safe clickable links");
ok(engine.includes('calculate(raw)')&&engine.includes('searchAssist')&&engine.includes('detectPersonalMemory')&&engine.includes('sendNaturalFeedback')&&core.includes('function analyze(text)')&&core.includes('function genericReply'),"conversation/search/natural-learning pipeline missing");
ok(engine.includes('context().slice(-6)')&&core.includes('contextReply')&&chatGs.includes('moaParseContext_')&&chatGs.includes('ctxHit'),"recent context must influence contextual follow-up matching");
ok(engine.includes('correction.test(raw)')&&engine.indexOf('correction.test(raw)')<engine.indexOf("feedback:'positive'")&&engine.includes('contrast=raw.split'),"correction/contrast detection must run before positive feedback");
ok(engine.includes('builtin:${id}')&&engine.includes('previousSource'),"builtin natural-learning metadata missing");
ok(!/MiniTalk\.Realtime|MiniTalk\.Firebase|firebase\./i.test(engine),"moa AI engine must not depend on Firebase");
ok(api.includes('mode: "moa_chat"')&&api.includes('mode: "moa_search"')&&api.includes('mode: "moa_feedback"')&&api.includes('previous_source')&&api.includes('MOA_CHAT_INTEGRATION_START'),"moa Apps Script API adapter/removal marker missing");
for(const mode of ['moa_chat','moa_search','moa_feedback','moa_topic_observe','moa_reaction_observe','moa_reaction_lexicon','moa_memory_get','moa_memory_set'])ok(code.includes(`case "${mode}"`),`Code.gs route missing: ${mode}`);
ok(code.includes('MOA_CHAT_INTEGRATION_START')&&code.includes('MOA_CHAT_INTEGRATION_END'),"Code.gs removal markers missing");
ok(chatGs.includes('CacheService.getScriptCache()')&&chatGs.includes('MOA_PHRASE_SHEET')&&chatGs.includes('MOA_DIALOG_SHEET'),"server cache/moa-only learning missing");
ok(!chatGs.includes('getSheet_(DIALOG_SHEET)'),"legacy `대화` sheet must not seed moa");
ok(chatGs.includes('/^builtin:/')&&chatGs.includes('positiveUsers>=2'),"builtin expression learning must require multiple distinct users");
ok(chatGs.includes('moaWeatherSearch_')&&chatGs.includes('open-meteo')&&chatGs.includes('moaCurrencySearch_')&&chatGs.includes('frankfurter')&&chatGs.includes('api.duckduckgo.com')&&chatGs.includes('wikipedia.org')&&chatGs.includes('news.google.com/rss/search'),"multi-source search helpers missing");
ok(learnGs.includes('moaAddUniqueHash_')&&learnGs.includes('supporter_hashes')&&learnGs.includes('moaExtractCorrection_'),"distinct-user learning/correction cleanup missing");
ok(learnGs.includes('count>=3?"review"')&&learnGs.includes('nextHashes!==hashes'),"same user must not repeatedly inflate correction confidence");
ok(feature.includes('완전히 제거')&&engine.includes('완전 제거')&&chatGs.includes('완전히 제거')&&learnGs.includes('완전 제거'),"removal guide comments missing");
ok(install.includes('기존 미나용 `대화` 시트와 **연결하지 않습니다.**')&&install.includes('완전 제거 방법'),"install/removal documentation missing");
ok(sw.includes('./js/ai/moa-dialogue-core.js')&&sw.includes('./js/ai/moa-chat-engine.js')&&sw.includes('./js/features/moa-chat.js')&&sw.includes('./css/features/moa-chat.css')&&sw.includes('MOA_CHAT_INTEGRATION_START'),"moa offline assets/removal marker missing");
console.log('MOA_AI_FOUNDATION_OK');
