const fs=require('fs');
const auth=fs.readFileSync('js/features/auth.js','utf8');
const shell=fs.readFileSync('js/ui/shell.js','utf8');
const feed=fs.readFileSync('js/features/feed.js','utf8');
const css=fs.readFileSync('css/features/feed-classinfo-weekly.css','utf8');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const app=fs.readFileSync('js/app.js','utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(shell.includes('function setAuthMode(active=true')&&shell.includes('header?.classList.toggle("hidden",Boolean(active))'),'auth header visibility helper missing');
ok(auth.includes('MiniTalk.UI.Shell?.setAuthMode?.(true)'),'auth/PiP return does not hide app header');
ok(shell.includes('setAuthMode(false);D().byId("authHost")?.classList.add("hidden")'),'workspace entry does not restore app header');
ok(feed.includes('MiniTalk.Chat.Linkify?.youtubeId?.(text)')&&feed.includes('youtube-nocookie.com/embed/')&&feed.includes('MiniTalk.Chat.Linkify?.displayText?.(post.text)'),'feed inline YouTube player missing');
ok(css.includes('.feed-youtube-player{')&&css.includes('aspect-ratio:16/9'),'feed YouTube player styling missing');
ok(html.includes('feed-classinfo-weekly.css?v=65.0.16')&&html.includes('js/features/feed.js?v=65.0.12')&&html.includes('js/features/auth.js?v=64.5.34')&&html.includes('js/ui/shell.js?v=64.5.31'),'new asset versions stale');
ok(sw.includes('moaru-v64.5.43-feed-heart-state-audio-reward-20260820')&&app.includes('sw.js?v=64.5.43'),'service worker cache version stale');
console.log('PIP_AUTH_FEED_YOUTUBE_OK');
