const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const shell=fs.readFileSync(path.join(root,'js/ui/shell.js'),'utf8');
const css=fs.readFileSync(path.join(root,'css/app.css'),'utf8');
const auth=fs.readFileSync(path.join(root,'js/features/auth.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(shell.includes('shell?.classList.toggle("auth-mode",Boolean(active))'),'auth mode does not retile app shell');
ok(shell.includes('header?.classList.toggle("hidden",Boolean(active))'),'auth mode does not hide header');
ok(css.includes('.app-shell.auth-mode{grid-template-rows:minmax(0,1fr)}'),'auth host is still confined to header grid row');
ok(css.includes('.app-shell.auth-mode .auth-host{grid-row:1;min-height:0;height:100%}'),'auth host full-height rule missing');
ok(auth.includes('MiniTalk.UI.Shell?.setAuthMode?.(true)')&&auth.includes('function returnToLogin()'),'PiP return/login auth mode wiring missing');
ok(html.includes('css/app.css?v=64.5.12')&&html.includes('js/ui/shell.js?v=64.5.32'),'auth layout cache bust missing');
console.log('PIP_AUTH_LAYOUT_OK');
