const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const profile=fs.readFileSync(path.join(root,'js/tools/profile-editor.js'),'utf8');
const rt=fs.readFileSync(path.join(root,'js/adapters/realtime.js'),'utf8');
const rules=JSON.parse(fs.readFileSync(path.join(root,'database.rules.json'),'utf8'));
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(profile.includes('PROFILE_DATA_LIMIT=15*1024'),'profile editor must target 15KB stored strings');
ok(profile.includes('let size=192')&&profile.includes('Math.max(112'),'profile resize range must stay suitable for small UI avatars');
ok(profile.includes('if(nextAvatar&&nextAvatar.length>PROFILE_DATA_LIMIT)nextAvatar=await compressAvatarSource(nextAvatar)'),'existing 15-30KB avatars must migrate on the next profile save instead of blocking status-only edits');
ok(rt.includes('avatar.length>15*1024')&&rt.includes('15KB 이하여야 합니다.'),'realtime save guard must match 15KB');
ok(rules.rules.profiles.$nickname['.validate'].includes('<= 15360'),'legacy profile rule must enforce 15KB');
ok(rules.rules.moaru.v3.profiles.$userId['.validate'].includes('<= 15360'),'v3 profile rule must enforce 15KB');
console.log('PROFILE_IMAGE_15KB_OK');
