const fs=require('fs'),vm=require('vm'),cryptoNode=require('crypto');
const path=require('path');const root=path.resolve(__dirname,'..');
class CE extends Event{constructor(type,opts={}){super(type);this.detail=opts.detail}}
class SharedStorage{constructor(){this.m=new Map()}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}}
const storage=new SharedStorage();
const channels=new Map();
class BC{constructor(name){this.name=name;this.onmessage=null;(channels.get(name)||channels.set(name,new Set()).get(name)).add(this)}postMessage(data){for(const c of channels.get(this.name)||[])if(c!==this&&c.onmessage)c.onmessage({data})}close(){channels.get(this.name)?.delete(this)}}
function makeCtx(label){const events=new EventTarget();const ctx={console,EventTarget,Event,CustomEvent:CE,URLSearchParams,fetch:async()=>{throw new Error('fetch not expected')},localStorage:storage,BroadcastChannel:BC,crypto:{randomUUID:()=>cryptoNode.randomUUID()},setInterval,clearInterval,setTimeout,clearTimeout,addEventListener:(t,f)=>events.addEventListener(t,f),removeEventListener:(t,f)=>events.removeEventListener(t,f),dispatchEvent:(e)=>events.dispatchEvent(e),window:null,document:{scripts:[],createElement(){throw new Error('DOM not expected')},head:{append(){}}}};ctx.window=ctx;vm.createContext(ctx);for(const f of ['js/config.js','js/core/namespace.js','js/core/events.js','js/core/store.js','js/adapters/realtime.js'])vm.runInContext(fs.readFileSync(root+'/'+f,'utf8'),ctx,{filename:f});ctx.MiniTalk.AdminSession={requireToken:()=>"test-admin-token"};ctx.label=label;return ctx}
(async()=>{const A=makeCtx('A'),B=makeCtx('B'),C=makeCtx('C');let bMsgs=[],bCmds=[],bTasks=[],cTasks=[],aProfiles=0,aRooms=0;A.MiniTalk.Events.on('rt:profiles',()=>aProfiles++);A.MiniTalk.Events.on('rt:rooms',()=>aRooms++);B.MiniTalk.Events.on('rt:message',m=>bMsgs.push(m));B.MiniTalk.Events.on('rt:command',c=>bCmds.push(c));B.MiniTalk.Events.on('rt:tasks',t=>bTasks.push(t));C.MiniTalk.Events.on('rt:tasks',t=>cTasks.push(t));await A.MiniTalk.Realtime.init({user_id:'a',nickname:'A'});if(aRooms!==1)throw new Error('local init emitted rooms more than once: '+aRooms);await B.MiniTalk.Realtime.init({user_id:'b',nickname:'B'});await C.MiniTalk.Realtime.init({user_id:'b',nickname:'B2'});await B.MiniTalk.Realtime.subscribeMessages('global');const beforeProfile=aProfiles;await A.MiniTalk.Realtime.saveProfile({statusMsg:'hello'});await new Promise(r=>setTimeout(r,10));if(aProfiles-beforeProfile!==1)throw new Error('profile save emitted duplicate local events: '+(aProfiles-beforeProfile));const created=await A.MiniTalk.Realtime.createRoom('테스트방');if(!created||created.title!=='테스트방')throw new Error('create room failed');await A.MiniTalk.Realtime.sendMessage('global',{text:'hello'});await new Promise(r=>setTimeout(r,10));if(bMsgs.length!==1||bMsgs[0].text!=='hello')throw new Error('cross-context message failed '+JSON.stringify(bMsgs));await A.MiniTalk.Realtime.sendMessage('global',{type:'file',text:'[파일] a.txt',fileUrl:'https://example.com/a.txt',fileName:'a.txt'});await new Promise(r=>setTimeout(r,10));if(bMsgs.length!==2||bMsgs[1].type!=='file'||bMsgs[1].fileName!=='a.txt')throw new Error('file payload failed '+JSON.stringify(bMsgs));await A.MiniTalk.Realtime.sendCommand('b','NOTICE',{body:'hi'});await new Promise(r=>setTimeout(r,10));if(bCmds.length!==1||bCmds[0].type!=='NOTICE')throw new Error('command failed '+JSON.stringify(bCmds));await A.MiniTalk.Realtime.assignTask('b',{title:'T'});await new Promise(r=>setTimeout(r,10));if(!bTasks.some(t=>Object.values(t).some(x=>x.title==='T')))throw new Error('task failed '+JSON.stringify(bTasks));const taskSet=bTasks.find(t=>Object.values(t).some(x=>x.title==='T'));const taskId=Object.values(taskSet).find(x=>x.title==='T').id;await B.MiniTalk.Realtime.submitTask(taskId,'done');await new Promise(r=>setTimeout(r,10));if(!cTasks.some(t=>t[taskId]?.status==='submitted'&&t[taskId]?.answer==='done'))throw new Error('task submit did not sync to second local window '+JSON.stringify(cTasks));A.MiniTalk.Realtime.cleanup();B.MiniTalk.Realtime.cleanup();C.MiniTalk.Realtime.cleanup();console.log('REALTIME_LOCAL_INTEGRATION_OK')})().catch(e=>{console.error(e);process.exit(1)})
