const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8'),ok=(v,m)=>{if(!v)throw new Error(m)};
const rt=read('js/adapters/realtime.js'),chat=read('js/features/chats.js'),html=read('index.html');
const between=(a,b)=>{const i=rt.indexOf(a),j=rt.indexOf(b,i+1);ok(i>=0&&j>i,`missing block ${a}`);return rt.slice(i,j)};
const memberSummary=between('  function attachMemberSummary(roomId,membership){','  function startMemberRoomIndexSubscription(){');
const groupSummary=between('  async function startRoomListSubscription(){','  function startFirebase(){');
const messageSub=between('  async function subscribeMessages(roomId){','  async function loadOlderMessages(roomId,beforeTs,beforeId=""){');
const indexRepair=between('  async function ensureCurrentUserRoomIndex(){','  function attachMemberSummary(roomId,membership){');
const saveRoom=between('  async function saveRoom(room,{syncMemberships=true,newRoom=false}={}){','  async function createRoom(title,password=""){');
ok(rt.includes('const ROOM_INDEX_VERSION=4'),'one-time room index repair version missing');
ok(indexRepair.includes('if(Number(ready.val()||0)>=ROOM_INDEX_VERSION)return'),'room index repair must be version-gated');
ok(indexRepair.match(/db\.ref\(MiniTalkConfig\.paths\.rooms\)\.once\("value"\)/g)?.length===1,'room index repair should scan rooms only once in its gated migration');
ok(!memberSummary.includes('authoritativeRoom('),'normal member summary updates must not download full room detail');
ok(memberSummary.includes('limitToLast(1).once("value")'),'broken summary repair must read only the latest message');
ok(!groupSummary.includes('getRoom(')&&!groupSummary.includes('authoritativeRoom(')&&!groupSummary.includes('MiniTalkConfig.paths.rooms'),'group directory must stay summary-only');
ok(rt.includes('function stopRoomListSubscription(){roomListRequested=false;clearGroupRoomSubscription();roomDirectoryCache={...roomsCache};publishRooms()}'),'group listener must stop only when chat feature leaves and drop stale directory cache');
ok(groupSummary.includes('orderByChild("lastMessageAt").startAt(1)'),'group directory must query only rooms with message activity');
ok(saveRoom.includes('if(newRoom){')&&saveRoom.includes('blocked=new Set(["lastMessage"'),'existing-room metadata save must preserve last-message fields');
ok(!saveRoom.includes('[`${roomSummariesPath()}/${room.id}`]:roomSummaryValue(room)'),'existing room save must not overwrite whole summary');
ok(messageSub.includes('MiniTalk.DataCache?.getMessages?.(cacheRoom,CHAT_PAGE_SIZE)'),'room entry must use local message cache first');
ok(messageSub.includes('cached.length&&lastTs>0?base.startAt(lastTs):base.limitToLast(CHAT_PAGE_SIZE)'),'room entry must fetch only cache delta or latest page');
ok(chat.includes('if(!room?._detail)room=await MiniTalk.Realtime.getRoom(roomId)'),'room detail must remain on-demand at entry');
ok(chat.includes('node.dataset.roomSignature=roomRenderSignature(room)')&&chat.includes('node.dataset.roomSignature!==signature'),'room list must update rows by delta instead of repainting all rows');
ok(!chat.slice(chat.indexOf('  function refreshRoomList(){'),chat.indexOf('  function roomPreview(room)')).includes('list.replaceChildren'),'room refresh must not replace the whole list');
ok(chat.includes('Number(room?.lastMessageAt||room?.last_message_at||0)>0'),'group visibility must not mistake metadata updatedAt for a message');
ok(groupSummary.includes('if(roomListRequested&&groupRoomUnsubs.length)return'),'reopening group filter must reuse the existing group summary listener');
ok(!chat.includes('else{MiniTalk.Realtime.stopRoomListSubscription?.();filter'),'all/unread/favorite filter switches must not tear down group subscription');
const openBlock=chat.slice(chat.indexOf('  async function openRoom('),chat.indexOf('  function quickRoomActions('));
ok(!openBlock.includes('stopRoomListSubscription'),'opening a room must not recreate group subscription when returning to the list');
ok(chat.includes('function leave(){MiniTalk.Store.set("activeRoom",null);MiniTalk.Realtime.unsubscribeMessages?.();MiniTalk.Realtime.stopRoomListSubscription?.();'),'group subscription must be released when leaving the chat feature');
ok(indexRepair.includes('Object.prototype.hasOwnProperty.call(roomSource,id)'),'stale userRooms cleanup must only remove indexes for rooms that truly do not exist');
ok(html.includes('realtime.js?v=64.5.46')&&html.includes('chats.js?v=64.5.25'),'cache bust versions missing');
console.log('ROOM_LIST_CACHE_ARCHITECTURE_PRESERVED_OK');
