const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const rt=fs.readFileSync(path.join(root,'js/adapters/realtime.js'),'utf8');
const chats=fs.readFileSync(path.join(root,'js/features/chats.js'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};

ok(rt.includes('const ROOM_INDEX_VERSION=2;'),'room index consistency version missing');
ok(rt.includes('if(Number(ready.val()||0)>=ROOM_INDEX_VERSION)return;'),'old incomplete room index is not rechecked once');
ok(rt.includes('const [roomsSnap,indexSnap]=await Promise.all'),'server rooms and userRooms are not reconciled together');
ok(rt.includes('if(!isRoomMember(room))continue;')&&rt.includes('rootUpdates[`${userRoomsPath(user.user_id)}/${id}`]=membershipValue(member);'),'actual server memberships do not rebuild missing userRooms entries');
ok(rt.includes('for(const id of Object.keys(indexed)){if(id!=="global"&&!actualIds.has(id))rootUpdates[`${userRoomsPath(user.user_id)}/${id}`]=null}'),'stale userRooms memberships are not removed');
ok(rt.includes('id:String(id||value.id||value.room_id||"")'),'Firebase child key is not canonical room id');
ok(rt.includes('const canonicalId=String(id||value.id||"")'),'summary does not use Firebase child key as canonical id');
ok(rt.includes('try{detail=await authoritativeRoom(id)}catch(error)')&&rt.includes('if(!detail||!isRoomMember(detail))'),'member room summary is trusted without actual room/member verification');
ok(rt.includes('그룹 대화방 본체 확인 실패 - 요약을 삭제하지 않습니다.')&&rt.includes('db.ref(`${roomSummariesPath()}/${id}`).remove().catch(()=>{})'),'group ghost summary handling is unsafe or missing');
ok(chats.includes('let room=verifiedRoom||await MiniTalk.Realtime.getRoom(roomId);'),'room entry still trusts device-local cached detail');
ok(!chats.includes('verifiedRoom||MiniTalk.Store.get("rooms")?.[roomId]'),'room entry still uses Store detail as authority');
ok(chats.includes('if(room.hasPassword){joinRoomDialog(room);return}'),'non-member locked room no longer asks for password');
ok(chats.includes('openRoom(room.id,joined)'),'successful password join cannot reopen without a second password prompt');
ok(rt.includes('if(room.id==="global"||isRoomMember(room))return room;'),'existing invited/joined member is forced to re-enter password');
ok(rt.includes('updates={[`${userRoomsPath(user.user_id)}/${roomId}`]:null}'),'leaving room does not remove membership index');
ok(index.includes('js/adapters/realtime.js?v=64.5.45')&&index.includes('js/features/chats.js?v=64.5.24'),'room consistency cache versions stale');
console.log('ROOM_SERVER_CONSISTENCY_OK');
