const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const rt=read('js/adapters/realtime.js'),chats=read('js/features/chats.js'),rules=JSON.parse(read('database.rules.json')),html=read('index.html');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(rt.includes('const isPendingInviteRecord=member=>'), 'pending invite classifier missing');
ok(rt.includes('String(membership.status||"")!=="invited"'), 'summary membership still trusts pending invites');
ok(rt.includes('status:"invited"')&&rt.includes('role:"invite"'), 'invitation is not stored as pending');
ok(!rt.includes('members[userId]={user_id:userId,nickname,role:"member",joinedAt:now,invitedAt:now'), 'invite still auto-adds room member');
ok(chats.includes('notifyRoomInvites(rooms)')&&chats.includes('memberRooms=Object.fromEntries'), 'pending invite notification/member filtering split missing');
ok(rt.includes('async function validateIndexedMembership(roomId,membership)'), 'legacy/stale userRooms repair missing');
ok(rt.includes('await db.ref(`${userRoomsPath(user.user_id)}/${roomId}`).remove()'), 'stale membership pruning missing');
ok(rt.includes('passwordMode="preserve"')&&rt.includes('detailRef.transaction(current=>'), 'room writes do not preserve password fields transactionally');
ok(rt.includes('passwordRevision=Math.max(0,Number(room.passwordRevision||0))+1'), 'password revision guard missing');
ok(rt.includes('passwordMode:"clear"')&&rt.includes('passwordMode:"replace"'), 'password mutation modes missing');
const roomRule=rules.rules.rooms.$roomId['.validate']||'';
ok(roomRule.includes("passwordRevision")&&roomRule.includes("passwordUpdatedAt")&&roomRule.includes("passwordHash"), 'Firebase room rule does not guard password removal');
const membershipRule=rules.rules.moaru.v3.userRooms.$userId.$roomId['.validate']||'';
ok(membershipRule.includes("status')")||membershipRule.includes("child('status')"), 'userRooms status validation missing');
ok(membershipRule.includes("root.child('rooms').child($roomId).child('members').child($userId).exists()"), 'userRooms member entry is not tied to actual room membership');
ok(html.includes('realtime.js?v=64.5.52')&&html.includes('features/chats.js?v=64.5.28'), 'room rootfix cache bust missing');
console.log('ROOM_MEMBERSHIP_PASSWORD_ROOTFIX_OK');
