const fs=require('fs');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const shell=fs.readFileSync('js/ui/shell.js','utf8');
const rt=fs.readFileSync('js/adapters/realtime.js','utf8');
const tasks=fs.readFileSync('js/tasks/task-service.js','utf8');
const shop=fs.readFileSync('js/shopping/store-service.js','utf8');
const gs=fs.readFileSync('docs/apps-script/coin-shopping-extension.gs','utf8');
const index=fs.readFileSync('index.html','utf8');
ok(!shell.includes('},700);')&&!shell.includes('},1400);')&&!shell.includes('},2200);'),'artificial feature startup delays remain');
ok(shell.includes('MiniTalk.Shopping.StoreService?.start?.(user)'),'shopping local-cache startup missing');
const start=shop.slice(shop.indexOf('function start('),shop.indexOf('async function enter'))
ok(!start.includes('refreshInventory(true)'),'shopping server inventory still competes with login');
ok(rt.includes('setInterval(pollServerCommands,30000)'),'server command fallback poll must be 30s');
ok(!rt.includes('setInterval(pollServerCommands,10000)'),'10s command polling regression');
ok(tasks.includes('setInterval(() => refresh(true).catch(() => {}), 30000)'),'task fallback poll must be 30s');
ok(!/writeShopAdminSession_\(userId, role, token\);\s*try \{ cleanupExpiredShopAdminSessions_\(\)/.test(gs),'admin unlock still scans all sessions on critical path');
ok(gs.includes('pendingShopPurchaseUserMarkerKey_')&&gs.includes('getProperty(pendingShopPurchaseUserMarkerKey_(userId)) === "1"'),'inventory pending recovery not marker-gated');
ok(!/function handleUserTaskList[\s\S]{0,500}cleanupCompletedMoaruTasks_\(\)/.test(gs),'user task list still runs global cleanup');
ok(gs.includes('MOARU_SHOP_CATALOG_DATA_CACHE')&&gs.includes('clearShopCatalogCaches_'),'shop catalog full-properties cache missing');
ok(index.includes('realtime.js?v=')&&index.includes('shell.js?v=')&&index.includes('task-service.js?v='),'latency rootfix cache bust missing');
console.log('SERVER_LATENCY_ROOTFIX_OK');
