const fs=require('fs'),vm=require('vm');
const src=fs.readFileSync('docs/apps-script/coin-shopping-extension.gs','utf8');
const a=src.indexOf('function createPurchasedInventory_('),b=src.indexOf('/*',a);if(a<0||b<0)throw new Error('purchase inventory helpers missing');
const fnSrc=src.slice(a,b);
let reads=0,writes=0,lastOpts=null;
const ctx={Date:{now:()=>100},Utilities:{getUuid:()=> 'u1'},readShopInventory_:()=>{reads++;return [{id:'existing',purchaseKey:'dup'}]},writeShopInventoryItem_:(user,item,row,opts)=>{writes++;lastOpts=opts||{};return item}};
vm.createContext(ctx);vm.runInContext(fnSrc,ctx);
let out=ctx.createPurchasedInventory_('u',{id:'p1',name:'연필',description:'',price:3},'dup');
if(reads!==1||writes!==0||out.id!=='existing')throw new Error('duplicate/retry path must still detect existing inventory');
reads=0;writes=0;lastOpts=null;
out=ctx.createFreshPurchasedInventory_('u',{id:'p1',name:'연필',description:'',price:3,imageUrl:'x'},'fresh');
if(reads!==0||writes!==1||out.purchaseKey!=='fresh')throw new Error('fresh purchase still performs redundant inventory read');
if(lastOpts?.knownNewId!==true||!lastOpts?.knownProduct)throw new Error('fresh purchase must declare only safe known-new/known-product facts');
console.log('SHOPPING_PURCHASE_SAFE_FRESH_FASTPATH_OK');