const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const service=fs.readFileSync(path.join(root,'js/shopping/store-service.js'),'utf8');
const realtime=fs.readFileSync(path.join(root,'js/adapters/realtime.js'),'utf8');
const ui=fs.readFileSync(path.join(root,'js/features/shopping.js'),'utf8');
const css=fs.readFileSync(path.join(root,'css/features/shopping-store.css'),'utf8');
const math=fs.readFileSync(path.join(root,'js/tasks/daily-math-quest.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const server=fs.readFileSync(path.join(root,'docs/apps-script/coin-shopping-extension.gs'),'utf8');
if(service.includes('const balance = await MiniTalk.Economy.CoinWallet.refresh(true)'))throw new Error('redundant pre-purchase balance request remains');
if(!service.includes('result.product?.imageUrl')||!service.includes('writeCatalog('))throw new Error('optimistic saved-image catalog update is missing');
if(!realtime.includes('pendingSync:true')||!realtime.includes('syncPendingShopInventory'))throw new Error('purchased inventory fallback/sync queue is missing');
if(!realtime.includes('firebaseAuthenticated&&!shopInventoryFallback'))throw new Error('protected shop inventory writes are not guarded by Firebase authentication');
if(!ui.includes('data.length > 7200')||!server.includes('SHOP_IMAGE_MAX_CHARS = 7200'))throw new Error('client/server product image limits do not match');
if(!server.includes('createTextFinder')||server.includes('SpreadsheetApp.flush();'))throw new Error('slow purchase-log scan or redundant spreadsheet flush remains');
if(!service.includes('CATALOG_CACHE_KEY')||!service.includes('refreshCatalog(true)'))throw new Error('startup catalog cache/prefetch is missing');
if(!service.includes('MiniTalk.AuthApi.shopGift')||!server.includes('function handleShopGift'))throw new Error('server-mediated gift flow is missing');
if(!service.includes('notifyGift')||!server.includes('giftedAt'))throw new Error('gift receipt notification metadata is missing');
if(ui.includes('관리자가 상품을 등록하면')||!ui.includes('상점을 준비하고 있어요'))throw new Error('empty shop copy is not clean');
if(!css.includes('.shop-market-mark::before')||!css.includes('.shop-empty-illustration > span::before'))throw new Error('shop diamond icons are not geometrically centered');
if(!css.includes('.shop-inventory-fab b { flex: 0 0 18px')||!css.includes('margin: 0; padding: 0'))throw new Error('inventory count badge alignment is stale');
if(!ui.includes('modal-close-button')||!math.includes('icon: "123"')||math.includes('icon: "∑"'))throw new Error('inventory close or elementary math icon polish is missing');
if(!html.includes('css/features/shopping-store.css?v=64.5.4')||!html.includes('js/features/shopping.js?v=64.5.4')||!html.includes('js/tasks/daily-math-quest.js?v=64.5.4'))throw new Error('shopping or math cache versions are stale');
console.log('SHOPPING_RELIABILITY_OK');
