const fs=require('fs');const s=fs.readFileSync('docs/apps-script/coin-shopping-extension.gs','utf8');const ok=(v,m)=>{if(!v)throw new Error(m)};
const gift=s.slice(s.indexOf('function handleShopGift('),s.indexOf('function normalizeDeliveryStatus_',s.indexOf('function handleShopGift(')));
ok(gift.includes('requireRegisteredShopUser_(p.user_id, registeredUsers)')&&gift.includes('requireRegisteredShopUser_(p.target_user_id, registeredUsers)'),'gift must preserve the established reward-account eligibility checks');
ok(gift.includes('findShopInventoryItemFresh_(userId, inventoryId)'),'gift must validate current source row/status');
ok(gift.includes('writeShopInventoryItem_(targetId, gift, 0, { knownProduct: source })'),'gift should reuse the already-known product without skipping destination id lookup');
ok(s.includes('knownProduct.id || knownProduct.productId'),'known product reuse must recognize an inventory source productId, otherwise gift performs the catalog read again');
ok(!gift.includes('knownNewId: true'),'gift retry must not bypass deterministic gift-id lookup');
ok(gift.includes('deleteShopInventoryItem_(userId, inventoryId, sourceFound && sourceFound.row)'),'gift source deletion no longer uses the already-known row');
ok(gift.includes('receipt.status === "done"')&&gift.includes('GIFT_REQUEST_CONFLICT'),'gift idempotency/request conflict protection regressed');
ok(gift.includes('status: "pending"')&&gift.includes('status: "done"'),'gift receipt transaction guard regressed');
console.log('SHOPPING_GIFT_SAFE_SPEEDPATH_OK');
