const fs=require("fs");
const css=fs.readFileSync("css/features/shopping-store.css","utf8");
const index=fs.readFileSync("index.html","utf8");
if(!/\.shop-inventory-panel\s*\{[^}]*grid-template-rows:\s*auto\s+auto\s+minmax\(0,\s*1fr\)/s.test(css)) throw new Error("보관함은 헤더/묶음배송/목록 3행이어야 합니다.");
if(!/\.shop-bulk-delivery\s*\{[^}]*z-index:\s*2/s.test(css)) throw new Error("묶음배송 액션줄이 목록에 가려질 수 있습니다.");
if(!/shopping-store\.css\?v=[^\"']+/.test(index)) throw new Error("shopping-store.css cache-bust가 없습니다.");
if(!/\.shop-inventory-v2-list\s*\{[^}]*grid-template-columns:\s*repeat\(2,minmax\(0,1fr\)\)/s.test(css)) throw new Error("보관함 v2가 2열 전용 그리드가 아닙니다.");
if(!/\.shop-inventory-v2-card\s*\{[^}]*grid-template-columns:\s*58px\s+minmax\(0,1fr\)[^}]*grid-template-rows:\s*auto\s+auto/s.test(css)) throw new Error("보관함 v2 카드가 이미지/정보/액션 전용 구조가 아닙니다.");
if(!/\.shop-inventory-v2-image\s*\{[^}]*width:\s*58px[^}]*height:\s*50px/s.test(css)) throw new Error("보관함 v2 이미지가 compact 크기가 아닙니다.");
if(!/\.shop-inventory-v2-actions\s*\{[^}]*grid-column:\s*1\s*\/\s*-1/s.test(css)) throw new Error("보관함 v2 액션줄이 카드 하단 전체폭을 사용하지 않습니다.");
if(!/\.shop-inventory-v2-check\s*\{[^}]*position:\s*absolute/s.test(css)) throw new Error("묶음배송 체크 UI가 카드와 분리되지 않았습니다.");
console.log("SHOPPING_INVENTORY_V2_TOOLBAR_LAYOUT_OK");
