const fs=require('fs'),path=require('path'),vm=require('vm');const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8'),ok=(v,m)=>{if(!v)throw new Error(m)};
const code=read('docs/apps-script/Code.gs'),server=read('docs/apps-script/coin-shopping-extension.gs'),auth=read('js/adapters/auth-api.js'),session=read('js/admin/session.js'),admin=read('js/features/admin.js'),shopping=read('js/features/shopping.js'),store=read('js/shopping/store-service.js'),wallet=read('js/economy/coin-wallet.js');
for(const mode of ['shop_request_delivery','shop_delivery_list','shop_delivery_shipping','shop_delivery_complete','shop_delivery_cancel'])ok(code.includes(`case "${mode}"`),`Code.gs route missing: ${mode}`);
ok(server.includes('MOARU_SHOP_INVENTORY_SHEET = "모아루_쇼핑보관함"')&&server.includes('function readShopInventoryRowsForUser_')&&server.includes('.getValues()\n    .map(shopInventoryRowToItem_)'),"sheet-based inventory single-read path missing");
ok(server.includes('requireShopManagerToken_')&&server.includes('role === "SHOP_MANAGER"')&&server.includes('handleShopDeliveryList'),"server SHOP_MANAGER role or delivery API missing");
ok(auth.includes('shopDeliveryList')&&auth.includes('shopDeliveryShipping')&&auth.includes('shopDeliveryComplete')&&auth.includes('shopDeliveryCancel'),"client delivery APIs missing");
ok(session.includes('currentRole')&&session.includes('SHOP_MANAGER')&&session.includes('requireToken(permission = "ANY")'),"client role-aware admin session missing");
ok(admin.includes('role==="SHOP_MANAGER"')&&admin.includes('deliveryAdminPanel'),"SHOP_MANAGER restricted admin view missing");
ok(shopping.includes('function deliveryAdminPanel')&&shopping.includes('배송완료')&&shopping.includes('배송 시작'),"delivery manager panel missing");
ok(!store.includes('setInterval(()=>refreshInventory(true).catch(()=>{}),15000)')&&store.includes('SHOP_DELIVERY_COMPLETED'),"15-second inventory polling remains or signal refresh missing");
ok(!wallet.includes('Math.max(0, Math.floor(Number(MiniTalk.Store.get("coins"))')&&!wallet.includes('Math.max(0, Math.floor(Number(amount)'),"wallet still clamps negative coins");
// Role token acceptance: SHOP_MANAGER must authenticate without gaining ADMIN.
const state=new Map(),ctx={console,MiniTalk:{Store:{get:k=>state.get(k),set:(k,v)=>state.set(k,v)},AuthApi:{adminUnlock:async()=>({role:'SHOP_MANAGER',shop_manager:true,admin_token:'shop-token',expires_in:3600})}}};ctx.MiniTalk.Store.set('user',{user_id:'u1'});vm.createContext(ctx);vm.runInContext(session,ctx,{filename:'session.js'});
(async()=>{const role=await ctx.MiniTalk.AdminSession.unlock('shop');ok(role==='SHOP_MANAGER'&&ctx.MiniTalk.AdminSession.isShopManager()&&!ctx.MiniTalk.AdminSession.isAdmin(),"SHOP_MANAGER session role is incorrect");ok(ctx.MiniTalk.AdminSession.requireToken('SHOP')==='shop-token',"SHOP_MANAGER token rejected for shop permission");let denied=false;try{ctx.MiniTalk.AdminSession.requireToken('ADMIN')}catch{denied=true}ok(denied,"SHOP_MANAGER incorrectly gained full ADMIN permission");console.log('SHOP_MANAGER_SHEET_SCALE_OK')})().catch(e=>{console.error(e);process.exitCode=1});
