const fs=require("fs");
const css=fs.readFileSync("css/features/shopping-store.css","utf8");
const index=fs.readFileSync("index.html","utf8");
if(!/\.shop-inventory-panel\s*\{[^}]*grid-template-rows:\s*auto\s+auto\s+minmax\(0,\s*1fr\)/s.test(css)) throw new Error("보관함은 헤더/묶음배송/목록 3행이어야 합니다.");
if(!/\.shop-bulk-delivery\s*\{[^}]*z-index:\s*2/s.test(css)) throw new Error("묶음배송 액션줄이 목록에 가려질 수 있습니다.");
if(!/shopping-store\.css\?v=[^\"']+/.test(index)) throw new Error("shopping-store.css cache-bust가 없습니다.");
if(!/\.shop-inventory-item:has\(\.shop-inventory-image\)\s*\{[^}]*grid-template-columns:\s*52px\s+minmax\(0,1fr\)\s+auto/s.test(css)) throw new Error("보관함 일반 행이 이미지/정보/액션의 컴팩트 3열 구조가 아닙니다.");
if(!/@media\(max-width:560px\)[\s\S]*?\.shop-inventory-item:has\(\.shop-inventory-image\)\s*\{[^}]*grid-template-columns:\s*48px\s+minmax\(0,1fr\)\s+auto/s.test(css)) throw new Error("작은 화면에서 보관함 행이 세로 카드로 되돌아갑니다.");
if(!/\.shop-inventory-actions\s*\{[^}]*flex-wrap:\s*nowrap/s.test(css)) throw new Error("보관함 액션 버튼이 불필요하게 여러 줄로 꺾일 수 있습니다.");
console.log("SHOPPING_BULK_TOOLBAR_LAYOUT_OK");
