const fs=require('fs'),vm=require('vm'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),src=fs.readFileSync(path.join(root,'docs/apps-script/coin-shopping-extension.gs'),'utf8');
let rewardReads=0,rewardWrites=0;
class Finder{constructor(range,text){this.range=range;this.text=String(text)}matchEntireCell(){return this}findNext(){for(let i=0;i<this.range.nr;i++){const rr=this.range.r-1+i,val=String(this.range.sheet.rows[rr]?.[this.range.c-1]??'');if(val===this.text)return{getRow:()=>rr+1}}return null}}
class Range{constructor(sheet,r,c,nr=1,nc=1){Object.assign(this,{sheet,r,c,nr,nc})}getValues(){if(this.sheet.name==='보상')rewardReads++;return Array.from({length:this.nr},(_,i)=>Array.from({length:this.nc},(_,j)=>this.sheet.rows[this.r-1+i]?.[this.c-1+j]??''))}getValue(){return this.getValues()[0][0]}setValue(v){if(this.sheet.name==='보상')rewardWrites++;while(this.sheet.rows.length<this.r)this.sheet.rows.push([]);this.sheet.rows[this.r-1][this.c-1]=v;return this}setValues(vals){vals.forEach((row,i)=>row.forEach((v,j)=>{while(this.sheet.rows.length<this.r+i)this.sheet.rows.push([]);this.sheet.rows[this.r-1+i][this.c-1+j]=v}));return this}createTextFinder(t){return new Finder(this,t)}}
class Sheet{constructor(name,rows=[]){this.name=name;this.rows=rows.map(r=>r.slice())}getLastRow(){return this.rows.length}getLastColumn(){return Math.max(0,...this.rows.map(r=>r.length))}getRange(r,c,nr=1,nc=1){return new Range(this,r,c,nr,nc)}appendRow(row){this.rows.push(row.slice())}deleteRow(r){this.rows.splice(r-1,1)}setFrozenRows(){}}
class SS{constructor(){this.sheets=new Map()}getSheetByName(n){return this.sheets.get(n)||null}insertSheet(n){const s=new Sheet(n);this.sheets.set(n,s);return s}}
const ss=new SS();ss.sheets.set('보상',new Sheet('보상',[['user_id','username','coin','url'],['u1','user',10,'']]));ss.sheets.set('로그인',new Sheet('로그인',[['id','username','pw','nickname'],['u1','user','x','사용자']]));
const props=new Map([['SHOP_PRODUCT_p1',JSON.stringify({id:'p1',name:'연필',description:'HB',price:3,active:true,updatedAt:7})]]),cache=new Map([['moaru-known-user-v1-u1','1']]);
const propApi={getProperty:k=>props.get(k)||null,setProperty:(k,v)=>props.set(k,String(v)),deleteProperty:k=>props.delete(k),getProperties:()=>Object.fromEntries(props)};
const ctx={console,SHEET_ID:'sheet',REWARD_SHEET:'보상',LOGIN_SHEET:'로그인',COL_REWARD_USER_ID:1,COL_REWARD_USERNAME:2,COL_REWARD_COIN:3,MANUAL_WEB_APP_URL:'',SpreadsheetApp:{openById:()=>ss,getActive:()=>ss},getSheet_:n=>{const s=ss.getSheetByName(n);if(!s)throw new Error('missing '+n);return s},PropertiesService:{getScriptProperties:()=>propApi,getDocumentProperties:()=>propApi},CacheService:{getScriptCache:()=>({get:k=>cache.get(k)||null,put:(k,v)=>cache.set(k,String(v)),remove:k=>cache.delete(k)})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}}),getDocumentLock:()=>({tryLock:()=>true,waitLock(){},releaseLock(){}})},Utilities:{getUuid:(()=>{let n=0;return()=>`uuid-${++n}`})(),computeDigest:(alg,v)=>[...crypto.createHash('sha256').update(String(v)).digest()],DigestAlgorithm:{SHA_256:'sha256'},sleep(){}},ContentService:{MimeType:{JSON:'json'},createTextOutput:value=>({value,setMimeType(){return this}})},Date,Math,JSON,Object,String,Number,Array,Set,parseInt,isNaN};
vm.createContext(ctx);vm.runInContext(src,ctx,{filename:'coin-shopping-extension.gs'});
const out=JSON.parse(ctx.handleShopPurchase({parameter:{user_id:'u1',product_id:'p1',price:'3',expected_name:'연필',expected_description:'HB',expected_updated_at:'7',purchase_key:'pk-fast'}}).value);
if(!out.ok||out.newCoin!==7)throw new Error('purchase fast path failed '+JSON.stringify(out));
if(rewardReads!==1)throw new Error(`reward row should be read once on normal purchase, got ${rewardReads}`);
if(rewardWrites!==1)throw new Error(`reward coin should be written once on normal purchase, got ${rewardWrites}`);
if(ss.getSheetByName('구매로그').getLastRow()!==2)throw new Error('purchase log not written');
if(ss.getSheetByName('모아루_쇼핑보관함').getLastRow()!==2)throw new Error('inventory not written');
console.log('SHOPPING_SERVER_FASTPATH_RUNTIME_OK',JSON.stringify({rewardReads,rewardWrites,newCoin:out.newCoin}));
