const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');const root=path.resolve(__dirname,'..');
const server=fs.readFileSync(path.join(root,'docs/apps-script/coin-shopping-extension.gs'),'utf8');const ok=(v,m)=>{if(!v)throw new Error(m)};
class Finder{constructor(range,text){this.range=range;this.text=String(text);this.entire=false}matchEntireCell(v){this.entire=v;return this}matches(){const out=[];for(let r=0;r<this.range.nr;r++)for(let c=0;c<this.range.nc;c++){const rr=this.range.r-1+r,cc=this.range.c-1+c,val=String(this.range.sheet.rows[rr]?.[cc]??'');if((this.entire&&val===this.text)||(!this.entire&&val.includes(this.text)))out.push({getRow:()=>rr+1,getColumn:()=>cc+1})}return out}findNext(){return this.matches()[0]||null}findAll(){return this.matches()}}
class Range{constructor(sheet,r,c,nr=1,nc=1){Object.assign(this,{sheet,r,c,nr,nc})}getValues(){return Array.from({length:this.nr},(_,i)=>Array.from({length:this.nc},(_,j)=>this.sheet.rows[this.r-1+i]?.[this.c-1+j]??''))}setValues(vals){vals.forEach((row,i)=>row.forEach((v,j)=>{while(this.sheet.rows.length<this.r+i)this.sheet.rows.push([]);this.sheet.rows[this.r-1+i][this.c-1+j]=v}));return this}getValue(){return this.getValues()[0][0]}setValue(v){return this.setValues([[v]])}createTextFinder(t){return new Finder(this,t)}}
class Sheet{constructor(name){this.name=name;this.rows=[]}getLastRow(){return this.rows.length}getLastColumn(){return Math.max(0,...this.rows.map(r=>r.length))}getRange(r,c,nr=1,nc=1){return new Range(this,r,c,nr,nc)}appendRow(row){this.rows.push(row.slice());return this}deleteRow(r){this.rows.splice(r-1,1)}setFrozenRows(){}}
class SS{constructor(){this.sheets=new Map()}getSheetByName(n){return this.sheets.get(n)||null}insertSheet(n){const s=new Sheet(n);this.sheets.set(n,s);return s}}
const ss=new SS(),props=new Map(),cache=new Map();
const scriptProps={getProperty:k=>props.get(k)||null,setProperty:(k,v)=>props.set(k,String(v)),deleteProperty:k=>props.delete(k),getProperties:()=>Object.fromEntries(props),setProperties:o=>Object.entries(o).forEach(([k,v])=>props.set(k,String(v)))};
const ctx={console,SHEET_ID:'sheet',SpreadsheetApp:{openById:()=>ss},PropertiesService:{getScriptProperties:()=>scriptProps,getDocumentProperties:()=>scriptProps},CacheService:{getScriptCache:()=>({get:k=>cache.get(k)||null,put:(k,v)=>cache.set(k,String(v)),remove:k=>cache.delete(k)})},LockService:{getScriptLock:()=>({tryLock:()=>true,waitLock(){},releaseLock(){}}),getDocumentLock:()=>({tryLock:()=>true,waitLock(){},releaseLock(){}})},Utilities:{getUuid:(()=>{let n=0;return()=>`uuid-${++n}`})(),computeDigest:(alg,v)=>[...crypto.createHash('sha256').update(String(v)).digest()],DigestAlgorithm:{SHA_256:'sha256'},sleep(){}},ContentService:{MimeType:{JSON:'json'},createTextOutput:value=>({value,setMimeType(){return this}})}};
vm.createContext(ctx);vm.runInContext(server,ctx,{filename:'coin-shopping-extension.gs'});
ctx.readShopCatalog_=()=>({p1:{id:'p1',name:'연필',description:'HB',price:3,imageUrl:'data:image/webp;base64,AAAA',active:true,updatedAt:1}});
ctx.moaruRegisteredUserMap_=()=>({u1:'하나',manager:'매니저'});ctx.requireKnownMoaruUser_=()=>true;ctx.requireRegisteredShopUser_=(id)=>String(id||'');ctx.requireKnownMoaruUserCached_=(id)=>String(id||'');
const item=ctx.writeShopInventoryItem_('u1',{id:'inv-1',ownerId:'u1',productId:'p1',name:'연필',description:'HB',price:3,purchaseKey:'pk1',createdAt:1,deliveryStatus:'owned'});
ok(item.id==='inv-1'&&ctx.readShopInventory_('u1').length===1,'sheet inventory write/read failed');
let res=JSON.parse(ctx.handleShopRequestDelivery({parameter:{user_id:'u1',inventory_id:'inv-1',request_id:'r1'}}).value);ok(res.ok&&res.deliveryStatus==='requested','delivery request failed');
cache.set('shop-admin:shop-token',JSON.stringify({userId:'manager',role:'SHOP_MANAGER'}));
res=JSON.parse(ctx.handleShopDeliveryShipping({parameter:{user_id:'manager',admin_token:'shop-token',owner_id:'u1',inventory_id:'inv-1'}}).value);ok(res.ok&&res.deliveryStatus==='shipping','SHOP_MANAGER shipping transition failed');
res=JSON.parse(ctx.handleShopDeliveryComplete({parameter:{user_id:'manager',admin_token:'shop-token',owner_id:'u1',inventory_id:'inv-1'}}).value);ok(res.ok&&res.deliveryStatus==='completed','SHOP_MANAGER complete transition failed');
const final=ctx.readShopInventory_('u1')[0];ok(final.deliveryStatus==='completed'&&final.usedAt>0,'completed state was not persisted');
// Legacy property migrates once and is deleted only after verified sheet write.
props.set('MOARU_SHOP_INV_u2_inv-old',JSON.stringify({id:'inv-old',ownerId:'u2',productId:'p1',name:'옛상품',price:4,createdAt:2,deliveryStatus:'shipping'}));
const mig=ctx.migrateLegacyShopInventoryToSheetOnce();ok(mig.migrated===1&&!props.has('MOARU_SHOP_INV_u2_inv-old'),'legacy inventory was not safely migrated');ok(ctx.readShopInventory_('u2')[0].deliveryStatus==='shipping','legacy delivery status lost during migration');
console.log('SHOP_SHEET_FLOW_OK');
