const fs=require("fs");
const css=fs.readFileSync("css/features/shopping-store.css","utf8");
const index=fs.readFileSync("index.html","utf8");
if(!/\.shop-inventory-panel\s*\{[^}]*grid-template-rows:\s*auto\s+auto\s+minmax\(0,\s*1fr\)/s.test(css)) throw new Error("보관함은 헤더/묶음배송/목록 3행이어야 합니다.");
if(!/\.shop-bulk-delivery\s*\{[^}]*z-index:\s*2/s.test(css)) throw new Error("묶음배송 액션줄이 목록에 가려질 수 있습니다.");
if(!/shopping-store\.css\?v=[^\"']+/.test(index)) throw new Error("shopping-store.css cache-bust가 없습니다.");
if(!/\.shop-inventory-list\s*\{[^}]*grid-template-columns:\s*repeat\(2,minmax\(0,1fr\)\)/s.test(css)) throw new Error("보관함이 쇼핑 상품 카드처럼 2열 카드 그리드가 아닙니다.");
if(!/\.shop-inventory-item,.shop-inventory-item:has\(\.shop-inventory-image\)\s*\{[^}]*grid-template-columns:\s*1fr[^}]*grid-template-rows:\s*auto\s+minmax\(0,1fr\)\s+auto/s.test(css)) throw new Error("보관함 카드가 이미지/상품명/액션의 상품카드형 세로 구조가 아닙니다.");
if(!/\.shop-inventory-image\s*\{[^}]*width:\s*100%[^}]*aspect-ratio:\s*4\/3/s.test(css)) throw new Error("보관함 이미지가 쇼핑 상품 카드와 같은 비율로 표시되지 않습니다.");
if(!/\.shop-inventory-copy small\s*\{\s*display:\s*none\s*\}/s.test(css)) throw new Error("보관함에 불필요한 설명/상태 보조문구가 남아 있습니다.");
if(!/\.shop-inventory-actions\s*\{[^}]*flex-wrap:\s*nowrap/s.test(css)) throw new Error("보관함 선물/배송 버튼이 여러 줄로 꺾일 수 있습니다.");
console.log("SHOPPING_INVENTORY_PRODUCT_CARD_LAYOUT_OK");
