const fs=require("fs"),path=require("path");
const root=path.resolve(__dirname,".."),read=p=>fs.readFileSync(path.join(root,p),"utf8");
const realtime=read("js/adapters/realtime.js"),tasks=read("js/tasks/task-service.js"),taskFeature=read("js/features/tasks.js"),admin=read("js/features/admin.js"),shop=read("js/shopping/store-service.js"),feed=read("js/features/feed.js"),chats=read("js/features/chats.js"),index=read("index.html"),sw=read("sw.js"),app=read("js/app.js");
if(!realtime.includes('signals/${commandSignalRoom(user.user_id)}/wakeup')||!realtime.includes('pollServerCommands()}'))throw new Error("Firebase wakeup listener is missing");
if(!realtime.includes('mode==="firebase"?1800000:60000'))throw new Error("Firebase signal-first / sparse safety fallback policy is missing");
if(realtime.includes('setInterval(pollServerCommands,10000)')||realtime.includes('12000'))throw new Error("frequent command/task polling still exists");
if(tasks.includes('setInterval(() => refresh(true)')||tasks.includes('pollTimer'))throw new Error("task list background polling still exists");
if(!tasks.includes('async function enter()')||!taskFeature.includes('TaskService?.enter?.()')||!taskFeature.includes('leave(){entered=false;}'))throw new Error("task route-entry recovery refresh is missing");
if(admin.includes('const fallback=setInterval')||!admin.includes('tasks:admin-refresh'))throw new Error("admin task review still polls instead of using signal refresh");
if(!shop.includes('async function enter()')||shop.includes('setInterval(()=>refreshInventory(true)'))throw new Error("shopping is not route-scoped");
if(feed.includes('render(MiniTalk.UI.Dom.byId("viewHost"))'))throw new Error("feed changes still trigger full-screen render");
if(!chats.includes('startRoomListSubscription')||!chats.includes('stopRoomListSubscription'))throw new Error("room list is not route-scoped");
for(const ref of ['realtime.js?v=64.5.15','task-service.js?v=64.5.9','features/tasks.js?v=64.5.1','features/admin.js?v=64.5.9','app.js?v=64.5.15'])if(!index.includes(ref))throw new Error(`cache-busted signal-idle asset missing: ${ref}`);
if(!sw.includes('moaru-v64.5.15-capacity-gate-20260819')||!app.includes('sw.js?v=64.5.15'))throw new Error("signal-idle service worker cache bump missing");
console.log("SIGNAL_DRIVEN_IDLE_OK");
