const fs=require('fs');
const read=p=>fs.readFileSync(p,'utf8'),ok=(v,m)=>{if(!v)throw new Error(m)};
const tools=read('js/features/tools.js'),tasks=read('js/features/tasks.js'),accordion=read('js/tasks/quest-accordion.js'),math=read('js/tasks/daily-math-quest.js'),korean=read('js/tasks/daily-korean-quest.js'),friday=read('js/tasks/friday-grade6-mission.js'),css=read('css/features/quest-accordion.css'),html=read('index.html');
ok(tasks.includes('MiniTalk.UI.DragScroll?.bind?.(list);'),'tasks shared drag baseline missing');
ok(tools.includes('MiniTalk.UI.DragScroll?.bind?.(list,{allowInteractive:".profile-summary,.modern-tool,.shortcut-row"});'),'tools not aligned with shared task pointer drag');
ok(!tools.includes('documentMouseDrag:true'),'tools still uses separate mouse-only path');
ok(math.includes('rewardCoin: 1')&&korean.includes('rewardCoin: 1'),'daily subject reward amount not exposed in headers');
ok(accordion.includes('quest-subject-reward')&&accordion.includes('과목 완료 보상'),'quest reward badge rendering missing');
ok(css.includes('.quest-subject-reward')&&css.includes('.quest-subject-meta'),'quest reward badge CSS missing');
ok(friday.includes('text:`${subject} · 20문항`')&&friday.includes('text:`+${REWARD_COIN}`')&&friday.includes('text:"80점 이상"'),'weekly concise reward copy missing');
for(const noisy of ['큰 별도 창','주간 미션 · 시험지형','다음 주 ${subject'])ok(!friday.includes(noisy),`weekly implementation copy still visible: ${noisy}`);
for(const ref of ['quest-accordion.css?v=27','quest-accordion.js?v=24','daily-math-quest.js?v=64.5.7','daily-korean-quest.js?v=64.4.2','friday-grade6-mission.js?v=65.0.17','features/tools.js?v=64.5.6'])ok(html.includes(ref),`cache ref stale: ${ref}`);
console.log('TASK_TOOLS_UI_REGRESSION_OK');
