const fs=require('fs');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const drag=fs.readFileSync('js/ui/drag-scroll.js','utf8');
const tools=fs.readFileSync('js/features/tools.js','utf8');
const wm=fs.readFileSync('js/adapters/window-mode.js','utf8');
const html=fs.readFileSync('index.html','utf8');
ok(tools.includes('allowInteractive:".profile-summary,.modern-tool,.shortcut-row"'),'tools interactive drag allowance missing');
ok(!tools.includes('documentMouseDrag:true'),'tools must use the same default pointer drag path as tasks');
ok(drag.includes('doc.addEventListener("mousemove",move,{passive:false})'),'document mousemove drag path missing');
ok(wm.includes('preferInitialWindowPlacement:true'),'PiP must prefer requested initial placement/size');
ok(wm.includes('pipWindow.resizeTo?.(PIP_BOUNDS.width,PIP_BOUNDS.height)'),'PiP one-shot immediate size correction missing');
ok(!wm.includes('setTimeout(()=>pipWindow')&&!wm.includes('[80,260,700]'),'PiP delayed resize must not return');
ok(html.includes('drag-scroll.js?v=11')&&html.includes('tools.js?v=64.5.5')&&html.includes('window-mode.js?v=64.5.38'),'v101 cache refs stale');
console.log('V101_TOOLS_PIP_REAL_FIX_OK');
