const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const realtime=read('js/adapters/realtime.js'),feed=read('js/features/feed.js'),tools=read('js/features/tools.js'),friday=read('js/tasks/friday-grade6-mission.js'),css=read('css/features/feed-classinfo-weekly.css'),index=read('index.html'),sw=read('sw.js'),app=read('js/app.js');
if(realtime.includes('limitToLast(keep+50).once("value")'))throw new Error('message pruning still redownloads recent message bodies');
if(!realtime.includes('shallow=true')||!realtime.includes('pruneLastAt')||!realtime.includes('limitToFirst(excess)'))throw new Error('low-download message pruning is incomplete');
if(!realtime.includes('child_added')||!realtime.includes('child_changed')||!realtime.includes('presenceCache')||!realtime.includes('roomsCache'))throw new Error('room/presence child-event optimization is missing');
if(!realtime.includes('cloudSubscribeChildren'))throw new Error('child subscription adapter is missing');
if(realtime.includes('const snap=await ref.once("value"),saved='))throw new Error('sendMessage still re-downloads the message immediately after writing');
if(!realtime.includes('시트 백업은 이미 가진 메시지 내용과 clientTs로 충분합니다'))throw new Error('no-readback send path is missing');
if(realtime.includes('bindFirstValue(db.ref(MiniTalkConfig.paths.legacyProfiles)')||realtime.includes('bindFirstValue(db.ref(MiniTalkConfig.paths.profiles)'))throw new Error('profile lists still use whole-value live subscriptions');
if(!realtime.includes('legacyProfilesRef.once("value")')||!realtime.includes('currentProfilesRef.once("value")')||!realtime.includes('기존 프로필 변경을 읽지 못했습니다.')||!realtime.includes('프로필 변경을 읽지 못했습니다.'))throw new Error('profile child-event optimization is incomplete');
if(feed.includes('cloudSubscribe(STATE_PATH'))throw new Error('feed still subscribes to the entire feedState');
for(const required of ['cloudSubscribeChildren(POSTS_PATH','TOTALS_PATH','VIDEO_LIMIT=350*1024','feed-fab','video-gated','leave:stopSub'])if(!feed.includes(required))throw new Error(`feed optimization missing: ${required}`);
for(const removed of ['id: "notifications"','id: "timer"','id: "layout"'])if(tools.includes(removed))throw new Error(`removed tool still visible: ${removed}`);
for(const required of ['오늘의 타로','알람','놀이터','오늘의 시간표','오늘의 급식표'])if(!tools.includes(required))throw new Error(`expected tool missing: ${required}`);
if(friday.includes('평소에는 잠겨 있어요')||friday.includes('text:info.open?"시작":"잠김"'))throw new Error('old Friday mission lock copy/button remains');
for(const required of ['friday-lock-overlay','주간 미션','수학·국어 20문항'])if(!friday.includes(required))throw new Error(`Friday mission polish missing: ${required}`);
for(const required of ['.feed-fab','.feed-heart-total','.friday-lock-overlay','.video-gated'])if(!css.includes(required))throw new Error(`new UI style missing: ${required}`);
for(const required of ['feed-classinfo-weekly.css?v=65.0.5','realtime.js?v=64.5.15','friday-grade6-mission.js?v=65.0.3','feed.js?v=65.0.4','features/tools.js?v=64.5'])if(!index.includes(required))throw new Error(`cache-busted asset missing: ${required}`);
if(!sw.includes('moaru-v64.5.15-capacity-gate-20260819')||!app.includes('sw.js?v=64.5.15'))throw new Error('service worker cache bump missing');
console.log('TRAFFIC_UI_POLISH_OK');
