const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const rt=read('js/adapters/realtime.js'),chats=read('js/features/chats.js'),shell=read('js/ui/shell.js');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(rt.includes('mode="initializing"'),'realtime must distinguish initializing from true local fallback');
ok(rt.includes('async function awaitTransport()'),'transport readiness gate missing');
ok(rt.includes('function deferSubscription(setup)'),'subscription deferral helper missing');
ok(rt.includes('async function cloudSet(path,value){requireWritableUser();await awaitTransport();'),'cloud writes can fall into local storage during Firebase bootstrap');
ok(rt.includes('async function cloudTransaction(path,updater){requireWritableUser();await awaitTransport();'),'transactions can fall into local storage during Firebase bootstrap');
ok(rt.includes('async function sendMessage(roomId,payload){\n    await awaitTransport();'),'chat send can race Firebase bootstrap');
ok(rt.includes('requestedMessageRoom=String(roomId)'),'message subscription intent must survive transport bootstrap');
ok(rt.includes('roomListRequested=true;clearRoomListSubscription();\n    await awaitTransport();'),'group room subscription must survive transport bootstrap');
ok(rt.includes('return deferSubscription(()=>'),'cloud subscriptions must attach after transport resolves');
ok(!shell.includes('const transport=await MiniTalk.Realtime.init(user)'),'workspace must not wait for realtime transport');
ok(chats.includes('renderMessages(roomId);MiniTalk.Realtime.subscribeMessages(roomId).catch('),'room UI should render before network subscription completes');
ok(!chats.includes('await MiniTalk.Realtime.subscribeMessages(roomId)'),'room entry is still blocked by realtime subscription');
console.log('TRANSPORT_READY_RACE_OK');
