const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
class CE extends Event{constructor(type,options={}){super(type);this.detail=options.detail}}
const ctx={console,EventTarget,Event,CustomEvent:CE,window:null,document:{},setTimeout,clearTimeout};ctx.window=ctx;vm.createContext(ctx);
for(const file of ['js/core/namespace.js','js/core/events.js','js/core/store.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
ctx.MiniTalk.AuthApi={userDirectory:async()=>[{user_id:'a',nickname:'나'},{user_id:'b',nickname:'별이'},{user_id:'c',nickname:'구름'},{user_id:'guest-old',nickname:'게스트'},{user_id:'legacy-guest',nickname:'게스트1728'},{user_id:'guesthouse',nickname:'게스트하우스'},{user_id:'temporary',nickname:'임시',isGuest:true}]};
ctx.MiniTalk.Store.set('user',{user_id:'a',nickname:'나'});ctx.MiniTalk.Store.set('profiles',{b:{user_id:'b',nickname:'별이',avatar:'data:image/jpeg;base64,AA'},visitor:{user_id:'visitor',nickname:'손님',isGuest:true}});
vm.runInContext(fs.readFileSync(path.join(root,'js/core/user-directory.js'),'utf8'),ctx,{filename:'js/core/user-directory.js'});
(async()=>{const rows=await ctx.MiniTalk.UserDirectory.refresh();if(rows.map(row=>row.user_id).sort().join(',')!=='b,c,guesthouse')throw new Error('login-sheet users were not normalized, self/guests were not excluded');if(rows.some(row=>row.isGuest||row.user_id.startsWith('guest-')||/^게스트\s*\d*$/.test(row.nickname)))throw new Error('legacy guest appeared in a transfer recipient list');if(!rows.find(row=>row.user_id==='b')?.avatar)throw new Error('Firebase profile image was not merged into the login-sheet directory');ctx.MiniTalk.Store.set('profiles',{orphan:{user_id:'deleted-user',nickname:'삭제계정',avatar:'x'}});if(ctx.MiniTalk.UserDirectory.all().some(row=>row.user_id==='deleted-user'))throw new Error('Firebase-only deleted account appeared in a recipient list');ctx.MiniTalk.Store.set('user',{user_id:'b',nickname:'별이'});ctx.MiniTalk.AuthApi.userDirectory=async()=>[{user_id:'b',nickname:'별이'},{user_id:'d',nickname:'달'}];const switched=await ctx.MiniTalk.UserDirectory.refresh();if(switched.map(row=>row.user_id).join(',')!=='d')throw new Error('previous account directory cache leaked after account switch');const code=fs.readFileSync(path.join(root,'docs/apps-script/Code.gs'),'utf8'),server=fs.readFileSync(path.join(root,'docs/apps-script/coin-shopping-extension.gs'),'utf8'),shopping=fs.readFileSync(path.join(root,'js/features/shopping.js'),'utf8'),admin=fs.readFileSync(path.join(root,'js/features/admin.js'),'utf8');if((code.match(/case "user_directory"/g)||[]).length!==2||!server.includes('function handleUserDirectory')||!server.includes('function isMoaruGuestIdentity_'))throw new Error('Apps Script user-directory routing or legacy guest filter is incomplete');if(!shopping.includes('placeholder: "닉네임 검색"')||!admin.includes('MiniTalk.UserDirectory'))throw new Error('gift/admin nickname directory UI is incomplete');console.log('USER_DIRECTORY_OK',rows.length)})().catch(error=>{console.error(error);process.exit(1)});
