const fs=require("fs");
const read=f=>fs.readFileSync(f,"utf8"),ok=(v,m)=>{if(!v)throw new Error(m)};
const wm=read("js/adapters/window-mode.js"),drag=read("js/ui/drag-scroll.js"),feed=read("js/features/feed.js"),css=read("css/features/feed-classinfo-weekly.css"),html=read("index.html"),sw=read("sw.js");
ok(wm.includes("const PIP_BOUNDS={width:290,height:560}")&&wm.includes("documentPictureInPicture.requestWindow({...PIP_BOUNDS"),"290x560 PiP request missing");
ok(!wm.includes("[80,260,700].forEach")&&!wm.includes("enforcePiPBounds(pipWindow)"),"delayed PiP self-resize must be removed");
ok(drag.includes("overscroll-behavior:none;overscroll-behavior-y:none"),"drag surface must prevent overscroll chaining");
ok(feed.includes('[commentTrigger,heart].filter(Boolean)'),"feed controls must be comment then heart");
ok(css.includes(".feed-card-foot{display:flex;align-items:center;justify-content:flex-end;gap:8px"),"feed controls must align right");
ok(css.includes(".feed-comments{")&&feed.includes("commentsBlock(post)"),"comment display area must remain intact");
ok(html.includes("window-mode.js?v=64.5.38")&&html.includes("drag-scroll.js?v=10")&&html.includes("feed-classinfo-weekly.css?v=65.0.25")&&html.includes("feed.js?v=65.0.21"),"combined cache bust refs missing");
ok(sw.includes("moaru-v64.5.61-dragscroll-cleanup-v102-20260821"),"combined SW cache bump missing");
console.log("V92_COMBINED_PIP_FEED_LAYOUT_OK");
