const fs=require('fs'),vm=require('vm');
const read=p=>fs.readFileSync(p,'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const weekly=read('js/tasks/friday-grade6-mission.js'),html=read('index.html'),sw=read('sw.js'),gs=read('docs/apps-script/MOA_AI.gs');
ok(weekly.includes('const sourceView=MiniTalk.UI.Dom.doc()?.defaultView||window'),'weekly popup must use the live messenger/PiP view');
ok(weekly.includes('const gap=42'),'weekly popup must keep the same 42px safety gap');
ok(weekly.includes('sourceView.screenX??sourceView.screenLeft')&&weekly.includes('sourceView.outerWidth'),'weekly popup still uses the wrong browser window geometry');
ok(html.includes('friday-grade6-mission.js?v='),'weekly popup cache-bust missing');
ok(sw.includes('moaru-runtime-bundle-'),'v92 service worker cache id missing');
for(const token of ['function moaSearchContext_','function moaContextAnchor_','function moaCleanKnowledgeQuery_','function moaWikiExact_','function moaResultQuality_','function moaRankResults_','function moaFactualAnswer_','moa.search.v4.'])ok(gs.includes(token),`MOA smart search piece missing: ${token}`);
ok(gs.includes('"군산":"Gunsan"')&&gs.includes('"수원":"Suwon"')&&gs.includes('variants.push(q+"시")'),'Korean city geocoding fallback is incomplete');
const ctx={console};vm.createContext(ctx);vm.runInContext(gs,ctx);
ok(ctx.moaCleanKnowledgeQuery_('피카츄가 누구야','피카츄가 누구야')==='피카츄','fact question query cleanup failed');
const answer=ctx.moaFactualAnswer_('피카츄',[{title:'피카츄',snippet:'피카츄는 포켓몬스터에 등장하는 전기 타입 포켓몬이다. 노란 몸과 번개 모양 꼬리가 특징이다.',url:'https://ko.wikipedia.org/wiki/x',exact:true}]);
ok(answer.includes('피카츄')&&answer.includes('포켓몬'),'factual answer synthesis failed');
const anchor=ctx.moaContextAnchor_({context_json:JSON.stringify([{role:'user',text:'피카츄가 누구야?'},{role:'assistant',text:'답변'},{role:'user',text:'더 알려줘'}])});
ok(anchor==='피카츄가 누구야','follow-up context anchor failed');
console.log('V92_WEEKLY_POPUP_MOA_SMART_OK');
