const fs=require('fs'),vm=require('vm');
const read=p=>fs.readFileSync(p,'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const weekly=read('js/tasks/friday-grade6-mission.js');
const css=read('css/features/feed-classinfo-weekly.css');
const engine=read('js/ai/moa-communication-engine.js');
const html=read('index.html');
const sw=read('sw.js');
for(const token of ['correctAnswer:String(item.answer)','question:String(item.text','const REPORT_GUIDE=','function answerDetails(','function feedbackLine(','function wrongReviewCard(','text:"오답 확인"','text:"내 답"','text:"정답"'])ok(weekly.includes(token),`weekly report detail missing: ${token}`);
ok(weekly.includes('filter(x=>x.rate>=75)'),'strong feedback must be threshold-based instead of blindly taking top categories');
ok(weekly.includes('filter(x=>x.rate<100)'),'weak feedback must not list perfect categories as weaknesses');
ok(css.includes('.friday-wrong-toggle')&&css.includes('.friday-answer-compare'),'wrong-answer accordion styles missing');
ok(engine.includes('return "whatdoing"')&&engine.includes('return "hungry"')&&engine.includes('return "nervous"')&&engine.includes('return "confused"'),'new local conversation reactions missing');
for(const token of ['whatdoing:[','hungry:[','nervous:[','confused:['])ok(engine.includes(token),`new local dialogue pool missing: ${token}`);
ok(html.includes('feed-classinfo-weekly.css?v=65.0.25'),'weekly report CSS cache bust missing');
ok(html.includes('friday-grade6-mission.js?v=65.0.15'),'weekly mission cache bust missing');
ok(html.includes('moa-communication-engine.js?v=16'),'MOA local dialogue cache bust missing');
ok(sw.includes('moaru-tools-scroll-layout'),'v95 SW cache missing');
console.log('WEEKLY_REPORT_DIALOGUE_V95_OK');
