/* ============================================================
   APP SHELL
   - 인증/메뉴/헤더/모달/토스트만 관리합니다.
   - 각 feature의 기능 로직을 포함하지 않습니다.
   ============================================================ */
MiniTalk.UI.Shell=(()=>{
  const D=()=>MiniTalk.UI.Dom;let started=false,entering=false,activeUserId=null,modalCloseTimer=0;
  function toast(message){const host=D().byId("toastHost");if(!host)return;const item=D().el("div",{class:"toast",text:String(message||"")});host.append(item);requestAnimationFrame(()=>item.classList.add("show"));setTimeout(()=>{item.classList.remove("show");setTimeout(()=>item.remove(),220)},2600)}
  function closeModal(){const host=D().byId("modalHost");if(!host)return;clearTimeout(modalCloseTimer);host.classList.add("closing");const closingHost=host;modalCloseTimer=setTimeout(()=>{modalCloseTimer=0;if(closingHost.classList.contains("closing")){closingHost.className="modal-host hidden";closingHost.replaceChildren()}},170)}
  function modal(title,body){const host=D().byId("modalHost");clearTimeout(modalCloseTimer);modalCloseTimer=0;host.className="modal-host";const box=D().el("section",{class:"modal modal-enter",role:"dialog","aria-modal":"true","aria-label":title});const close=D().el("button",{class:"icon-button subtle",type:"button",text:"×","aria-label":"닫기",onclick:closeModal});const head=D().el("header",{},[D().el("strong",{text:title}),close]);box.append(head,body);host.replaceChildren(box);host.onclick=e=>{if(e.target===host)closeModal()};close.focus?.();return host}
  function setHeader(title,actions=[],opts={}){const titleNode=D().byId("headerTitle"),host=D().byId("headerActions"),back=D().byId("backBtn"),profile=D().byId("headerProfileButton");if(titleNode)titleNode.textContent=title;if(profile){profile.classList.toggle("hidden",opts.profile!==true);profile.disabled=opts.profile===true&&opts.profileEditable===false;profile.onclick=opts.profile===true&&opts.profileEditable!==false?opts.onProfile||null:null;profile.setAttribute("aria-label",profile.disabled?"프로필 수정은 로그인 후 이용할 수 있습니다":"내 프로필 설정");if(opts.profileNode)profile.replaceChildren(opts.profileNode)}if(host){const extra=[];if(MiniTalk.MobileImmersive?.isBrowserMode?.()&&!document.fullscreenElement)extra.push(D().el("button",{class:"icon-button subtle immersive-button",type:"button",text:"⛶","aria-label":"전체 화면",onclick:()=>MiniTalk.MobileImmersive.enterFromGesture().then(ok=>{if(!ok)toast("브라우저가 전체 화면 전환을 허용하지 않았습니다.")})}));host.replaceChildren(...actions,...extra)}if(back){back.classList.toggle("hidden",!opts.back);back.onclick=opts.back||null}}
  function visibleFeatures(){return MiniTalk.Registry.all().filter(f=>f.nav!==false&&(!f.isVisible||f.isVisible()))}
  function normalizedOrder(features){const preferred=["chats","tools","tasks","shopping","settings"],ids=features.map(f=>f.id);return[...preferred.filter(id=>ids.includes(id)),...ids.filter(id=>!preferred.includes(id))]}
  function navButton(feature){return D().el("button",{class:`nav-button ${MiniTalk.Store.get("route")===feature.id?"active":""}`,type:"button","data-route":feature.id,onclick:()=>MiniTalk.Router.go(feature.id)},[D().el("span",{text:feature.icon||"•"}),D().el("small",{text:feature.title})])}
  function renderNav(){const features=visibleFeatures(),order=normalizedOrder(features);features.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));const side=D().byId("sideRail"),bottom=D().byId("bottomNav");if(side)side.replaceChildren(...features.map(navButton));if(bottom)bottom.replaceChildren(...features.map(navButton))}
  function setActiveNav(id){const navId=id==="games"||id==="links"?"tools":id==="admin"?"settings":id;D().all("[data-route]").forEach(b=>b.classList.toggle("active",b.dataset.route===navId))}
  async function showApp(){document.getElementById("launchView")?.classList.add("hidden");D().byId("appShell")?.classList.remove("hidden");document.documentElement.classList.add("app-visible");if(!started){started=true;MiniTalk.Features.Auth.render(D().byId("authHost"))}const user=MiniTalk.Store.get("user");if(user)await enterWorkspace(user);MiniTalk.MobileImmersive?.afterAppShown?.()}
  async function enterWorkspace(user){if(entering||(activeUserId===user.user_id&&MiniTalk.Store.get("transport")!=="idle"))return;entering=true;try{D().byId("authHost")?.classList.add("hidden");D().byId("workspace")?.classList.remove("hidden");const transport=await MiniTalk.Realtime.init(user);activeUserId=user.user_id;renderNav();await MiniTalk.Router.go("chats");MiniTalk.Features.Admin?.applyStoredLock?.();if(!user.isGuest&&transport!=="firebase")toast("실시간 서버가 연결되지 않아 이 기기에만 저장됩니다.")}catch(error){toast(error.message||"초기화에 실패했습니다.");D().byId("authHost")?.classList.remove("hidden");D().byId("workspace")?.classList.add("hidden")}finally{entering=false}}
  function updateInstallButton(v){document.getElementById("installBtn")?.classList.toggle("hidden",!v)}
  function start(){MiniTalk.Events.on("state:transport",mode=>{const b=D().byId("connectionBadge");if(b){b.textContent=mode==="firebase"?"온라인":"로컬";b.dataset.mode=mode}});MiniTalk.Events.on("auth:success",enterWorkspace);MiniTalk.Events.on("install:available",updateInstallButton);MiniTalk.Events.on("state:admin",renderNav);addEventListener("keydown",event=>{if(event.key==="Escape"&&!D().byId("modalHost")?.classList.contains("hidden"))closeModal()});updateInstallButton(MiniTalk.WindowMode.canInstall?.()===true)}
  return{start,showApp,enterWorkspace,toast,modal,closeModal,setHeader,setActiveNav,renderNav};
})();
